//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol DUIApplicationTerminationDelegate
@property(readonly, nonatomic) BOOL canApplicationTerminate;
- (void)prepareForApplicationTerminationWithAbortHandler:(void (^)(BOOL, NSError *))arg1 doneHandler:(void (^)(void))arg2;
@end

