//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DUIBRTalk : NSObject
{
    struct BRTalkClientHandle *brtalkHandle;
    struct BRTalkClientRequest *brtalkRequest;
    BOOL _waitingForServices;
    void *_pendingContext;
    CDUnknownFunctionPointerType _pendingResponseCB;
    CDUnknownFunctionPointerType _pendingAbortCB;
}

@property(nonatomic) CDUnknownFunctionPointerType pendingAbortCB; // @synthesize pendingAbortCB=_pendingAbortCB;
@property(nonatomic) CDUnknownFunctionPointerType pendingResponseCB; // @synthesize pendingResponseCB=_pendingResponseCB;
@property(nonatomic) void *pendingContext; // @synthesize pendingContext=_pendingContext;
@property(nonatomic) BOOL waitingForServices; // @synthesize waitingForServices=_waitingForServices;
- (void)cancelRequest;
- (void)closeConnection;
- (void)onRequestEnded;
- (BOOL)isRequestPending;
- (BOOL)setEnablePromiscuousModeWithoutAuth:(BOOL)arg1 authorizationRef:(CDStruct_7a08cd8d *)arg2 checkAuthorization:(BOOL)arg3 context:(void *)arg4 doneCallback:(CDUnknownFunctionPointerType)arg5 abortCallback:(CDUnknownFunctionPointerType)arg6;
- (BOOL)updateNetworkConfig:(char *)arg1 authorizationRef:(CDStruct_7a08cd8d *)arg2 checkAuthorization:(BOOL)arg3 context:(void *)arg4 doneCallback:(CDUnknownFunctionPointerType)arg5 abortCallback:(CDUnknownFunctionPointerType)arg6;
- (BOOL)createBridgeForAdapter:(id)arg1 adapterName:(id)arg2 checkAuthorization:(BOOL)arg3 context:(void *)arg4 doneCallback:(CDUnknownFunctionPointerType)arg5 abortCallback:(CDUnknownFunctionPointerType)arg6;
- (BOOL)lookupBridgeForAdapter:(id)arg1 context:(void *)arg2 doneCallback:(CDUnknownFunctionPointerType)arg3 abortCallback:(CDUnknownFunctionPointerType)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)connectWithContext:(void *)arg1 doneCallback:(CDUnknownFunctionPointerType)arg2 abortCallback:(CDUnknownFunctionPointerType)arg3;
- (void)dealloc;

@end

