//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "NSApplicationDelegate.h"
//#import "VixCommandHandler.h"

@class DUIActionController, DUIActivityViewer, DUIDlgMgr, DUIDockTileController, DUIFeatures, DUIKeyboardAndMousePreferences, DUIUpdateController, NSString, VMServiceUser, VMUSBArbitratorController;

@interface DUIController : NSObject //<NSApplicationDelegate, VixCommandHandler>
{
    DUIActivityViewer *mDefaultActivityViewer;
    DUIDockTileController *mDockTileController;
    DUIActivityViewer *mFileCopyActivityViewer;
    struct DataCollection *mUserDataCollection;
    struct OpaqueEventHandlerRef *mEventHandlerRef;
    BOOL mShouldQuitOnPowerOff;
    DUIActionController *mActionController;
    VMServiceUser *mFusionServices;
    VMUSBArbitratorController *mVMUSBArbitratorController;
}

+ (void)initFoundry;
+ (void)initVMClient;
+ (void)initDefaultPreferences;
+ (void)initVMDBWithBriefApplicationName:(id)arg1;
+ (void)checkMASReceipt;
+ (void)initLowLevelWithPathToApplicationLogDirectory:(id)arg1 briefApplicationName:(id)arg2 product:(int)arg3;
+ (void)initApplicationWithPathToLogDirectory:(id)arg1 briefApplicationName:(id)arg2 product:(int)arg3;
+ (BOOL)isPaschalOvumAvailable;
+ (id)pathToLogDirectory;
+ (id)sharedController;
+ (BOOL)duiIsReady;
@property(retain, nonatomic) VMUSBArbitratorController *vmUSBArbitratorController; // @synthesize vmUSBArbitratorController=mVMUSBArbitratorController;
@property(nonatomic) struct DataCollection *userDataCollection; // @synthesize userDataCollection=mUserDataCollection;
@property(nonatomic) BOOL shouldQuitOnPowerOff; // @synthesize shouldQuitOnPowerOff=mShouldQuitOnPowerOff;
@property(retain, nonatomic) VMServiceUser *fusionServices; // @synthesize fusionServices=mFusionServices;
@property(readonly, retain, nonatomic) DUIDockTileController *dockTileController; // @synthesize dockTileController=mDockTileController;
@property(retain, nonatomic) DUIActionController *actionController; // @synthesize actionController=mActionController;
- (void)connectToServer:(id)arg1 withCaption:(id)arg2 onAbort:(CDUnknownBlockType)arg3 onDone:(CDUnknownBlockType)arg4;
- (id)archiveToTarPath:(id)arg1 sourcePath:(id)arg2 onAbort:(CDUnknownBlockType)arg3 onDone:(CDUnknownBlockType)arg4;
- (id)aboutBoxVersionString;
- (BOOL)performPerVMHotKeyWithVMUUID:(id)arg1;
- (BOOL)performPerVMHotKeyWithEvent:(id)arg1;
- (void)processCommandLine;
- (void)registerValueTransformers;
- (void)onVixUnmountVMCommand:(id)arg1;
- (void)onVixReloadCommand:(id)arg1;
- (void)teardownDUI;
- (void)teardownCUI;
- (void)initDUI;
- (void)initCUI;
- (void)applicationWillTerminate:(id)arg1;
- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)pushActionController:(id)arg1;
- (void)duiDidFinishInitialization;
- (void)collectSupportInformation;
- (id)allLocalVMNodes;
- (void)updateWindowsMenu:(id)arg1;
- (void)prepareForUpdate;
- (void)showLicenseExpiration:(id)arg1;
- (void)addInventory:(id)arg1;
- (void)preparePaschalOvum:(CDUnknownBlockType)arg1;
- (void)runVMsForURLs:(id)arg1;
- (void)showWindowsForURLs:(id)arg1;
- (void)showWindowsForVMWithID:(id)arg1 allWindows:(BOOL)arg2;
- (void)showWindowsForVMWithID:(id)arg1;
- (id)actionControllerForVMWithNode:(id)arg1;
- (id)actionControllerForVMWithID:(id)arg1;
- (id)defaultActionController;
- (id)inventoryNodesForVMWithUUID:(id)arg1;
- (id)updateControllerDelegate;
@property(readonly, retain, nonatomic) DUIUpdateController *updateController;
@property(readonly, retain, nonatomic) DUIActivityViewer *fileCopyActivityViewer; // @synthesize fileCopyActivityViewer=mFileCopyActivityViewer;
@property(readonly, retain, nonatomic) DUIActivityViewer *defaultActivityViewer; // @synthesize defaultActivityViewer=mDefaultActivityViewer;
@property(readonly, retain, nonatomic) DUIKeyboardAndMousePreferences *keyboardAndMousePreferences;
@property(readonly, nonatomic) DUIFeatures *features;
@property(readonly, retain, nonatomic) DUIDlgMgr *dlgMgr;
- (BOOL)validateMenuItem:(id)arg1;
- (void)showHelpForTag:(long long)arg1;
- (void)showHelpTopic:(id)arg1;
- (void)enableAllHints:(id)arg1;
- (void)sendUserEmail:(id)arg1 licenseName:(id)arg2 licenseVersion:(id)arg3 licenseEdition:(id)arg4;
- (void)sendUserData;
- (void)checkForUpdates:(id)arg1;
- (void)browseURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

