//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIKeyboardAndMouseMappingInfo;

@interface DUICachedMapping : NSObject
{
    DUIKeyboardAndMouseMappingInfo *mHostMappingInfo;
    DUIKeyboardAndMouseMappingInfo *mGuestMappingInfo;
}

@property(retain, nonatomic) DUIKeyboardAndMouseMappingInfo *guestMappingInfo; // @synthesize guestMappingInfo=mGuestMappingInfo;
@property(retain, nonatomic) DUIKeyboardAndMouseMappingInfo *hostMappingInfo; // @synthesize hostMappingInfo=mHostMappingInfo;
- (BOOL)isEditable;
@property(nonatomic) BOOL enabled;
- (int)mappingType;
- (void)dealloc;
- (id)initWithHostMappingInfo:(id)arg1 guestMappingInfo:(id)arg2;

@end

