//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUICnxFSDatastoreInfo : NSObject
{
    struct DatastoreInfo mDatastoreInfo;
}

+ (id)cnxFSDatastoreInfoWithCUICnxFSDatastoreInfo:(const struct DatastoreInfo *)arg1;
@property(readonly, nonatomic) struct DatastoreInfo cuiDatastoreInfo; // @synthesize cuiDatastoreInfo=mDatastoreInfo;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long freeBytes;
@property(readonly, nonatomic) NSString *path;
@property(readonly, nonatomic) NSString *ID;
@property(readonly, nonatomic) NSString *name;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCUICnxFSDatastoreInfo:(const struct DatastoreInfo *)arg1;

@end

