//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

#import "DUIApplicationTerminationDelegate.h"

@class DUICnx;

@interface DUICnxMgr : DUIAdaptorBase <DUIApplicationTerminationDelegate>
{
}

+ (id)cnxMgr;
- (void)prepareForApplicationTerminationWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL canApplicationTerminate;
- (void)disconnectAllWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)disconnectCnx:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)connectCnx:(id)arg1 withDlgMgr:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (id)cnxForHostID:(id)arg1 type:(int)arg2;
- (id)cnxForServerKey:(id)arg1 type:(int)arg2;
- (void)cnxTypeForServerKey:(id)arg1 dlgMgr:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (int)cnxTypeForURIScheme:(id)arg1;
@property(readonly, nonatomic) DUICnx *clientCnx;
@property(readonly, nonatomic) struct CnxMgr *adaptedCnxMgr;
- (id)initWithAdaptedCnxMgr:(struct CnxMgr *)arg1;

@end

