//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class NSString;

@interface DUICnxInfo : DUIAdaptorBase
{
}

+ (id)cnxInfoForAdaptedCnxInfo:(struct CnxInfo *)arg1;
@property(readonly, nonatomic) NSString *productVersion;
@property(readonly, nonatomic) NSString *productName;
@property(readonly, nonatomic) int osType;
@property(readonly, nonatomic) int apiType;
@property(readonly, nonatomic) int productID;
@property(readonly, nonatomic) struct CnxInfo *adaptedCnxInfo;
- (id)initWithAdaptedCnxInfo:(struct CnxInfo *)arg1;

@end

