//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

#import "DUICPClipboardSrc.h"

@class DUIPasteboardItemProvider, DUIVM, NSTimer;

@interface DUICopyPasteMgr : DUIAdaptorBase <DUICPClipboardSrc>
{
    CDStruct_64802fdf mClipboard;
    int mSeqNum;
    int mReqSeqNum;
    NSTimer *mPendingCopyTimer;
    NSTimer *mPasteboardTimer;
    DUIPasteboardItemProvider *mProvider;
}

+ (id)copyPasteMgrForAdaptedCopyPasteMgr:(struct HostCopyPasteMgr *)arg1;
@property(retain, nonatomic) DUIPasteboardItemProvider *provider; // @synthesize provider=mProvider;
@property(retain, nonatomic) NSTimer *pasteboardTimer; // @synthesize pasteboardTimer=mPasteboardTimer;
@property(retain, nonatomic) NSTimer *pendingCopyTimer; // @synthesize pendingCopyTimer=mPendingCopyTimer;
@property(nonatomic) int reqSeqNum; // @synthesize reqSeqNum=mReqSeqNum;
@property(nonatomic) int seqNum; // @synthesize seqNum=mSeqNum;
- (void)onGrabStateChanged;
- (void)startPasteboardPolling;
- (void)pollPasteboard:(id)arg1;
- (void)srcUIGetFilesAtDir:(struct string)arg1 onDone:(slot_b50ce1c7)arg2 onAbort:(slot_c916f39b)arg3 onProgress:(slot_47124170)arg4 onOverwriteQuestion:(slot_d5bddd47)arg5;
- (void)invalidateAdaptation;
- (void)onPendingCopyTimeout:(id)arg1;
- (void)startProgressCB:(slot_b50ce1c7 *)arg1 abort:(slot_c916f39b *)arg2 progress:(slot_47124170 *)arg3;
- (void)getRemoteClipboardCB:(const CDStruct_64802fdf *)arg1;
- (void)internalUpdateRemoteClipboard:(BOOL)arg1;
- (void)updateRemoteClipboard;
- (void)updateLocalClipboard;
- (CDStruct_64802fdf *)srcClipboard;
@property(readonly, nonatomic) DUIVM *vm;
- (struct HostCopyPasteMgr *)adaptedCopyPasteMgr;
- (void)cleanupPromisedData;
- (void)dealloc;
- (id)initWithAdaptedCopyPasteMgr:(struct HostCopyPasteMgr *)arg1;

@end

