//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class DUICnxCapabilities, DUICnxFS, DUICnxInfo, DUIServerKey, NSMutableDictionary;

@interface DUICnx : DUIAdaptorBase
{
    RefPtr_0f6139b8 mAdaptedCnx;
    NSMutableDictionary *mAssociatedWindows;
}

+ (id)cnxForAdaptedCnxRefPtr:(RefPtr_0f6139b8)arg1;
+ (id)cnxForAdaptedCnxPtr:(WeakPtr_682d8722)arg1;
+ (id)cnxForAdaptedCnx:(struct Cnx *)arg1;
@property(retain, nonatomic) NSMutableDictionary *associatedWindows; // @synthesize associatedWindows=mAssociatedWindows;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isVirtualCenter;
- (void)dealloc;
- (void)setUsername:(id)arg1 password:(id)arg2;
@property(readonly, nonatomic) DUIServerKey *serverKey;
@property(readonly, nonatomic) int type;
@property(readonly, nonatomic) BOOL connectionPending;
@property(readonly, nonatomic) DUICnxCapabilities *capabilities;
@property(readonly, nonatomic) DUICnxInfo *info;
@property(readonly, nonatomic) DUICnxFS *fileSystem;
@property(readonly, nonatomic) BOOL isConnected;
@property(readonly, nonatomic) BOOL isSecure;
@property(readonly, nonatomic) BOOL isRemote;
@property(readonly, nonatomic) BOOL isClientCnx;
- (void)invalidateAdaptation;
@property(readonly, nonatomic) RefPtr_0f6139b8 adaptedCnxRefPtr;
@property(readonly, nonatomic) WeakPtr_682d8722 adaptedCnxPtr;
- (id)initWithAdaptedCnx:(struct Cnx *)arg1;

@end

