//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIDockerHiddenWindowProxy : NSObject
{
    NSString *uuid;
    NSString *vmUUID;
    unsigned int windowID;
    unsigned int surfaceID;
    struct UnityMgr *unityMgr;
    BOOL hasKeyboardFocus;
}

@property BOOL hasKeyboardFocus; // @synthesize hasKeyboardFocus;
@property(retain, nonatomic) NSString *vmUUID; // @synthesize vmUUID;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid;
- (void)onDockerDidResignKey:(id)arg1;
- (void)onDockerDidBecomeKey:(id)arg1;
- (void)onDockerDisconnectWindow:(id)arg1;
- (void)onDockerConnectWindow:(id)arg1;
- (void)listenForDockerMessages:(BOOL)arg1;
- (void)disconnect;
- (void)dealloc;
- (void)close;
- (void)setGuestApp:(id)arg1;
- (BOOL)isConnected;
- (id)initWithUnityMgr:(struct UnityMgr *)arg1 vmUUID:(id)arg2;

@end

