//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIRemovableDevice.h"

@interface DUIDeviceFileBackend : DUIRemovableDevice
{
}

- (id)description;
- (id)fileBackendForDeviceHost:(id)arg1 transaction:(id)arg2;
- (id)fileBackendForDeviceHost:(id)arg1;
- (BOOL)usesFileBackendForDeviceHost:(id)arg1 transaction:(id)arg2;
- (BOOL)usesFileBackendForDeviceHost:(id)arg1;
- (void)configureFileBackendForDeviceHost:(id)arg1 path:(id)arg2 transaction:(id)arg3;
- (void)setUsesFileBackendForTransaction:(id)arg1;
- (BOOL)usesFileBackendForTransaction:(id)arg1;
- (BOOL)usesFileBackend;
- (struct FileBackend *)adaptedDeviceFileBackend;
- (id)initWithAdaptedDevice:(struct Device *)arg1;
- (void)setFileBackendPath:(id)arg1 forTransaction:(id)arg2;
- (id)fileBackendPathForTransaction:(id)arg1;
- (id)fileBackendPath;

@end

