//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIRemovableDevice.h"

#import "DUIDevicePhysicalBackend.h"

@interface DUIDeviceAudio : DUIRemovableDevice <DUIDevicePhysicalBackend>
{
}

- (BOOL)canSupportRemoteAudio;
- (BOOL)canUseEchoCancellation;
- (void)setUsesPhysicalBackendForTransaction:(id)arg1;
- (BOOL)usesPhysicalBackendForTransaction:(id)arg1;
- (BOOL)usesPhysicalBackend;
- (struct PhysicalBackend *)adaptedDevicePhysicalBackend;
- (struct Audio *)adaptedDeviceAudio;
- (id)initWithAdaptedDevice:(struct Device *)arg1;
- (void)setEnableEchoCancellation:(BOOL)arg1 forTransaction:(id)arg2;
- (BOOL)enableEchoCancellationForTransaction:(id)arg1;
- (BOOL)enableEchoCancellation;
- (void)setPhysicalBackendPath:(id)arg1 forTransaction:(id)arg2;
- (id)physicalBackendPathForTransaction:(id)arg1;
- (id)physicalBackendPath;

@end

