//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIDlgCustomHelper.h"

#import "NSOutlineViewDelegate.h"
#import "NSSplitViewDelegate.h"

@class DUIDlgRemoteBrowserViewController, DUIDlgRemoteOutlineViewController, DUIHost, DUIRemoteFileNode, NSArray, NSButton, NSIndexPath, NSLayoutConstraint, NSMutableArray, NSOutlineView, NSPopUpButton, NSSegmentedControl, NSSplitView, NSString, NSTextField, NSTreeController, NSView;

@interface DUIDlgRemoteFileBrowserHelper : DUIDlgCustomHelper <NSOutlineViewDelegate, NSSplitViewDelegate>
{
    NSView *saveAsView;
    NSView *saveAsCenteredView;
    NSView *buttonContainer;
    NSView *horizontalLine;
    NSButton *openButton;
    NSButton *cancelButton;
    NSTextField *saveAsLabel;
    NSTextField *whereLabel;
    NSPopUpButton *pathControl;
    NSPopUpButton *wherePopup;
    NSView *detailView;
    NSOutlineView *outlineView;
    NSSplitView *splitView;
    DUIDlgRemoteBrowserViewController *browserViewController;
    DUIDlgRemoteOutlineViewController *outlineViewController;
    NSSegmentedControl *navigationSegment;
    NSTreeController *baseTreeController;
    NSTreeController *detailTreeController;
    BOOL mCollapsedState;
    BOOL mCanChooseDirectories;
    DUIHost *mHost;
    DUIRemoteFileNode *mBaseNode;
    DUIRemoteFileNode *mRootNode;
    DUIRemoteFileNode *mSelectedNode;
    NSArray *mSupportedTypes;
    NSArray *mBaseNodesArray;
    NSMutableArray *mNavigationForwardItems;
    NSMutableArray *mNavigationBackItems;
    NSIndexPath *mSelectionIndexPath;
    NSLayoutConstraint *mWidthConstraint;
    NSArray *mNavigationConstraints;
    NSView *mNavigationContainer;
    NSLayoutConstraint *mTopSpaceConstraint;
    NSLayoutConstraint *mFlexibleWidthConstraint;
    NSArray *mWhereConstraints;
    NSView *mWhereContainer;
    NSString *_saveAsFilename;
    struct CGSize mExpandedContentSize;
}

@property(retain, nonatomic) NSString *saveAsFilename; // @synthesize saveAsFilename=_saveAsFilename;
@property(nonatomic) BOOL canChooseDirectories; // @synthesize canChooseDirectories=mCanChooseDirectories;
@property(nonatomic) BOOL collapsedState; // @synthesize collapsedState=mCollapsedState;
@property(retain, nonatomic) NSView *whereContainer; // @synthesize whereContainer=mWhereContainer;
@property(retain, nonatomic) NSArray *whereConstraints; // @synthesize whereConstraints=mWhereConstraints;
@property(retain, nonatomic) NSLayoutConstraint *flexibleWidthConstraint; // @synthesize flexibleWidthConstraint=mFlexibleWidthConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topSpaceConstraint; // @synthesize topSpaceConstraint=mTopSpaceConstraint;
@property(retain, nonatomic) NSView *navigationContainer; // @synthesize navigationContainer=mNavigationContainer;
@property(retain, nonatomic) NSArray *navigationConstraints; // @synthesize navigationConstraints=mNavigationConstraints;
@property(nonatomic) struct CGSize expandedContentSize; // @synthesize expandedContentSize=mExpandedContentSize;
@property(retain, nonatomic) NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=mWidthConstraint;
@property(retain, nonatomic) NSIndexPath *selectionIndexPath; // @synthesize selectionIndexPath=mSelectionIndexPath;
@property(retain, nonatomic) NSMutableArray *navigationBackItems; // @synthesize navigationBackItems=mNavigationBackItems;
@property(retain, nonatomic) NSMutableArray *navigationForwardItems; // @synthesize navigationForwardItems=mNavigationForwardItems;
@property(retain, nonatomic) NSArray *baseNodesArray; // @synthesize baseNodesArray=mBaseNodesArray;
@property(retain, nonatomic) NSArray *supportedTypes; // @synthesize supportedTypes=mSupportedTypes;
@property(retain, nonatomic) DUIRemoteFileNode *selectedNode; // @synthesize selectedNode=mSelectedNode;
@property(retain, nonatomic) DUIRemoteFileNode *rootNode; // @synthesize rootNode=mRootNode;
@property(retain, nonatomic) DUIRemoteFileNode *baseNode; // @synthesize baseNode=mBaseNode;
@property(retain, nonatomic) DUIHost *host; // @synthesize host=mHost;
- (void)splitView:(id)arg1 resizeSubviewsWithOldSize:(struct CGSize)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)minWidth;
- (double)absoluteMinWidth;
- (void)updateCollapsedState;
- (void)onDisclosureTriangle:(id)arg1;
- (struct CGRect)centeredWindowFrameForSize:(struct CGSize)arg1;
- (void)configureLayoutForSavePanel;
- (id)constraintsForMiddleView:(id)arg1;
- (void)configureLayoutForOpenPanel;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (void)onStyleClick:(id)arg1;
- (void)loadViewForStyleTag:(long long)arg1;
- (void)onNavigationClick:(id)arg1;
- (void)selectIndexPath:(id)arg1 navigation:(int)arg2;
- (void)addObject:(id)arg1 toNavigationArray:(id)arg2;
- (void)updateNavSegment;
- (void)updatePathControlIndexPath:(id)arg1 forUserSelection:(BOOL)arg2;
- (void)setPrompt:(id)arg1;
- (id)filename;
- (void)processHierarchy:(id)arg1 onNode:(id)arg2;
- (void)setPathControlIndexPath:(id)arg1;
- (void)setSaveAsLocationNode:(id)arg1;
- (id)menuItemForNode:(id)arg1;
- (void)onPathMenuItemSelected:(id)arg1;
- (void)setTreeSelectionNode:(id)arg1 withParent:(id)arg2;
- (void)selectNode:(id)arg1;
- (void)validateButton;
- (BOOL)canSelectNode:(id)arg1;
- (void)doCancel:(id)arg1;
- (void)doOpen:(id)arg1;
- (struct DlgRemoteFileBrowser *)adaptedDlgFileBrowser;
- (void)dealloc;
- (id)initWithNibNamed:(id)arg1 adaptedDlg:(struct DlgCustomDialog *)arg2 host:(id)arg3 title:(id)arg4 initialHierarchy:(id)arg5 filters:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

