//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIFileBasedDiskInfo, NSString, NSURL;

@interface DUIDeviceHardDiskProxy : NSObject
{
    BOOL mPreAllocated;
    BOOL mSplit;
    int mFileOperation;
    int mDiskType;
    int mFileBusType;
    long long mSize;
    NSURL *mAbsoluteURL;
    NSString *mDiskFile;
    DUIFileBasedDiskInfo *mDiskInfo;
    NSString *mOriginalDiskFile;
    NSString *mKey;
}

@property(retain, nonatomic) NSString *key; // @synthesize key=mKey;
@property(retain, nonatomic) NSString *originalDiskFile; // @synthesize originalDiskFile=mOriginalDiskFile;
@property(retain, nonatomic) DUIFileBasedDiskInfo *diskInfo; // @synthesize diskInfo=mDiskInfo;
@property(retain, nonatomic) NSString *diskFile; // @synthesize diskFile=mDiskFile;
@property(retain, nonatomic) NSURL *absoluteURL; // @synthesize absoluteURL=mAbsoluteURL;
@property(nonatomic) int fileBusType; // @synthesize fileBusType=mFileBusType;
@property(nonatomic) int diskType; // @synthesize diskType=mDiskType;
@property(nonatomic) int fileOperation; // @synthesize fileOperation=mFileOperation;
@property(nonatomic) BOOL split; // @synthesize split=mSplit;
@property(nonatomic) BOOL preAllocated; // @synthesize preAllocated=mPreAllocated;
@property(nonatomic) long long size; // @synthesize size=mSize;
- (void)dealloc;

@end

