//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface DUIDiskSizeSliderTransformer : NSValueTransformer
{
    double mMaxSizeGB;
    double mSlopeFactor;
}

+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
@property(nonatomic) double slopeFactor; // @synthesize slopeFactor=mSlopeFactor;
@property(nonatomic) double maxSizeGB; // @synthesize maxSizeGB=mMaxSizeGB;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;
- (id)initWithMaxSizeGB:(double)arg1;

@end

