//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIRemovableDevice.h"

@class DUIBRTalk, NSMutableDictionary;

@interface DUIDeviceNIC : DUIRemovableDevice
{
    DUIBRTalk *brTalk;
    BOOL hasBRTalkBridge;
    BOOL mHasBRTalkBridge;
    NSMutableDictionary *mIncomingBandwidthDict;
    NSMutableDictionary *mOutgoingBandwidthDict;
}

+ (id)maxLatencyValue;
+ (id)maxBandwidthValue;
+ (int)bootOrderType;
@property(retain, nonatomic) NSMutableDictionary *outgoingBandwidthDict; // @synthesize outgoingBandwidthDict=mOutgoingBandwidthDict;
@property(retain, nonatomic) NSMutableDictionary *incomingBandwidthDict; // @synthesize incomingBandwidthDict=mIncomingBandwidthDict;
@property(nonatomic) BOOL hasBRTalkBridge; // @synthesize hasBRTalkBridge=mHasBRTalkBridge;
@property(readonly) DUIBRTalk *brTalk; // @synthesize brTalk;
- (id)getNamedBandwidthLimits;
- (id)description;
- (BOOL)validateMACAddress:(id *)arg1 forCUITransaction:(struct ConfigTransaction *)arg2 error:(id *)arg3;
- (BOOL)validateMACAddress:(id *)arg1 forTransaction:(id)arg2 error:(id *)arg3;
- (BOOL)validateMACAddress:(id *)arg1 error:(id *)arg2;
- (id)generateMACAddress;
- (struct NIC *)adaptedDeviceNIC;
- (void)invalidateAdaptation;
- (void)dealloc;
- (id)initWithAdaptedDevice:(struct Device *)arg1;
- (void)setOutgoingLatency:(int)arg1 forTransaction:(id)arg2;
- (int)outgoingLatencyForTransaction:(id)arg1;
- (int)outgoingLatency;
- (void)setIncomingLatency:(int)arg1 forTransaction:(id)arg2;
- (int)incomingLatencyForTransaction:(id)arg1;
- (int)incomingLatency;
- (void)setOutgoingPacketLossPct:(double)arg1 forTransaction:(id)arg2;
- (double)outgoingPacketLossPctForTransaction:(id)arg1;
- (double)outgoingPacketLossPct;
- (void)setIncomingPacketLossPct:(double)arg1 forTransaction:(id)arg2;
- (double)incomingPacketLossPctForTransaction:(id)arg1;
- (double)incomingPacketLossPct;
- (void)setOutgoingBandwidthLimitKbps:(int)arg1 forTransaction:(id)arg2;
- (int)outgoingBandwidthLimitKbpsForTransaction:(id)arg1;
- (int)outgoingBandwidthLimitKbps;
- (void)setIncomingBandwidthLimitKbps:(int)arg1 forTransaction:(id)arg2;
- (int)incomingBandwidthLimitKbpsForTransaction:(id)arg1;
- (int)incomingBandwidthLimitKbps;
- (void)setPromptForPromisc:(BOOL)arg1 forTransaction:(id)arg2;
- (BOOL)promptForPromiscForTransaction:(id)arg1;
- (BOOL)promptForPromisc;
- (void)setPropagateLinkStateEnabled:(BOOL)arg1 forTransaction:(id)arg2;
- (BOOL)propagateLinkStateEnabledForTransaction:(id)arg1;
- (BOOL)propagateLinkStateEnabled;
- (void)setMACAddress:(id)arg1 forTransaction:(id)arg2;
- (id)macAddressForTransaction:(id)arg1;
- (id)macAddress;
- (void)setHostIF:(int)arg1 forTransaction:(id)arg2;
- (int)hostIFForTransaction:(id)arg1;
- (int)hostIF;
- (void)setDisplayName:(id)arg1 forTransaction:(id)arg2;
- (id)displayNameForTransaction:(id)arg1;
- (id)displayName;
- (void)setDvsPortgroupKey:(id)arg1 forTransaction:(id)arg2;
- (id)dvsPortgroupKeyForTransaction:(id)arg1;
- (id)dvsPortgroupKey;
- (void)setDvsUUID:(id)arg1 forTransaction:(id)arg2;
- (id)dvsUUIDForTransaction:(id)arg1;
- (id)dvsUUID;
- (void)setCustomVMNetKey:(id)arg1 forTransaction:(id)arg2;
- (id)customVMNetKeyForTransaction:(id)arg1;
- (id)customVMNetKey;
- (void)setBSDName:(id)arg1 forTransaction:(id)arg2;
- (id)bsdNameForTransaction:(id)arg1;
- (id)bsdName;

@end

