//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIDlgCustomHelper.h"

@class NSButton, NSImageView, NSProgressIndicator, NSTextField;

@interface DUIDlgProgressHelper : DUIDlgCustomHelper
{
    NSImageView *appIconView;
    NSButton *cancelButton;
    NSTextField *informativeText;
    NSProgressIndicator *progressIndicator;
    BOOL mHasSlowCancel;
    id <NSObject> mActivity;
}

@property(retain, nonatomic) id <NSObject> activity; // @synthesize activity=mActivity;
@property(nonatomic) BOOL hasSlowCancel; // @synthesize hasSlowCancel=mHasSlowCancel;
@property(readonly, retain, nonatomic) NSButton *cancelButton; // @synthesize cancelButton;
@property(readonly, retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
- (void)doCancel:(id)arg1;
- (void)setText:(id)arg1;
- (void)configureConstraints;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithNibNamed:(id)arg1 adaptedDlg:(struct DlgCustomDialog *)arg2 informativeText:(id)arg3 title:(id)arg4;

@end

