//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DUIConfigTransaction, NSString;

@protocol DUIDeviceClientBackend
- (void)setUsesClientBackendForTransaction:(DUIConfigTransaction *)arg1;
- (BOOL)usesClientBackendForTransaction:(DUIConfigTransaction *)arg1;
- (BOOL)usesClientBackend;
- (void)setFilePath:(NSString *)arg1 forTransaction:(DUIConfigTransaction *)arg2;
- (NSString *)filePathForTransaction:(DUIConfigTransaction *)arg1;
- (NSString *)filePath;
- (void)setDevicePath:(NSString *)arg1 forTransaction:(DUIConfigTransaction *)arg2;
- (NSString *)devicePathForTransaction:(DUIConfigTransaction *)arg1;
- (NSString *)devicePath;
- (void)setClientPathBacking:(int)arg1 forTransaction:(DUIConfigTransaction *)arg2;
- (int)clientPathBackingForTransaction:(DUIConfigTransaction *)arg1;
- (int)clientPathBacking;
@end

