//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class NSWindow;

@interface DUIDlgMgr : DUIAdaptorBase
{
    NSWindow *window;
}

+ (id)dlgMgrForAdaptedDlgMgr:(struct DlgMgr *)arg1;
+ (void)teardownSharedDlgMgr;
+ (id)sharedDlgMgr;
+ (id)dlgMgrWithWindow:(id)arg1;
+ (id)dlgMgr;
@property(retain, nonatomic) NSWindow *window; // @synthesize window;
- (id)description;
- (void)dealloc;
- (void)invalidateAdaptation;
- (id)init;
- (void)setHasSlowCancelForProgress:(id)arg1;
- (void)closeProgress:(id)arg1;
- (void)showProgress:(id)arg1;
- (void)showEULAWithName:(id)arg1 label:(id)arg2 eulas:(id)arg3 declineButton:(id)arg4 acceptButton:(id)arg5 declineHandler:(CDUnknownBlockType)arg6 acceptHandler:(CDUnknownBlockType)arg7;
- (id)showCloseVMDlgWithMessage:(id)arg1 allowBackground:(BOOL)arg2 allowSuspend:(BOOL)arg3 repliedHandler:(CDUnknownBlockType)arg4;
- (void)beginCertificateDialogWithTrust:(struct __SecTrust *)arg1 text:(id)arg2 informativeText:(id)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (id)beginPasswordDialog:(int)arg1 text:(id)arg2 warningText:(id)arg3 buttonText:(id)arg4 title:(id)arg5 showRememberPassword:(BOOL)arg6;
- (id)beginPasswordDialog:(int)arg1 text:(id)arg2 warningText:(id)arg3 buttonText:(id)arg4 title:(id)arg5 username:(id)arg6 showRememberPassword:(BOOL)arg7;
- (id)beginFileBrowserForHost:(id)arg1 title:(id)arg2 initialPath:(id)arg3 initialFilename:(id)arg4 fileTypes:(id)arg5 browserType:(int)arg6;
- (void)beginSavePanel:(id)arg1 fileTypes:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)beginOpenPanel:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)beginAlert:(id)arg1 repliedHandler:(CDUnknownBlockType)arg2;
- (void)deleteDlg:(id)arg1;
- (void)updateWindow:(id)arg1;
- (void)redisplayCurrentDialog;
- (void)suspendDialogDisplay;
@property(readonly, nonatomic) BOOL hasDialog;
@property(readonly, nonatomic) struct DlgMgr *adaptedDlgMgr;
@property(readonly, nonatomic) BOOL hasProgressDialogs;
- (id)initWithWindow:(id)arg1;

@end

