//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIDevicesLEDItem : NSObject
{
    NSString *name;
    NSString *key;
    NSString *statusBarImageName;
    BOOL isConnected;
}

@property BOOL isConnected; // @synthesize isConnected;
@property(retain) NSString *key; // @synthesize key;
@property(retain) NSString *statusBarImageName; // @synthesize statusBarImageName;
@property(retain) NSString *name; // @synthesize name;
- (void)dealloc;

@end

