//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIDlgRemoteFileBrowserHelper.h"

@interface DUIDlgRemoteOpenPanel : DUIDlgRemoteFileBrowserHelper
{
}

- (void)validateButton;
- (BOOL)canOpenNode:(id)arg1;
- (id)filename;
- (id)initWithNibNamed:(id)arg1 adaptedDlg:(struct DlgCustomDialog *)arg2 host:(id)arg3 title:(id)arg4 initialHierarchy:(id)arg5 initialFilename:(id)arg6 filters:(id)arg7;

@end

