//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class DUICnx, DUIDlgMgr, NSButton, NSPopUpButton, NSSecureTextField, NSString, NSTextField;

@interface DUIDlgServerConnection : NSWindowController
{
    NSPopUpButton *recentHostsButton;
    NSTextField *usernameField;
    NSSecureTextField *passwordField;
    NSTextField *infoField;
    NSButton *connectButton;
    BOOL mIsConnecting;
    BOOL mSaveToKeychain;
    BOOL mHostIsEditable;
    BOOL mUsernameIsEditable;
    BOOL mSkipKeychain;
    BOOL mHasObservers;
    BOOL _disableRememberPassword;
    DUICnx *mCnx;
    NSString *mHostID;
    NSString *mUsername;
    NSString *mPassword;
    NSString *mLastHostID;
    NSString *mLastUsername;
    NSString *mSavedUsername;
    DUIDlgMgr *mDlgMgr;
    NSString *mInfoString;
    CDUnknownBlockType mAbortHandler;
    CDUnknownBlockType mDoneHandler;
}

+ (void)showWithCnx:(id)arg1 description:(id)arg2 skipKeychain:(BOOL)arg3 error:(id)arg4 abortHandler:(CDUnknownBlockType)arg5 doneHandler:(CDUnknownBlockType)arg6;
+ (void)connectToCnx:(id)arg1 description:(id)arg2 dlgMgr:(id)arg3 abortHandler:(CDUnknownBlockType)arg4 doneHandler:(CDUnknownBlockType)arg5;
+ (id)serverConnectionDlgForCnx:(id)arg1;
+ (BOOL)serverConnectionDlgExistsForCnx:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) BOOL disableRememberPassword; // @synthesize disableRememberPassword=_disableRememberPassword;
@property(nonatomic) BOOL hasObservers; // @synthesize hasObservers=mHasObservers;
@property(readonly, retain, nonatomic) NSTextField *usernameField; // @synthesize usernameField;
@property(readonly, retain, nonatomic) NSSecureTextField *passwordField; // @synthesize passwordField;
@property(copy, nonatomic) CDUnknownBlockType doneHandler; // @synthesize doneHandler=mDoneHandler;
@property(copy, nonatomic) CDUnknownBlockType abortHandler; // @synthesize abortHandler=mAbortHandler;
@property(copy, nonatomic) NSString *infoString; // @synthesize infoString=mInfoString;
@property(nonatomic) BOOL skipKeychain; // @synthesize skipKeychain=mSkipKeychain;
@property(nonatomic) BOOL usernameIsEditable; // @synthesize usernameIsEditable=mUsernameIsEditable;
@property(nonatomic) BOOL hostIsEditable; // @synthesize hostIsEditable=mHostIsEditable;
@property(nonatomic) BOOL saveToKeychain; // @synthesize saveToKeychain=mSaveToKeychain;
@property(nonatomic) BOOL isConnecting; // @synthesize isConnecting=mIsConnecting;
@property(retain, nonatomic) DUIDlgMgr *dlgMgr; // @synthesize dlgMgr=mDlgMgr;
@property(copy, nonatomic) NSString *savedUsername; // @synthesize savedUsername=mSavedUsername;
@property(copy, nonatomic) NSString *lastUsername; // @synthesize lastUsername=mLastUsername;
@property(copy, nonatomic) NSString *lastHostID; // @synthesize lastHostID=mLastHostID;
@property(copy, nonatomic) NSString *password; // @synthesize password=mPassword;
@property(copy, nonatomic) NSString *username; // @synthesize username=mUsername;
@property(copy, nonatomic) NSString *hostID; // @synthesize hostID=mHostID;
@property(retain, nonatomic) DUICnx *cnx; // @synthesize cnx=mCnx;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)controlTextDidChange:(id)arg1;
- (void)clearCredentials;
@property(readonly, nonatomic) BOOL enableConnect;
@property(readonly, nonatomic) BOOL credentialsChangedForCnx;
- (id)hostIDStatic;
@property(readonly, nonatomic) BOOL passwordIsDummy;
- (void)cancel:(id)arg1;
- (int)cnxType:(id *)arg1 hostID:(id *)arg2;
- (void)connect:(id)arg1;
- (void)onConnectionDone;
- (void)addHostToRecents;
- (void)onClearRecents:(id)arg1;
- (void)onEnteredUsername:(id)arg1;
- (void)onEnteredHost:(id)arg1;
- (void)onHostSelected:(id)arg1;
- (void)populateFromRememberedHost:(id)arg1;
- (void)updateAccountFields:(BOOL)arg1;
- (void)updateAccountFieldsForHost:(id)arg1;
- (void)buildRecentItemsMenu;
- (void)close;
- (void)awakeFromNib;
- (void)dealloc;

@end

