//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIDevice.h"

#import "DUIDeviceList.h"

@class NSString;

@interface DUIDeviceController : DUIDevice <DUIDeviceList>
{
}

- (unsigned long long)maxDiskSizeGBForTransaction:(id)arg1;
- (void)removeDevice:(id)arg1 forTransaction:(id)arg2 destroyIfNew:(BOOL)arg3;
- (void)addDevice:(id)arg1 forTransaction:(id)arg2;
- (id)addNewControlledDevice:(struct ControlledDevice *)arg1 forTransaction:(id)arg2;
- (void)onGetDiskInfoDone:(id)arg1 vmdkPath:(id)arg2 transaction:(id)arg3 abortHandler:(CDUnknownBlockType)arg4 doneHandler:(CDUnknownBlockType)arg5;
- (void)addExistingHardDiskForPath:(id)arg1 transaction:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (id)addNewHardDiskForTransaction:(id)arg1 configOptions:(id)arg2;
- (id)addNewCDROMForTransaction:(id)arg1;
- (id)addNewDeviceForTransaction:(id)arg1;
- (BOOL)canAddHardDiskForTransaction:(id)arg1;
- (BOOL)canAddCDROMForTransaction:(id)arg1;
- (BOOL)canAddForTransaction:(id)arg1;
- (BOOL)canAddHardDisk;
- (BOOL)canAddCDROM;
- (BOOL)canAdd;
- (id)deviceAtIndex:(unsigned int)arg1 forTransaction:(id)arg2;
- (id)deviceAtIndex:(unsigned int)arg1;
- (id)deviceForKey:(id)arg1 forTransaction:(id)arg2;
- (id)deviceForKey:(id)arg1;
- (id)allDevicesForTransaction:(id)arg1;
- (id)allDevices;
- (int)scsiCtlrTypeForTransaction:(id)arg1;
- (int)busType;
- (struct Controller *)adaptedDeviceController;
- (id)initWithAdaptedDevice:(struct Device *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

