//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSTimer;

@interface DUIExposeDetector : NSObject
{
    BOOL isInExpose;
    NSTimer *exposeTimer;
    NSMutableDictionary *callbacks;
}

+ (id)sharedExposeDetector;
@property BOOL isInExpose; // @synthesize isInExpose;
@property(retain) NSMutableDictionary *callbacks; // @synthesize callbacks;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1 enterSelector:(SEL)arg2 exitSelector:(SEL)arg3;
- (void)onExposeTimer:(id)arg1;
- (void)updateExposeTimer;
- (void)setExposeTimer:(id)arg1;
- (void)dealloc;

@end

