//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface DUIFitGuestOperation : NSObject
{
    NSArray *topology;
    id delegate;
    SEL selector;
    BOOL requestAcknowledged;
    void *contextInfo;
}

@property void *contextInfo; // @synthesize contextInfo;
@property BOOL requestAcknowledged; // @synthesize requestAcknowledged;
@property SEL selector; // @synthesize selector;
@property(retain) id delegate; // @synthesize delegate;
@property(retain) NSArray *topology; // @synthesize topology;
- (void)dealloc;

@end

