//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIFeatureCompatMode : NSObject
{
    int mModeIndex;
    NSString *mModeString;
}

+ (id)featureCompatModeWithCUIFeatureCompatMode:(pair_8f99d3fa)arg1;
@property(nonatomic) int modeIndex; // @synthesize modeIndex=mModeIndex;
@property(copy, nonatomic) NSString *modeString; // @synthesize modeString=mModeString;
- (void)dealloc;
- (id)description;
- (id)initWithCUIFeatureCompatMode:(pair_8f99d3fa)arg1;

@end

