//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DUITrackable.h"

@class DUIGuestAppMgr, DUIVM;

@interface DUIGuestAppList : NSObject <DUITrackable>
{
    DUIGuestAppMgr *mGuestAppMgr;
    id <DUITrackableProxy> mTrackableProxyImpl;
    BOOL mUpdateForPublishingChangeInProgress;
    DUIVM *mVM;
}

@property(nonatomic) DUIVM *vm; // @synthesize vm=mVM;
@property(nonatomic) BOOL updateForPublishingChangeInProgress; // @synthesize updateForPublishingChangeInProgress=mUpdateForPublishingChangeInProgress;
@property(nonatomic) DUIGuestAppMgr *guestAppMgr; // @synthesize guestAppMgr=mGuestAppMgr;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onRefreshListDone:(int)arg1;
- (void)verifyGuestApp:(struct GuestApp *)arg1;
- (struct GuestAppMgr *)duiGuestAppMgr;
- (void)dealloc;
- (void)invalidateTrackableProxy;
- (id)trackableProxy;
- (id)findItemWithGuestAppURI:(id)arg1 inArray:(id)arg2;
- (id)initialFrequentlyUsedApps;
- (void)setFrequentlyUsedApps:(id)arg1;
- (id)frequentlyUsedApps;
- (void)addFrequentlyUsedApp:(id)arg1;
- (void)setPinnedApps:(id)arg1;
- (id)pinnedApps;
- (void)removePinnedApp:(id)arg1;
- (void)addPinnedApp:(id)arg1;
- (id)itemsForList:(int)arg1;
- (void)refreshPublishListWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)refreshList:(int)arg1;
- (void)invalidateGuestAppMgr;
- (id)initWithGuestAppMgr:(id)arg1;

@end

