//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@interface DUIHostMgr : DUIAdaptorBase
{
}

+ (id)hostMgrForAdaptedHostMgr:(struct HostMgr *)arg1;
+ (id)hostMgr;
- (id)getHostForConnection:(id)arg1 moid:(id)arg2;
- (void)openHostWithID:(id)arg1 connection:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (void)listHostNetworksForConnection:(id)arg1 hostMOID:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (void)listHostsForConnection:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) struct HostMgr *adaptedHostMgr;
- (id)initWithAdaptedHostMgr:(struct HostMgr *)arg1;

@end

