//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIHotKey : NSObject
{
    struct HotKey mCUIHotKey;
}

+ (id)hotKeyWithCUIHotKey:(const struct HotKey *)arg1;
+ (id)hotKey;
- (id).cxx_construct;
- (BOOL)isEqual:(id)arg1;
- (id)shortString;
@property(readonly, nonatomic) NSString *keyString;
@property(readonly, nonatomic) unsigned long long modifierFlags;
@property(nonatomic) unsigned int modifiers;
@property(nonatomic) unsigned int vkey;
- (id)initWithVKey:(unsigned int)arg1 modifierFlags:(unsigned int)arg2;
- (id)initWithVKey:(unsigned int)arg1 modifiers:(unsigned int)arg2;
- (id)initWithCUIHotKey:(const struct HotKey *)arg1;
@property(readonly, nonatomic) const struct HotKey *cuiHotKey;

@end

