//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIHostMgrNetworkID : NSObject
{
    struct NetworkID mNetworkID;
}

+ (id)networkIDWithCUINetworkID:(const struct NetworkID *)arg1;
@property(readonly, nonatomic) struct NetworkID cuiNetworkID; // @synthesize cuiNetworkID=mNetworkID;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *dvsPortgroupKey;
@property(readonly, nonatomic) NSString *dvsUUID;
@property(readonly, nonatomic) NSString *ID;
@property(readonly, nonatomic) NSString *name;
- (id)initWithCUINetworkID:(const struct NetworkID *)arg1;

@end

