//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIHostMgrHostID : NSObject
{
    struct HostID mHostID;
}

+ (id)hostIDWithCUIHostID:(const struct HostID *)arg1;
@property(readonly, nonatomic) struct HostID cuiHostID; // @synthesize cuiHostID=mHostID;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *ID;
@property(readonly, nonatomic) NSString *name;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCUIHostID:(const struct HostID *)arg1;

@end

