//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@interface DUIHardwareVersion : DUIAdaptorBase
{
}

+ (id)hardwareVersionWithHardwareVersion:(const struct HardwareVersion *)arg1;
@property(readonly, nonatomic) BOOL enableVTPM;
@property(readonly, nonatomic) BOOL enableSupportFeatureCompat;
@property(readonly, nonatomic) BOOL enableSupportSecureBoot;
@property(readonly, nonatomic) BOOL enableVBS;
@property(readonly, nonatomic) BOOL enableUEFI;
@property(readonly, nonatomic) BOOL enableNVMe;
@property(readonly, nonatomic) BOOL enableEHCI;
@property(readonly, nonatomic) BOOL enableXHCI;
- (struct HardwareVersion *)adaptedHardwareVersion;
- (void)invalidateAdaptation;
- (id)initWithCUIHardwareVersion:(const struct HardwareVersion *)arg1;

@end

