//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIInventoryNode.h"

@class DUIVM, DUIVMID, NSString;

@interface DUIInventoryVMNode : DUIInventoryNode
{
    BOOL mIsVMChanging;
}

@property(nonatomic) BOOL isVMChanging; // @synthesize isVMChanging=mIsVMChanging;
- (id)description;
//- (void)deleteWithInteractive:(BOOL)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) DUIVM *vm;
@property(readonly, nonatomic) NSString *vmUUID;
@property(readonly, nonatomic) DUIVMID *vmID;
@property(readonly, nonatomic) BOOL isClone;
@property(readonly, nonatomic) struct VMNode *adaptedVMNode;
- (id)initWithAdaptedVMNode:(struct VMNode *)arg1;
- (id)latestLogFilePath;
- (id)toolTip;
- (id)staticScreenshots;
- (id)suspendedScreenshot;
- (id)finderURLForVMNode;
- (BOOL)isBootCampNode;
- (BOOL)isBrokenVMNode;
- (BOOL)isEncryptedVMNode;
- (BOOL)isLockedVMNode;
- (BOOL)isLocalVMNode;

@end

