//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSDraggingSource.h"
#import "NSPasteboardItemDataProvider.h"

@class CALayer, DUIMKSChrome, NSArray, NSString;

@interface DUIImageParentView : NSView <NSDraggingSource, NSPasteboardItemDataProvider>
{
    unsigned long long frontMostLayerIndex;
    CALayer *resizeIndicatorLayer;
    BOOL mouseDownOnMKSViews;
    BOOL wasSelectedOnMouseDown;
    struct CGPoint mouseDownPoint;
    BOOL mIsOpen;
    DUIMKSChrome *mChrome;
    NSArray *mScreenshots;
    NSArray *mLiveScreenshots;
    NSArray *mScreenshotTopologies;
    NSArray *mScreenshotLayers;
    NSArray *mMKSScreens;
    NSArray *mMKSScreenlayers;
    CALayer *mBadgeLayer;
}

+ (id)observationKeyPaths;
@property(nonatomic) BOOL isOpen; // @synthesize isOpen=mIsOpen;
@property(retain, nonatomic) CALayer *badgeLayer; // @synthesize badgeLayer=mBadgeLayer;
@property(retain, nonatomic) NSArray *mksScreenLayers; // @synthesize mksScreenLayers=mMKSScreenlayers;
@property(retain, nonatomic) NSArray *mksScreens; // @synthesize mksScreens=mMKSScreens;
@property(retain, nonatomic) NSArray *screenshotLayers; // @synthesize screenshotLayers=mScreenshotLayers;
@property(retain, nonatomic) NSArray *screenshotTopologies; // @synthesize screenshotTopologies=mScreenshotTopologies;
@property(retain, nonatomic) NSArray *liveScreenshots; // @synthesize liveScreenshots=mLiveScreenshots;
@property(retain, nonatomic) NSArray *screenshots; // @synthesize screenshots=mScreenshots;
@property(retain, nonatomic) DUIMKSChrome *chrome; // @synthesize chrome=mChrome;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateLayerRendering;
- (id)typesOfPromisedFilesToDrop;
- (void)updateLiveScreenshots;
- (BOOL)ignoreModifierKeysWhileDragging;
- (id)destinationOfPasteboard:(id)arg1;
- (id)namesOfPromisedFilesAt:(id)arg1 fileCount:(long long)arg2;
- (void)pasteboard:(id)arg1 item:(id)arg2 provideDataForType:(id)arg3;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)imageForDragInRect:(struct CGRect)arg1;
- (id)screenshotsAsImages;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)updateBadgeLayer:(BOOL)arg1;
- (id)badgeFont;
- (struct CGRect)frontRect;
- (struct CGSize)preferredSize;
- (void)updateBackgroundColor;
- (void)updateLayerShadow:(id)arg1;
- (void)closeMKSScreens;
- (void)closeScreenshots;
- (void)cycleLayerZorder;
- (BOOL)hasRealScreenshots;
- (id)layoutForFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)viewDidChangeBackingProperties;
- (void)performLayout;
- (void)close;
- (void)open;
- (void)showScreens:(id)arg1;
- (void)showScreenshots:(id)arg1 withTopologies:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

