//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIInventoryNode.h"

@class DUIProgress;

@interface DUIInventoryPlaceholderNode : DUIInventoryNode
{
    DUIProgress *mProgress;
}

@property(retain, nonatomic) DUIProgress *progress; // @synthesize progress=mProgress;
- (void)invalidateAdaptation;
@property(readonly, nonatomic) struct PlaceholderNode *adaptedPlaceholderNode;
- (id)initWithAdaptedPlaceholderNode:(struct PlaceholderNode *)arg1;
- (id)staticScreenshot;
- (id)pathImage;

@end

