//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSMutableArray, NSString;

@interface DUIKeyboardAndMouseMappingInfo : NSObject <NSCopying>
{
    BOOL mIsHostMapping;
    unsigned short mCharacter;
    int mMouseButton;
    int mModifierMask;
    NSString *mApplicationCommandID;
    NSMutableArray *mScancodesArray;
}

+ (id)mappingInfoForHostMapping:(BOOL)arg1;
+ (id)mappingInfoWithString:(id)arg1 isHostMapping:(BOOL)arg2;
@property(nonatomic) BOOL isHostMapping; // @synthesize isHostMapping=mIsHostMapping;
@property(nonatomic) unsigned short character; // @synthesize character=mCharacter;
@property(nonatomic) int modifierMask; // @synthesize modifierMask=mModifierMask;
@property(nonatomic) int mouseButton; // @synthesize mouseButton=mMouseButton;
@property(retain, nonatomic) NSMutableArray *scancodesArray; // @synthesize scancodesArray=mScancodesArray;
@property(copy, nonatomic) NSString *applicationCommandID; // @synthesize applicationCommandID=mApplicationCommandID;
@property(retain, nonatomic) NSArray *scancodes;
- (void)applyScancode:(unsigned short)arg1;
- (id)localizedStringWithModifiers:(BOOL)arg1;
- (id)displayArrayWithModifiers:(BOOL)arg1;
- (id)displayArrayWithModifiers:(BOOL)arg1 images:(BOOL)arg2;
- (long long)keyCount;
- (BOOL)hasModifiersOnly;
- (BOOL)isEmpty;
- (void)clear;
- (BOOL)isEquivalent:(id)arg1;
- (BOOL)isModifierOnly;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)mappingString;
- (id)initWithMappingString:(id)arg1 isHostMapping:(BOOL)arg2;

@end

