//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface DUIKeyboardAndMouseLocalizedMappings : NSObject
{
    NSString *mLanguageKeyboardID;
    NSArray *mKeyMappings;
}

+ (id)displayNameForCurrentLanguageKeyboard;
+ (BOOL)currentKeyboardIsISO;
+ (id)currentLanguageKeyboardID;
+ (id)allMappingLanguageKeyboardIDs;
+ (id)mappingsForLanguageKeyboardID:(id)arg1;
@property(retain, nonatomic) NSArray *keyMappings; // @synthesize keyMappings=mKeyMappings;
@property(retain, nonatomic) NSString *languageKeyboardID; // @synthesize languageKeyboardID=mLanguageKeyboardID;
- (id)keyMappingInfoForModifierMask:(unsigned int)arg1 key:(unsigned int)arg2 isHostMapping:(BOOL)arg3;
- (id)parseFileContents:(id)arg1;
- (id)parseFile:(id)arg1;
- (BOOL)isValidLineValues:(id)arg1;
- (id)splitLine:(id)arg1;
- (BOOL)parseValue:(id)arg1 asKey:(unsigned int *)arg2;
- (BOOL)parseValue:(id)arg1 asModifierMask:(unsigned int *)arg2;
- (id)normalizeValue:(id)arg1;
- (id)convertToDUIMappings:(id)arg1;
- (void)dealloc;
- (id)initWithLanguageKeyboardID:(id)arg1;

@end

