//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIMKS, DUIUnityMgr, NSMutableDictionary, NSString;

@interface DUIKeyboardMouseConnection : NSObject
{
    BOOL mHasKeyPressAfterGrab;
    BOOL mHasMousePressAfterGrab;
    int mGuiKeyDelay;
    int mGuiKeyState;
    int mPendingKeyDelay;
    int mPendingKeyDelayUnity;
    unsigned int mApplicationCommandIDCount;
    unsigned int mKeyboardType;
    long long mGuiKeyStateLastEventTimeMS;
    NSString *mLastGuestAppURI;
    DUIMKS *mMks;
    DUIUnityMgr *mUnityMgr;
    NSMutableDictionary *mApplicationCommandIDMap;
    unsigned long long _currentModifierFlags;
}

+ (id)observationKeyPaths;
@property(nonatomic) unsigned long long currentModifierFlags; // @synthesize currentModifierFlags=_currentModifierFlags;
@property(nonatomic) unsigned int keyboardType; // @synthesize keyboardType=mKeyboardType;
@property(nonatomic) unsigned int applicationCommandIDCount; // @synthesize applicationCommandIDCount=mApplicationCommandIDCount;
@property(retain, nonatomic) NSMutableDictionary *applicationCommandIDMap; // @synthesize applicationCommandIDMap=mApplicationCommandIDMap;
@property(readonly, retain, nonatomic) DUIUnityMgr *unityMgr; // @synthesize unityMgr=mUnityMgr;
@property(nonatomic) int pendingKeyDelayUnity; // @synthesize pendingKeyDelayUnity=mPendingKeyDelayUnity;
@property(nonatomic) int pendingKeyDelay; // @synthesize pendingKeyDelay=mPendingKeyDelay;
@property(readonly, retain, nonatomic) DUIMKS *mks; // @synthesize mks=mMks;
@property(retain, nonatomic) NSString *lastGuestAppURI; // @synthesize lastGuestAppURI=mLastGuestAppURI;
@property(nonatomic) BOOL hasMousePressAfterGrab; // @synthesize hasMousePressAfterGrab=mHasMousePressAfterGrab;
@property(nonatomic) BOOL hasKeyPressAfterGrab; // @synthesize hasKeyPressAfterGrab=mHasKeyPressAfterGrab;
@property(nonatomic) long long guiKeyStateLastEventTimeMS; // @synthesize guiKeyStateLastEventTimeMS=mGuiKeyStateLastEventTimeMS;
@property(nonatomic) int guiKeyState; // @synthesize guiKeyState=mGuiKeyState;
@property(nonatomic) int guiKeyDelay; // @synthesize guiKeyDelay=mGuiKeyDelay;
- (BOOL)convertMouseShortcut:(id)arg1 toCUIKeyBinding:(struct KeyBinding *)arg2;
- (void)convertGuestMapping:(id)arg1 toCUIKeyBinding:(struct KeyBinding *)arg2;
- (void)convertHostMapping:(id)arg1 toCUIKeyBinding:(struct KeyBinding *)arg2;
- (BOOL)convertMapping:(id)arg1 toCUIKeyBinding:(struct KeyBinding *)arg2;
- (int)notifyUIValueForCommandID:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onGrabStateChanged;
- (void)onWindowLostFocus:(id)arg1;
- (BOOL)onEmitKey:(unsigned short)arg1 isKeyDown:(BOOL)arg2;
- (id)keyboardProfile;
- (void)sendModifierFlagsToGuest:(unsigned long long)arg1 escapeCapslock:(BOOL)arg2;
- (void)handleGUIKeyState:(int)arg1;
- (void)updateDelayGUIKeyForShortcutsEnabled:(BOOL)arg1;
- (void)sendKey:(unsigned int)arg1;
- (BOOL)canSendKey;
- (BOOL)handleEvent:(id)arg1 forGuestApp:(id)arg2;
- (BOOL)handleEvent:(id)arg1;
- (BOOL)isHotKeyEvent:(id)arg1;
- (BOOL)onModifierChangedEvent:(id)arg1 escapeCapslock:(BOOL)arg2;
- (BOOL)onKeyEvent:(id)arg1;
- (void)synchronizeGuestKeyboardLEDState;
- (void)dealloc;
- (id)initWithMKS:(id)arg1 unityMgr:(id)arg2;

@end

