//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString, NSURL;

@interface DUILocalCDROMDevice : NSObject
{
    NSString *mDeviceName;
    NSString *mDevicePath;
    NSString *mHostPath;
    NSURL *mVolumeURL;
    NSString *mCustomDeviceName;
    NSNumber *mCachedIsSuperDrive;
    NSNumber *mCachedIsInternal;
    NSString *mCachedInternalLocation;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) NSString *cachedInternalLocation; // @synthesize cachedInternalLocation=mCachedInternalLocation;
@property(retain, nonatomic) NSNumber *cachedIsInternal; // @synthesize cachedIsInternal=mCachedIsInternal;
@property(retain, nonatomic) NSNumber *cachedIsSuperDrive; // @synthesize cachedIsSuperDrive=mCachedIsSuperDrive;
@property(retain, nonatomic) NSString *customDeviceName; // @synthesize customDeviceName=mCustomDeviceName;
@property(retain, nonatomic) NSURL *volumeURL; // @synthesize volumeURL=mVolumeURL;
@property(retain, nonatomic) NSString *hostPath; // @synthesize hostPath=mHostPath;
@property(retain, nonatomic) NSString *devicePath; // @synthesize devicePath=mDevicePath;
@property(retain, nonatomic) NSString *deviceName; // @synthesize deviceName=mDeviceName;
- (id)description;
- (void)dealloc;
- (int)internalLocation;
- (BOOL)isInternal;
- (BOOL)isSuperDrive;
@property(readonly, retain, nonatomic) NSString *displayName;
@property(readonly, retain, nonatomic) NSString *displayDeviceName;
- (id)initWithCUIDeviceInfo:(const struct Device *)arg1;

@end

