//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class DUIUSBDeviceRule, NSString;

@interface DUILocalUSBDevice : DUIAdaptorBase
{
}

+ (id)usbDeviceForAdaptedUSBDevice:(struct USBDevice *)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (id)description;
@property(readonly, nonatomic) DUIUSBDeviceRule *rule;
- (void)setConnectionAction:(int)arg1 vmFilename:(id)arg2;
- (int)connectionActionForVMFilename:(id)arg1;
- (BOOL)isIOSDevice;
- (void)restoreState:(id)arg1;
- (id)currentState;
- (BOOL)isBuiltIn;
- (void)saveDevicePrefs:(id)arg1 usbPrefs:(id)arg2;
- (id)devicePrefs;
- (id)legacyPrefsKey;
@property(readonly, copy, nonatomic) NSString *familyName;
@property(readonly, nonatomic) struct USBDevice *adaptedLocalUSBDevice;
- (id)initWithAdaptedUSBDevice:(struct USBDevice *)arg1;
- (void)connectionAction;
- (void)setQuirks:(unsigned int)arg1;
- (unsigned int)quirks;
- (void)setId:(long long)arg1;
- (long long)id;
- (void)setFamily:(unsigned int)arg1;
- (unsigned int)family;
- (void)setConnected:(BOOL)arg1;
- (BOOL)connected;
- (void)setName:(id)arg1;
- (id)name;
- (void)setSerial:(id)arg1;
- (id)serial;
- (void)setKey:(id)arg1;
- (id)key;

@end

