//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DUIMKSChromeElement.h"

@class DUIImageParentView, DUIMKSChrome, NSString;

@interface DUIMKSChromeElementScreenshot : NSObject <DUIMKSChromeElement>
{
    DUIMKSChrome *chrome;
    DUIImageParentView *imageParentView;
    BOOL isOpen;
    int oldPowerState;
    BOOL suppressPerformLayout;
}

+ (id)observationKeyPaths;
@property(nonatomic) BOOL isOpen; // @synthesize isOpen;
@property(retain, nonatomic) DUIImageParentView *imageParentView; // @synthesize imageParentView;
@property(nonatomic) DUIMKSChrome *chrome; // @synthesize chrome;
- (void)invalidateChrome;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)layoutForScreenshots:(id)arg1 mksScreens:(id)arg2;
- (id)namesOfPromisedFilesDroppedAtDestination:(id)arg1;
- (id)typesOfPromisedFilesToDrop;
- (id)imageForAnimationInRect:(struct CGRect)arg1;
- (id)screenshotItems;
- (void)performLayout;
- (void)update;
- (id)buildSortedScreens;
- (void)dealloc;
- (BOOL)isInChildWindow;
- (int)identifier;
- (BOOL)needsChildWindow;
- (void)resize;
- (BOOL)shouldOpen;
- (void)close;
- (void)open;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

