//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAOpenGLLayer.h"

@class DUIMKS, DUIMKSScreen, DUIMKSScreenView;

@interface DUIMKSIOSurfaceLayer : CAOpenGLLayer
{
    struct __IOSurface *ioSurfaceRef;
    unsigned long long ioSurfaceWidth;
    unsigned long long ioSurfaceHeight;
    unsigned int surfaceTexture;
    unsigned long long textureWidth;
    unsigned long long textureHeight;
    struct _CGLContextObject *openGLContext;
    struct connection mGuestContentsChangedForIOSurfaceIDCnx;
    BOOL mIsOpen;
    BOOL mDidStartRendering;
    BOOL mSurfaceHasContent;
    DUIMKS *mMKS;
    DUIMKSScreen *mMKSScreen;
    DUIMKSScreenView *mMKSScreenView;
}

@property(retain, nonatomic) DUIMKSScreenView *mksScreenView; // @synthesize mksScreenView=mMKSScreenView;
@property(retain, nonatomic) DUIMKSScreen *mksScreen; // @synthesize mksScreen=mMKSScreen;
@property(retain, nonatomic) DUIMKS *mks; // @synthesize mks=mMKS;
@property(nonatomic) BOOL surfaceHasContent; // @synthesize surfaceHasContent=mSurfaceHasContent;
@property(nonatomic) BOOL didStartRendering; // @synthesize didStartRendering=mDidStartRendering;
@property(nonatomic) BOOL isOpen; // @synthesize isOpen=mIsOpen;
- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned int)ioSurfaceID;
- (void)drawInCGLContext:(struct _CGLContextObject *)arg1 pixelFormat:(struct _CGLPixelFormatObject *)arg2 forLayerTime:(double)arg3 displayTime:(const CDStruct_e50ab651 *)arg4;
- (struct _CGLPixelFormatObject *)copyCGLPixelFormatForDisplayMask:(unsigned int)arg1;
- (void)releaseCGLContext:(struct _CGLContextObject *)arg1;
- (struct _CGLContextObject *)copyCGLContextForPixelFormat:(struct _CGLPixelFormatObject *)arg1;
- (void)setIOSurfaceRef:(struct __IOSurface *)arg1;
- (void)updateTexture;
- (void)dealloc;
- (void)updateIOSurfaceWithSize:(struct CGSize)arg1 mksScreen:(id)arg2;
- (void)close;
- (void)open;
- (id)initWithMKS:(id)arg1;

@end

