//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

#import "DUIAdaptorSubclassable.h"

@class NSArray, NSString;

@interface DUIMKS : DUIAdaptorBase <DUIAdaptorSubclassable>
{
}

+ (id)mksForAdaptedMKS:(struct MKS *)arg1;
+ (Class)baseSubclassableClass;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void)setMouseInMKSWindow:(BOOL)arg1;
- (void)sendGrabRequestForWindow:(id)arg1 motionGrab:(BOOL)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (BOOL)isGrabbed;
@property(nonatomic) int grabState;
@property(readonly, nonatomic) BOOL present;
- (id)windowMgr;
- (id)screenMgr;
@property(readonly, nonatomic) int windowGroupID;
@property(readonly, nonatomic) struct MKS *adaptedMKS;
- (id)initWithAdaptedMKS:(struct MKS *)arg1;
@property(readonly, retain, nonatomic) NSArray *canGrabFailureReasons;
@property(readonly, nonatomic) BOOL canGrab;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

