//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class DUIMKSScreenID;

@interface DUIMKSScreen : DUIAdaptorBase
{
    BOOL _hasRoot;
    shared_ptr_6cb5aa5c *mAdaptedMKSScreen;
}

+ (id)screenForAdaptedScreen:(shared_ptr_6cb5aa5c)arg1;
@property(readonly, nonatomic) BOOL hasRoot; // @synthesize hasRoot=_hasRoot;
@property(readonly, nonatomic) shared_ptr_6cb5aa5c *mAdaptedMKSScreen; // @synthesize mAdaptedMKSScreen;
- (id)description;
@property(readonly, nonatomic) BOOL isVirtualBoundingScreen;
@property(readonly, nonatomic) BOOL isPrimary;
@property(readonly, nonatomic) BOOL isPresent;
@property(readonly, nonatomic) struct CGPoint root;
@property(readonly, nonatomic) struct CGSize size;
@property(readonly, nonatomic) DUIMKSScreenID *screenID;
@property(readonly, nonatomic) shared_ptr_6cb5aa5c adaptedMKSScreen;
- (void)invalidateAdaptation;
- (id)initWithAdaptedScreen:(shared_ptr_6cb5aa5c)arg1;

@end

