//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MKSOpenGLViewDelegate.h"

@class DUIMKSScreen, DUIMKSScreenMgr, DUIMKSScreenView, MKSOpenGLView, NSString, UIDrawnMKSController;

@interface DUIMKSOpenGLViewController : NSObject <MKSOpenGLViewDelegate>
{
    int mDisplayMode;
    DUIMKSScreen *mMKSScreen;
    DUIMKSScreenMgr *mScreenMgr;
    DUIMKSScreenView *mScreenView;
    MKSOpenGLView *mOpenGLView;
    long long mScreenDisableCount;
    UIDrawnMKSController *mUIDrawnMKS;
    struct CGRect mSourceRect;
}

@property(retain, nonatomic) UIDrawnMKSController *uiDrawnMKS; // @synthesize uiDrawnMKS=mUIDrawnMKS;
@property(nonatomic) long long screenDisableCount; // @synthesize screenDisableCount=mScreenDisableCount;
@property(readonly, retain, nonatomic) MKSOpenGLView *openGLView; // @synthesize openGLView=mOpenGLView;
@property(readonly, retain, nonatomic) DUIMKSScreenView *screenView; // @synthesize screenView=mScreenView;
@property(readonly, retain, nonatomic) DUIMKSScreenMgr *screenMgr; // @synthesize screenMgr=mScreenMgr;
@property(nonatomic) int displayMode; // @synthesize displayMode=mDisplayMode;
@property(nonatomic) struct CGRect sourceRect; // @synthesize sourceRect=mSourceRect;
@property(retain, nonatomic) DUIMKSScreen *mksScreen; // @synthesize mksScreen=mMKSScreen;
- (void)setupUIDrawnMKS;
- (void)enableScreenUpdates;
- (void)disableScreenUpdates;
- (void)updateTopLeftScreenOrigin:(struct CGPoint)arg1;
- (void)updateRenderedView;
- (void)updateWindowID:(unsigned int)arg1 surfaceID:(unsigned int)arg2 size:(struct CGSize)arg3 pixelScale:(unsigned int)arg4 topLeftScreenOrigin:(struct CGPoint)arg5;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithView:(id)arg1 screenMgr:(id)arg2 screenView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

