//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class NSString;

@interface DUIMsgNotification : DUIAdaptorBase
{
}

+ (id)notificationForAdaptedNotification:(struct Notification *)arg1;
- (id)description;
@property(readonly, nonatomic) NSString *detail;
@property(readonly, nonatomic) NSString *text;
@property(readonly, nonatomic) struct Notification *adaptedNotification;
- (id)initWithAdaptedNotification:(struct Notification *)arg1;

@end

