//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIVM, NSMapTable;

@interface DUIMKSOverlayMgr : NSObject
{
    DUIVM *mVM;
    NSMapTable *mOverlayInfoMap;
    NSMapTable *mOverlayImageIDMap;
}

+ (id)observationKeyPaths;
@property(retain, nonatomic) NSMapTable *overlayImageIDMap; // @synthesize overlayImageIDMap=mOverlayImageIDMap;
@property(retain, nonatomic) NSMapTable *overlayInfoMap; // @synthesize overlayInfoMap=mOverlayInfoMap;
@property(retain, nonatomic) DUIVM *vm; // @synthesize vm=mVM;
- (void)removeMKSOverlayType:(int)arg1 forScreenView:(id)arg2;
- (BOOL)setMKSOverlayType:(int)arg1 alpha:(double)arg2 destination:(struct CGRect)arg3 isAboveMouse:(BOOL)arg4 overlayImage:(id)arg5 forScreenView:(id)arg6;
- (void)internalRemoveMKSOverlayType:(int)arg1 forScreenView:(id)arg2;
- (void)internalSetMKSOverlayType:(int)arg1 alpha:(double)arg2 destination:(struct CGRect)arg3 isAboveMouse:(BOOL)arg4 overlayImageID:(unsigned int)arg5 forScreenView:(id)arg6;
- (void)unregisterWindowOverlayImageWithID:(unsigned int)arg1;
- (unsigned int)registerWindowOverlayImage:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unregisterUnreferencedImages;
- (void)dealloc;
- (id)initWithVM:(id)arg1;

@end

