//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@interface DUIMemoryConfigMgr : DUIAdaptorBase
{
}

+ (id)memoryConfigMgrWithConfig:(id)arg1 vm:(id)arg2 transaction:(id)arg3;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void)graphicsMemoryDefaultsGuestMinMB:(unsigned int *)arg1 guestDefaultMB:(unsigned int *)arg2 guestMaxMB:(unsigned int *)arg3;
- (void)memoryDefaultsHostMax:(int *)arg1 hwMax:(int *)arg2 guestMin:(int *)arg3 guestMax:(int *)arg4 guestDefault:(int *)arg5;
- (id)validGraphicsMemorySizesMB;
@property(readonly, nonatomic) struct MemoryConfigMgr *adaptedMemoryConfigMgr;
- (void)invalidateAdaptation;
- (id)initWithConfig:(id)arg1 vm:(id)arg2 transaction:(id)arg3;
- (void)setRamSizeMB:(unsigned int)arg1;
- (unsigned int)ramSizeMB;
- (void)setHasGuestBackedGraphicsMemory:(BOOL)arg1;
- (BOOL)hasGuestBackedGraphicsMemory;
- (void)setGraphicsMemorySize:(unsigned int)arg1;
- (unsigned int)graphicsMemorySize;

@end

