//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DUIMKSChromeElement.h"

@class DUIMKSChrome, DUIMKSOpenGLViewController, DUIMKSOverlay, DUIMKSScreen, DUIMKSView, NSMutableArray, NSString;

@interface DUIMKSChromeElementMKSView : NSObject <DUIMKSChromeElement>
{
    BOOL mIsOpen;
    BOOL mOverlaysUpdateNeeded;
    BOOL mSuppressPerformLayout;
    BOOL mIsOnRetinaScreen;
    BOOL mScreenTypeChanged;
    DUIMKSChrome *mChrome;
    DUIMKSView *mMKSView;
    DUIMKSScreen *mMKSScreen;
    DUIMKSOpenGLViewController *mViewController;
    unsigned long long mFrontMostMKSViewIndex;
    DUIMKSOverlay *mTitleOverlay;
    NSMutableArray *mOverlays;
    unsigned long long mUngrabMarginMask;
    double mUngrabInset;
    struct CGRect mUngrabRect;
}

+ (id)observationKeyPaths;
@property(nonatomic) BOOL screenTypeChanged; // @synthesize screenTypeChanged=mScreenTypeChanged;
@property(nonatomic) BOOL isOnRetinaScreen; // @synthesize isOnRetinaScreen=mIsOnRetinaScreen;
@property(nonatomic) BOOL suppressPerformLayout; // @synthesize suppressPerformLayout=mSuppressPerformLayout;
@property(nonatomic) struct CGRect ungrabRect; // @synthesize ungrabRect=mUngrabRect;
@property(nonatomic) double ungrabInset; // @synthesize ungrabInset=mUngrabInset;
@property(nonatomic) unsigned long long ungrabMarginMask; // @synthesize ungrabMarginMask=mUngrabMarginMask;
@property(nonatomic) BOOL overlaysUpdateNeeded; // @synthesize overlaysUpdateNeeded=mOverlaysUpdateNeeded;
@property(retain, nonatomic) NSMutableArray *overlays; // @synthesize overlays=mOverlays;
@property(retain, nonatomic) DUIMKSOverlay *titleOverlay; // @synthesize titleOverlay=mTitleOverlay;
@property(nonatomic) unsigned long long frontMostMKSViewIndex; // @synthesize frontMostMKSViewIndex=mFrontMostMKSViewIndex;
@property(nonatomic) BOOL isOpen; // @synthesize isOpen=mIsOpen;
@property(retain, nonatomic) DUIMKSOpenGLViewController *viewController; // @synthesize viewController=mViewController;
@property(retain, nonatomic) DUIMKSScreen *mksScreen; // @synthesize mksScreen=mMKSScreen;
@property(retain, nonatomic) DUIMKSView *mksView; // @synthesize mksView=mMKSView;
@property(nonatomic) DUIMKSChrome *chrome; // @synthesize chrome=mChrome;
- (void)applyOverlaysAndUngrabRegions:(BOOL)arg1;
- (id)ungrabRegionForNewDestinationRect:(struct CGRect)arg1;
- (BOOL)updateOverlaysForNewDestinationRect:(struct CGRect)arg1 visibleRect:(struct CGRect)arg2;
- (int)nextAvailableOverlayType;
- (void)setUngrabInset:(double)arg1 marginMask:(unsigned long long)arg2;
- (void)removeMKSOverlay:(id)arg1;
- (void)addMKSOverlay:(id)arg1;
- (void)invalidateChrome;
- (id)liveVMScreenshot;
@property(readonly, copy) NSString *description;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateTitleOverlay;
- (void)updateResizeState;
- (BOOL)shouldAllowResize;
- (void)unregisterOverlay:(id)arg1;
- (void)registerOverlays;
- (void)onWindowScreenChanged:(id)arg1;
- (void)onOverlayRemovedFromChrome:(id)arg1;
- (void)onOverlayAddedToChrome:(id)arg1;
- (id)screenToDisplay;
- (void)performLayout;
- (void)update;
- (void)dealloc;
- (int)identifier;
- (BOOL)isInChildWindow;
- (BOOL)needsChildWindow;
- (void)resize;
- (BOOL)shouldOpen;
- (void)close;
- (void)open;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

