//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class DUINetcfgNetwork, NSString;

@interface DUINetcfgDHCP : DUIAdaptorBase
{
}

+ (id)netcfgDHCPForAdaptedNetcfgDHCP:(struct DHCP *)arg1;
@property(readonly, nonatomic) struct DHCP *adaptedNetcfgDHCP;
- (id)initWithAdaptedNetcfgDHCP:(struct DHCP *)arg1;
@property(nonatomic) unsigned int maxLeaseTime;
@property(nonatomic) unsigned int defaultLeaseTime;
@property(nonatomic) NSString *endIP;
@property(nonatomic) NSString *beginIP;
@property(readonly, nonatomic) DUINetcfgNetwork *network;

@end

