//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@interface DUINotificationAreaMgr : DUIAdaptorBase
{
}

+ (id)notificationAreaMgrForAdaptedNotificationAreaMgr:(struct NotificationAreaMgr *)arg1;
- (int)CUIEventTypeForDUIEvent:(int)arg1;
- (void)sendItem:(id)arg1 event:(int)arg2 atPoint:(struct CGPoint)arg3;
- (BOOL)isItemVisible:(id)arg1;
- (id)tooltipForItemWithUID:(id)arg1;
- (id)iconForItemWithUID:(id)arg1;
- (void)addBlackList:(id)arg1;
@property(readonly, nonatomic) BOOL isUpdating;
- (void)stopUpdates;
- (void)startUpdates;
@property(readonly, nonatomic) struct NotificationAreaMgr *adaptedNotificationAreaMgr;
- (id)initWithAdaptedNotificationAreaMgr:(struct NotificationAreaMgr *)arg1;

@end

