//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@interface DUINetcfgMgr : DUIAdaptorBase
{
}

- (void)unload;
- (char *)saveToBuffer;
- (void)load;
- (void)invalidateAdaptation;
@property(readonly, nonatomic) struct Mgr *adaptedNetcfgMgr;
- (id)initWithEditable:(id)arg1;

@end

