//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class DUINetcfgBridge, DUINetcfgDHCP, DUINetcfgNAT, NSString;

@interface DUINetcfgNetwork : DUIAdaptorBase
{
    NSString *mVmnetDisplayName;
}

+ (id)netcfgNetworkForAdaptedNetcfgNetwork:(struct Network *)arg1;
+ (_Bool)isValidDisplayName:(id)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) struct Network *adaptedNetcfgNetwork;
- (id)initWithAdaptedNetcfgNetwork:(struct Network *)arg1;
@property(nonatomic) NSString *subnetMask;
@property(nonatomic) NSString *subnetAddress;
@property(nonatomic) BOOL hasVirtualAdapter;
@property(nonatomic) BOOL hasDHCP;
@property(readonly, nonatomic) DUINetcfgNAT *nat;
@property(readonly, nonatomic) DUINetcfgDHCP *dhcp;
@property(readonly, nonatomic) DUINetcfgBridge *bridge;
@property(readonly, nonatomic) int networkType;
- (void)setNetworkType:(int)arg1 abortHandler:(CDUnknownBlockType)arg2;
@property(copy, nonatomic) NSString *vmnetDisplayName; // @synthesize vmnetDisplayName=mVmnetDisplayName;
- (id)vmnetKey;
@property(readonly, nonatomic) unsigned int index;

@end

