//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface DUIOVFInjectProperty : NSObject
{
    BOOL mAcceptEULAs;
    NSString *mDeploymentOption;
    NSArray *mProperties;
}

@property(retain, nonatomic) NSArray *properties; // @synthesize properties=mProperties;
@property(copy, nonatomic) NSString *deploymentOption; // @synthesize deploymentOption=mDeploymentOption;
@property(nonatomic) BOOL acceptEULAs; // @synthesize acceptEULAs=mAcceptEULAs;
- (void)dealloc;
- (struct InjectProperty)injectProperty;

@end

