//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface DUIOVFCategory : NSObject
{
    BOOL mUiOptional;
    NSString *mCategory;
    NSArray *mProperties;
}

+ (id)ovfCategoryWithCUIOVFCategory:(struct OVFCategory)arg1;
@property(retain, nonatomic) NSArray *properties; // @synthesize properties=mProperties;
@property(copy, nonatomic) NSString *category; // @synthesize category=mCategory;
@property(nonatomic) BOOL uiOptional; // @synthesize uiOptional=mUiOptional;
- (void)dealloc;
- (id)initWithCUIOVFCategory:(struct OVFCategory)arg1;

@end

