//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIOVFProperty : NSObject
{
    BOOL mAllowEmpty;
    BOOL mValid;
    NSString *mClassId;
    NSString *mKey;
    NSString *mInstanceId;
    NSString *mCategory;
    NSString *mLabel;
    NSString *mType;
    NSString *mDescript;
    NSString *mVal;
}

+ (id)ovfPropertyWithCUIOVFProperty:(struct OVFProperty)arg1;
@property(nonatomic) BOOL valid; // @synthesize valid=mValid;
@property(nonatomic) BOOL allowEmpty; // @synthesize allowEmpty=mAllowEmpty;
@property(copy, nonatomic) NSString *val; // @synthesize val=mVal;
@property(copy, nonatomic) NSString *descript; // @synthesize descript=mDescript;
@property(copy, nonatomic) NSString *type; // @synthesize type=mType;
@property(copy, nonatomic) NSString *label; // @synthesize label=mLabel;
@property(copy, nonatomic) NSString *category; // @synthesize category=mCategory;
@property(copy, nonatomic) NSString *instanceId; // @synthesize instanceId=mInstanceId;
@property(copy, nonatomic) NSString *key; // @synthesize key=mKey;
@property(copy, nonatomic) NSString *classId; // @synthesize classId=mClassId;
- (void)dealloc;
- (struct OVFProperty)cuiOVFProperty;
- (id)initWithCUIOVFProperty:(struct OVFProperty)arg1;

@end

