//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIOVFVMInfo : NSObject
{
    BOOL mSelected;
    NSString *mIdentifier;
    NSString *mName;
    NSString *mLocalPath;
}

+ (id)ovfVMInfoWithCUIOVFVMInfo:(struct OVFVMInfo)arg1;
@property(copy, nonatomic) NSString *localPath; // @synthesize localPath=mLocalPath;
@property(copy, nonatomic) NSString *name; // @synthesize name=mName;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=mIdentifier;
@property(nonatomic) BOOL selected; // @synthesize selected=mSelected;
- (void)dealloc;
- (struct OVFVMInfo)cuiOVFVMInfo;
- (id)initWithCUIOVFVMInfo:(struct OVFVMInfo)arg1;

@end

