//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUIOVFProductInfo : NSObject
{
    BOOL mIsVCSA;
    NSString *mName;
    NSString *mProductUrl;
    NSString *mVersion;
    NSString *mFullVersion;
    NSString *mVendor;
    NSString *mVendorUrl;
}

+ (id)ovfProductInfoWithCUIOVFProductInfo:(struct OVFProductInfo)arg1;
@property(nonatomic) BOOL isVCSA; // @synthesize isVCSA=mIsVCSA;
@property(copy, nonatomic) NSString *vendorUrl; // @synthesize vendorUrl=mVendorUrl;
@property(copy, nonatomic) NSString *vendor; // @synthesize vendor=mVendor;
@property(copy, nonatomic) NSString *fullVersion; // @synthesize fullVersion=mFullVersion;
@property(copy, nonatomic) NSString *version; // @synthesize version=mVersion;
@property(copy, nonatomic) NSString *productUrl; // @synthesize productUrl=mProductUrl;
@property(copy, nonatomic) NSString *name; // @synthesize name=mName;
- (void)dealloc;
- (id)initWithCUIOVFProductInfo:(struct OVFProductInfo)arg1;

@end

