//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "DUIVMContainer.h"

@class DUIVM, NSString;

@interface DUIOpenedVM : NSObject //<DUIVMContainer>
{
    DUIVM *mVM;
}

+ (id)openedVMWithVM:(id)arg1;
@property(nonatomic) DUIVM *vm; // @synthesize vm=mVM;
- (void)closeVMWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithVM:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

