//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIGuestApp, DUIProxyAppMgr, NSDictionary, NSObject<DUIProxyAppPublisherDelegate>, NSString;

@interface DUIProxyAppPublisher : NSObject
{
    BOOL mHasUI;
    BOOL mIsExternalToVM;
    BOOL mShouldAppendSuffix;
    DUIProxyAppMgr *mProxyAppMgr;
    DUIGuestApp *mGuestApp;
    NSString *mGuestAppURI;
    NSDictionary *mOldInfoPlist;
    NSDictionary *mAdditionalInfoPlistItems;
    NSString *mPublishPath;
    NSObject<DUIProxyAppPublisherDelegate> *mDelegate;
    NSString *mHumanReadableCopyright;
}

@property(retain, nonatomic) NSString *humanReadableCopyright; // @synthesize humanReadableCopyright=mHumanReadableCopyright;
@property(nonatomic) BOOL shouldAppendSuffix; // @synthesize shouldAppendSuffix=mShouldAppendSuffix;
@property(nonatomic) NSObject<DUIProxyAppPublisherDelegate> *delegate; // @synthesize delegate=mDelegate;
@property(nonatomic) BOOL isExternalToVM; // @synthesize isExternalToVM=mIsExternalToVM;
@property(nonatomic) BOOL hasUI; // @synthesize hasUI=mHasUI;
@property(retain, nonatomic) NSString *publishPath; // @synthesize publishPath=mPublishPath;
@property(retain, nonatomic) NSDictionary *additionalInfoPlistItems; // @synthesize additionalInfoPlistItems=mAdditionalInfoPlistItems;
@property(retain, nonatomic) NSDictionary *oldInfoPlist; // @synthesize oldInfoPlist=mOldInfoPlist;
@property(retain, nonatomic) NSString *guestAppURI; // @synthesize guestAppURI=mGuestAppURI;
@property(retain, nonatomic) DUIGuestApp *guestApp; // @synthesize guestApp=mGuestApp;
@property(retain, nonatomic) DUIProxyAppMgr *proxyAppMgr; // @synthesize proxyAppMgr=mProxyAppMgr;
- (BOOL)searchForRenamedDockerInDirectory:(id)arg1;
- (BOOL)shouldPublishProxyAppExternally;
- (BOOL)launchAndActivate:(BOOL)arg1 launchedURL:(id *)arg2;
- (BOOL)updateLaunchServices;
- (id)documentIconPath;
- (id)documentIconName;
- (id)iconPath;
- (BOOL)publishIcons;
- (BOOL)shouldDeleteFileAtPath:(id)arg1 isDirectory:(BOOL)arg2;
- (BOOL)publishBinary;
- (BOOL)shouldPublishInfoPlist:(id)arg1;
- (BOOL)shouldPublishIcons;
- (BOOL)shouldPublishBinary;
- (id)urlTypes;
- (id)documentTypes;
- (id)urlHandlers;
- (id)fileHandlers;
- (id)infoPlistPath;
- (id)templateInfoPlist;
- (id)mergeInfoPlist:(id)arg1 withOldInfoPlist:(id)arg2;
- (id)defaultHumanReadableCopyright;
- (id)hostAppBundleIdentifier;
- (id)hostAppName;
- (id)infoPlist;
- (BOOL)updatePublishPath;
- (BOOL)performPublish;
- (BOOL)updatePublishingInfo;
- (void)dealloc;
- (BOOL)unPublish:(id)arg1;
- (BOOL)publishAndLaunch:(BOOL)arg1 shouldActivate:(BOOL)arg2 launchedURL:(id *)arg3;
- (BOOL)shouldHaveUI:(BOOL)arg1;
- (id)initWithMgr:(id)arg1 guestAppURI:(id)arg2;
- (id)initWithMgr:(id)arg1 guestApp:(id)arg2;

@end

