//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSPasteboardItemDataProvider.h"

@class NSObject<DUICPClipboardSrc>, NSString;

@interface DUIPasteboardItemProvider : NSObject <NSPasteboardItemDataProvider>
{
    BOOL mIsProvidingForDrag;
    BOOL mPromisedFilesDelivered;
    BOOL mProvidingData;
    NSString *mDestinationPath;
    NSObject<DUICPClipboardSrc> *mMgr;
    struct CPClipboardClass *mGuestClipboard;
}

@property(nonatomic) struct CPClipboardClass *guestClipboard; // @synthesize guestClipboard=mGuestClipboard;
@property(nonatomic) NSObject<DUICPClipboardSrc> *mgr; // @synthesize mgr=mMgr;
@property(copy, nonatomic) NSString *destinationPath; // @synthesize destinationPath=mDestinationPath;
@property(nonatomic) BOOL providingData; // @synthesize providingData=mProvidingData;
@property(nonatomic) BOOL promisedFilesDelivered; // @synthesize promisedFilesDelivered=mPromisedFilesDelivered;
@property(nonatomic) BOOL isProvidingForDrag; // @synthesize isProvidingForDrag=mIsProvidingForDrag;
- (id)pasteboardPasteLocation:(id)arg1;
- (id)pasteboardItemArray;
- (void)sourceFileCopyDoneCB:(BOOL)arg1;
- (void)pasteboardFinishedWithDataProvider:(id)arg1;
- (void)reset;
- (void)pasteboard:(id)arg1 item:(id)arg2 provideDataForType:(id)arg3;
- (void)dealloc;
- (id)initWithDUICPClipboardSrc:(id)arg1 isProvidingForDrag:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

