//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DUIKeyboardAndMousePrefsProxy.h"

@class DUIKeyboardAndMouseLocalizedMappings, NSString;

@interface DUIPrefsKeyboardAndMousePrefsProxy : NSObject <DUIKeyboardAndMousePrefsProxy>
{
    DUIKeyboardAndMouseLocalizedMappings *mLocalizedMappings;
}

@property(retain) DUIKeyboardAndMouseLocalizedMappings *localizedMappings; // @synthesize localizedMappings=mLocalizedMappings;
- (id)displayNameForCurrentLanguageKeyboard;
- (id)currentLanguageKeyboardID;
- (id)mappingsForLanguageKeyboardID:(id)arg1;
- (BOOL)updateCurrentLanguageKeyboardMappings:(BOOL)arg1;
- (id)keyMappings;
- (id)languageKeyboardID;
- (BOOL)mapISONumpadEnterToAltGrEnabled;
- (BOOL)mapControlAndGUIClickEnabled;
- (BOOL)partialGrabEnabled;
- (struct KeyboardAndMouseProfile *)keyboardAndMouseProfile;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

