//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class DUIProgress, DUIScreenProgressLabel, NSButton, NSImage, NSString;

@interface DUIProgressViewController : NSViewController
{
    id progressIndicator;
    NSButton *cancelButton;
    DUIScreenProgressLabel *screenProgressTextField;
    NSString *mLabel;
    NSString *mProgressDetailText;
    NSString *mCancelTooltip;
    NSImage *mIcon;
}

+ (id)viewControllerWithProgress:(id)arg1 forViewer:(id)arg2;
+ (id)viewControllerWithProgress:(id)arg1 nibName:(id)arg2;
+ (id)viewControllerWithProgress:(id)arg1;
+ (id)observationKeyPaths;
@property(retain, nonatomic) NSImage *icon; // @synthesize icon=mIcon;
@property(retain, nonatomic) NSString *cancelTooltip; // @synthesize cancelTooltip=mCancelTooltip;
@property(retain, nonatomic) NSString *progressDetailText; // @synthesize progressDetailText=mProgressDetailText;
@property(retain, nonatomic) NSString *label; // @synthesize label=mLabel;
- (void)onMouseExitedButton:(id)arg1;
- (void)onMouseEnteredButton:(id)arg1;
- (void)onCancellableChanged;
- (void)onTextChanged;
- (void)onPercentChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)awakeFromNib;
@property(retain, nonatomic) DUIProgress *progress;
- (void)dealloc;
- (id)initWithProgress:(id)arg1 nibName:(id)arg2;
- (void)onCancel:(id)arg1;

@end

