//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class NSArray;

@interface DUIProgressMgr : DUIAdaptorBase
{
}

+ (id)progressMgrForAdaptedProgressMgr:(struct ProgressMgr *)arg1;
- (void)didRemoveProgress:(id)arg1 fromBefore:(__list_iterator_d217f3df)arg2;
- (void)willRemoveProgress:(__list_iterator_d217f3df)arg1;
- (void)didAddProgress:(__list_iterator_d217f3df)arg1;
- (void)willAddProgress:(id)arg1 toBefore:(__list_iterator_d217f3df)arg2;
- (void)addProgress:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *activeProgresses;
@property(readonly, nonatomic) struct ProgressMgr *adaptedProgressMgr;
- (id)initWithAdaptedProgressMgr:(struct ProgressMgr *)arg1;

@end

