//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIInventory.h"

@interface DUIRegisteredInventory : DUIInventory
{
}

+ (id)registeredInventoryWithCnx:(id)arg1;
- (id)nodeForMOID:(id)arg1;
@property(readonly, nonatomic) struct RegisteredInventory *adaptedRegisteredInventory;
- (id)initWithCnx:(id)arg1;

@end

