//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class DUIProgress, NSImage, NSString;

@interface DUIRestrictedVM : DUIAdaptorBase
{
    DUIProgress *mProgress;
}

+ (id)restrictedVMForAdaptedRestrictedVM:(struct RestrictedVM *)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)keyPathsForValuesAffectingButtonImage;
+ (id)keyPathsForValuesAffectingIsCancelEnabled;
+ (id)keyPathsForValuesAffectingIsDownloading;
+ (id)keyPathsForValuesAffectingProgressTransfer;
+ (id)keyPathsForValuesAffectingProgressInfo;
+ (id)keyPathsForValuesAffectingIsButtonEnabled;
@property(retain, nonatomic) DUIProgress *progress; // @synthesize progress=mProgress;
- (BOOL)resumeFailed;
- (void)setVMDeleted;
- (void)downloadToVMDestination:(id)arg1 downloadPath:(id)arg2 withDlgMgr:(id)arg3 placeholderNode:(id)arg4 directoryExistsHandler:(CDUnknownBlockType)arg5 abortHandler:(CDUnknownBlockType)arg6 doneHandler:(CDUnknownBlockType)arg7;
- (void)connectChanged:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSString *downloadPath;
@property(readonly, copy, nonatomic) NSString *nodeID;
@property(readonly, copy, nonatomic) NSString *cfgPath;
@property(readonly, retain, nonatomic) NSImage *image;
@property(readonly, nonatomic) int state;
@property(readonly, copy, nonatomic) NSString *eula;
@property(readonly, copy, nonatomic) NSString *vmEntitlementName;
@property(readonly, copy, nonatomic) NSString *vmDescriptionTitle;
@property(readonly, copy, nonatomic) NSString *vmDescription;
@property(readonly, copy, nonatomic) NSString *vmName;
@property(readonly, nonatomic) struct RestrictedVM *adaptedRestrictedVM;
- (void)dealloc;
- (id)initWithAdaptedRestrictedVM:(struct RestrictedVM *)arg1;
- (void)setDisplayName:(id)arg1;
- (id)displayName;
- (void)updateFileProgressOnChangedSignal;
- (void)pauseDownload;
- (void)cancelDownload;
- (id)progressTransfer;
- (id)stringForTime:(long long)arg1;
- (id)progressInfo;
- (id)buttonImage;
- (BOOL)isButtonEnabled;
- (BOOL)isCancelEnabled;
- (BOOL)isDownloading;

@end

