//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIDevice.h"

@interface DUIRemovableDevice : DUIDevice
{
}

- (id)disconnectedString;
- (id)connectedString;
- (id)disconnectString;
- (id)connectString;
- (struct RemovableDevice *)adaptedRemovableDevice;
- (id)initWithAdaptedDevice:(struct Device *)arg1;
- (void)setStartConnected:(BOOL)arg1 forTransaction:(id)arg2;
- (BOOL)startConnectedForTransaction:(id)arg1;
- (BOOL)startConnected;
- (void)setCurrentlyConnected:(BOOL)arg1 forTransaction:(id)arg2;
- (BOOL)currentlyConnectedForTransaction:(id)arg1;
- (BOOL)currentlyConnected;

@end

