//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class DUISettingsIconViewController, NSButton;

@interface DUISettingsIconView : NSView
{
    DUISettingsIconViewController *mViewController;
    NSButton *mButton;
}

@property(nonatomic) NSButton *button; // @synthesize button=mButton;
@property(nonatomic) DUISettingsIconViewController *viewController; // @synthesize viewController=mViewController;
- (void)awakeFromNib;

@end

