//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemBase.h"

@class DUISupportedHardwareVersion, NSArray, NSButton, NSPopUpButton, NSString, NSTableView, NSTextField;

@interface DUISettingsItemHWVersion : DUISettingsItemBase
{
    NSPopUpButton *hwVersionButton;
    NSButton *upgradeButton;
    NSButton *revertButton;
    NSButton *applyButton;
    NSButton *upgradePromptCheckBox;
    NSTextField *upgradeText;
    NSTextField *advancedLabel;
    NSTextField *hwVersionLabel;
    NSTextField *productsLabel;
    NSTextField *limitsLabel;
    NSTableView *productsTableView;
    NSTableView *limitsTableView;
    BOOL mSavePending;
    BOOL mDisallowUpgrade;
    int mDefaultHWVersion;
    DUISupportedHardwareVersion *mHardwareVersionInfo;
}

+ (id)keyPathsAffectingSettingsValueForKey:(id)arg1;
@property(nonatomic) int defaultHWVersion; // @synthesize defaultHWVersion=mDefaultHWVersion;
@property(retain, nonatomic) DUISupportedHardwareVersion *hardwareVersionInfo; // @synthesize hardwareVersionInfo=mHardwareVersionInfo;
@property(nonatomic) BOOL disallowUpgrade; // @synthesize disallowUpgrade=mDisallowUpgrade;
@property(nonatomic) BOOL savePending; // @synthesize savePending=mSavePending;
- (void)willStartCloseViewAnimation;
- (void)shouldCloseViewWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (BOOL)canCloseView;
- (id)localDefaults;
- (id)warnings;
@property(readonly, copy, nonatomic) NSString *upgradeDescription;
@property(readonly, copy, nonatomic) NSArray *featureRestrictions;
@property(readonly, copy, nonatomic) NSArray *productCompatNames;
- (id)hardwareVersionInfo:(int)arg1;
- (void)changeHardwareVersion:(int)arg1 closeAbortHandler:(CDUnknownBlockType)arg2 closeDoneHandler:(CDUnknownBlockType)arg3;
- (void)toggleCheckbox:(id)arg1;
- (void)upgrade:(id)arg1;
- (void)revert:(id)arg1;
- (void)apply:(id)arg1;
- (void)changeHardwareVersionInfo:(id)arg1;
- (BOOL)canRevert;
- (BOOL)canApply;
- (BOOL)canUpgrade;
- (BOOL)canChangeHWVersion;
- (id)hwVersionManager;
- (void)updateHWVersionButton;
- (void)closeView;
- (void)openView;

@end

