//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemNetworkCommon.h"

@class NSArray, NSMenuItem, NSPopUpButton, NSString;

@interface DUISettingsItemNetworkVIM : DUISettingsItemNetworkCommon
{
    NSPopUpButton *customNetworkPopUp;
    NSString *mErrorString;
    NSMenuItem *mPlaceholderItem;
    NSArray *mNetworkIDs;
}

+ (id)observationKeyPaths;
+ (id)keyPathsAffectingSettingsValueForKey:(id)arg1;
@property(retain, nonatomic) NSArray *networkIDs; // @synthesize networkIDs=mNetworkIDs;
@property(retain, nonatomic) NSMenuItem *placeholderItem; // @synthesize placeholderItem=mPlaceholderItem;
@property(retain, nonatomic) NSString *errorString; // @synthesize errorString=mErrorString;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)warnings;
- (void)chooseNetworkID:(id)arg1;
- (BOOL)isDVSForTransaction:(id)arg1;
- (void)updateSelection;
- (void)closeView;
- (void)openView;
- (void)dealloc;

@end

