//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemBase.h"

@class DUISettingsIconContainerView, NSMutableDictionary, NSStackView, NSTextField, NSView;

@interface DUISettingsItemBrowser : DUISettingsItemBase
{
    NSStackView *stackView;
    NSStackView *systemSettingsStack;
    NSStackView *removableDeviceSetStack;
    NSStackView *removableDevicesStack;
    NSStackView *removableDevicesOverflowStack;
    NSView *removableDevicesOverflowMenuView;
    NSStackView *otherSettingsStack;
    DUISettingsIconContainerView *systemSettingsMatrixBox;
    DUISettingsIconContainerView *removableDevicesMatrixBox;
    DUISettingsIconContainerView *otherSettingsMatrixBox;
    NSTextField *devicesLabelField;
    NSMutableDictionary *mViewControllers;
}

@property(retain, nonatomic) NSMutableDictionary *viewControllers; // @synthesize viewControllers=mViewControllers;
- (void)onOverflowMenuAction:(id)arg1;
- (void)updateSettingsItems:(id)arg1;
- (id)itemsForKeys:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)updateStack:(id)arg1 overflow:(id)arg2 forItems:(id)arg3 fromCache:(id)arg4;
- (void)clearStacks;
- (void)shouldCloseViewWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)closeView;
- (void)openView;
- (void)dealloc;

@end

