//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DUISensitiveString : NSObject
{
    struct SensitiveString mSensitiveString;
}

+ (id)sensitiveStringWithCUISensitiveString:(const struct SensitiveString *)arg1;
+ (id)sensitiveStringWithString:(id)arg1;
+ (id)sensitiveString;
@property(readonly, nonatomic) const struct SensitiveString *cuiSensitiveString; // @synthesize cuiSensitiveString=mSensitiveString;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *stringValue;
@property(readonly, nonatomic) BOOL isEmpty;
- (id)initWithCUISensitiveString:(const struct SensitiveString *)arg1;

@end

