//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

#import "VMDraggableViewInteractiveChild.h"

@interface DUIScreenPlayButton : NSButton <VMDraggableViewInteractiveChild>
{
    BOOL isOutlineStyle;
}

@property BOOL isOutlineStyle; // @synthesize isOutlineStyle;
- (void)setNilValueForKey:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (unsigned long long)focusRingType;
- (BOOL)wantsFirstClick;
- (BOOL)acceptsNonDragMouseClick:(id)arg1;

@end

