//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUILocalCDROMDevice, DUISettingsCDROMOpenPanel, NSString;

@protocol DUISettingsCDROMOpenPanelDelegate <NSObject>
- (void)browseForFileDidEnd:(DUISettingsCDROMOpenPanel *)arg1 returnCode:(int)arg2 deviceKey:(NSString *)arg3;
- (void)setFileBased:(NSString *)arg1 deviceKey:(NSString *)arg2 remoteDiscPath:(NSString *)arg3;
- (void)setPhysicalDisc:(DUILocalCDROMDevice *)arg1 deviceKey:(NSString *)arg2;

@optional
- (void)setFileBased:(NSString *)arg1 deviceKey:(NSString *)arg2 installAppPath:(NSString *)arg3;
- (NSString *)cdromAccessoryPanelLastDirectoryKey;
- (NSString *)cdromAccessoryPanelRecentItemsKey;
- (BOOL)cdromAccessoryPanelShowRecentItems;
- (BOOL)cdromAccessoryPanelHideToolsFolder;
@end

