//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemMixedBackendDevice.h"

@interface DUISettingsItemParallel : DUISettingsItemMixedBackendDevice
{
}

+ (id)keyPathsAffectingSettingsValueForKey:(id)arg1;
- (id)removeDeviceMessageText;
- (id)warnings;
- (id)deviceImage;
- (id)hostDevices;

@end

