//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUISensitiveString, NSString;

@interface DUIServerKey : NSObject
{
    struct ServerKey mServerKey;
}

+ (id)serverKeyWithHostID:(id)arg1 username:(id)arg2 sslThumbprint:(id)arg3 webSocket:(id)arg4 password:(id)arg5;
+ (id)serverKeyWithHostID:(id)arg1 username:(id)arg2 password:(id)arg3;
+ (id)serverKeyForCUIServerKey:(const struct ServerKey *)arg1;
@property(readonly, nonatomic) struct ServerKey *serverKey; // @synthesize serverKey=mServerKey;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) DUISensitiveString *password;
- (id)sslThumbprint;
@property(readonly, copy, nonatomic) NSString *username;
@property(readonly, copy, nonatomic) NSString *hostID;
@property(readonly, nonatomic) const struct ServerKey *cuiServerKey;
- (id)initWithCUIServerKey:(const struct ServerKey *)arg1;

@end

