//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<DUIVMContainer>;

@interface DUISettingsMenuController : NSObject
{
    NSObject<DUIVMContainer> *mVmContainer;
}

+ (id)menuControllerForVMWithContainer:(id)arg1;
@property(retain, nonatomic) NSObject<DUIVMContainer> *vmContainer; // @synthesize vmContainer=mVmContainer;
- (id)menuItemWithTitle:(id)arg1 action:(SEL)arg2 object:(id)arg3;
- (id)menuItemForUSBDevices;
- (id)menuForUSBSettingsPlaceholderItem;
- (id)menuForUSB;
- (id)menuForSharing;
- (id)menuForVMUSBDevice:(id)arg1;
- (id)menuItemForUSBSettings;
- (id)menuItemForVMUSBDevice:(id)arg1;
- (id)menuForLocalUSBDevice:(id)arg1;
- (id)menuForDeviceVUsbCamera:(id)arg1;
- (id)menuForDeviceHardDisk:(id)arg1;
- (id)menuForDeviceNetworkVIM:(id)arg1;
- (id)menuForDeviceNIC:(id)arg1;
- (id)displayNameForVMNetKey:(id)arg1;
- (id)menuItemForDeviceNIC:(id)arg1 hostIF:(int)arg2;
- (id)menuForDeviceCDROM_VIM:(id)arg1;
- (id)menuForDeviceCDROM:(id)arg1;
- (id)menuForDeviceAudio:(id)arg1;
- (id)menuForDeviceSerial:(id)arg1;
- (id)menuForDeviceParallel:(id)arg1;
- (id)menuForDeviceFloppy:(id)arg1;
- (BOOL)addDeviceDescription:(id)arg1 toMenu:(id)arg2;
- (id)menuItemForShowDeviceSettings:(id)arg1;
- (id)menuItemForShowSettingsWithKey:(id)arg1 name:(id)arg2;
- (id)menuItemForToggleDeviceConnected:(id)arg1;
- (id)menuForItemWithKey:(id)arg1;
- (id)fullScreenMinibarMenuItems;
- (id)virtualMachineSettingsMenuItems;
- (id)settingsMenuItemsForKeys:(id)arg1;
- (id)keysForFullScreenItemsToDisplay;
- (id)keysForItemsToDisplay;
- (id)ledItemForVMUSBDevice:(id)arg1;
- (id)ledItemForLocalUSBDevice:(id)arg1;
- (id)ledItemImageNameFromFamilyName:(id)arg1;
- (id)ledItemForKey:(id)arg1;
- (id)sharingItemName;
- (id)usbItemName;
- (BOOL)isLocal;
- (id)vm;
- (void)dealloc;
- (id)initWithVMContainer:(id)arg1;

@end

