//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSOpenSavePanelDelegate.h"

@class NSObject<DUISettingsCDROMOpenPanelDelegate>, NSOpenPanel, NSPopUpButton, NSString;

@interface DUISettingsCDROMOpenPanel : NSViewController <NSOpenSavePanelDelegate>
{
    NSObject<DUISettingsCDROMOpenPanelDelegate> *delegate;
    NSOpenPanel *openPanel;
    NSPopUpButton *recentItemsPopup;
    BOOL _allowInstallApps;
}

+ (id)installAppDmgPath:(id)arg1;
+ (BOOL)isInstallApp:(id)arg1;
@property(nonatomic) BOOL allowInstallApps; // @synthesize allowInstallApps=_allowInstallApps;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (void)browseForFileDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)onSelectFile:(id)arg1 deviceKey:(id)arg2;
- (void)addURLToRecentItems:(id)arg1;
- (void)chooseRecentItem:(id)arg1;
- (void)clearRecentItems:(id)arg1;
- (void)beginSheetForDevice:(id)arg1 dlgMgr:(id)arg2 delegate:(id)arg3;
- (void)configureAccessoryForPanel:(id)arg1;
- (void)configureAccessoryPanelMenu;
- (id)menuItemForBookmark:(id)arg1;
- (BOOL)isLocalImagePath:(id)arg1;
- (id)defaultOpenPanelPath:(id)arg1;
- (id)lastDirectoryKey;
- (id)recentItemsKey;
- (id)allowedFileTypes;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

