//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemBaseRemovableDevice.h"

@class NSImage, NSMenuItem, NSPopUpButton, NSString;

@interface DUISettingsItemMixedBackendDevice : DUISettingsItemBaseRemovableDevice
{
    NSPopUpButton *fileBackendPopup;
    NSMenuItem *fileBackendItem;
}

+ (void)panelDidEnd:(id)arg1 returnCode:(long long)arg2 lastDirectoryKey:(id)arg3 selectionHandler:(CDUnknownBlockType)arg4;
+ (void)beginFileBrowserForHost:(id)arg1 dlgMgr:(id)arg2 initialPath:(id)arg3 initialFilename:(id)arg4 selectionHandler:(CDUnknownBlockType)arg5;
+ (void)beginLocalFileBrowserWithDlgMgr:(id)arg1 initialPath:(id)arg2 initialFilename:(id)arg3 selectionHandler:(CDUnknownBlockType)arg4;
+ (id)observationKeyPaths;
+ (id)keyPathsAffectingSettingsValueForKey:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onChooseFileDidEnd:(id)arg1 host:(id)arg2;
- (void)chooseFileForDeviceHost:(id)arg1;
- (void)setRemotePhysicalDevice:(id)arg1;
- (void)selectItemWithRepresentedObject:(id)arg1;
- (void)chooseHostDevice:(id)arg1;
- (void)onChooseFile:(id)arg1;
@property(readonly, retain) NSImage *fileIcon;
@property(readonly, retain) NSString *fileName;
- (void)updatePopupMenu;
- (BOOL)usesFileBackend;
- (void)closeView;
- (void)openView;
- (id)deviceImage;
- (id)hostDevices;
- (id)deviceMixedBackend;

@end

