//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface DUISharedFolder : NSObject
{
    struct SharedFolder mSharedFolder;
}

+ (id)sharedFolderWithCUISharedFolder:(struct SharedFolder)arg1;
@property(readonly, nonatomic) struct SharedFolder cuiSharedFolder; // @synthesize cuiSharedFolder=mSharedFolder;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)description;
@property(copy, nonatomic) NSArray *tags;
@property(nonatomic) BOOL writeAccess;
@property(nonatomic) BOOL enabled;
@property(copy, nonatomic) NSString *hostPath;
@property(copy, nonatomic) NSString *guestName;
@property(readonly, nonatomic) BOOL sessionExpire;
@property(readonly, nonatomic) BOOL readAccess;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithCUISharedFolder:(struct SharedFolder)arg1;

@end

