//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMOneShotWindowController.h"

@class DUIDlgMgr, NSProgressIndicator, NSTextField;

@interface DUISupportController : VMOneShotWindowController
{
    NSProgressIndicator *supportProgressIndicator;
    NSTextField *pleaseWaitDescription;
    struct __sFILE *supportScriptPipe;
    int supportScriptPID;
    BOOL supportScriptRunning;
    struct __sFILE *supportScriptCancelPipe;
    int supportScriptCancelPID;
    BOOL supportScriptCancelRunning;
    BOOL mRequiresAdmin;
    DUIDlgMgr *mDlgMgr;
}

+ (id)windowNibName;
+ (void)showRequestingAdminPermission:(BOOL)arg1;
@property(retain, nonatomic) DUIDlgMgr *dlgMgr; // @synthesize dlgMgr=mDlgMgr;
@property(nonatomic) BOOL requiresAdmin; // @synthesize requiresAdmin=mRequiresAdmin;
- (void)reapChild:(int)arg1;
- (void)showSupportErrorWithLogMessage:(id)arg1;
- (void)supportScriptFinished:(id)arg1;
- (void)supportScriptCancelFinished:(id)arg1;
- (BOOL)runUserSupportScript:(BOOL)arg1 doneSelector:(SEL)arg2 pipe:(struct __sFILE **)arg3 pid:(int *)arg4;
- (BOOL)runAdminSupportScript:(BOOL)arg1 doneSelector:(SEL)arg2 pipe:(struct __sFILE **)arg3 pid:(int *)arg4;
- (BOOL)runSupportScript:(BOOL)arg1 doneSelector:(SEL)arg2 pipe:(struct __sFILE **)arg3 pid:(int *)arg4;
- (void)cancelSupportScript:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

@end

