//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol DUITransacting <NSObject>
@property(readonly, nonatomic, getter=isDirty) BOOL dirty;
- (void)setDisableAutocommit:(BOOL)arg1;
- (BOOL)validate:(id *)arg1;
- (void)discard;
- (BOOL)commitWithAbortHandler:(void (^)(BOOL, NSError *))arg1 doneHandler:(void (^)(void))arg2;
- (BOOL)isNew;
@end

