//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUILocalUSBDevice, DUISettingsItemUSB, DUIVM, DUIVMUSBDeviceProxy, NSString;

@interface DUIUSBDeviceRuleTableRowObject : NSObject
{
    DUILocalUSBDevice *mDevice;
    DUIVMUSBDeviceProxy *mProxyDevice;
    DUIVM *mVM;
    DUISettingsItemUSB *mSettingsItem;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) DUISettingsItemUSB *settingsItem; // @synthesize settingsItem=mSettingsItem;
@property(nonatomic) DUIVM *vm; // @synthesize vm=mVM;
@property(retain, nonatomic) DUIVMUSBDeviceProxy *proxyDevice; // @synthesize proxyDevice=mProxyDevice;
@property(nonatomic) DUILocalUSBDevice *device; // @synthesize device=mDevice;
- (id)usbDeviceMgr;
@property(readonly, nonatomic) BOOL targetIsEnabled;
@property(readonly, nonatomic) BOOL targetOtherIsHidden;
@property(readonly, nonatomic) BOOL connectedIsEnabled;
@property(nonatomic) int target;
@property(readonly, nonatomic) NSString *name;
@property(nonatomic) BOOL connected;
- (id)connectToOtherVMLabel;
- (id)connectToMacLabel;
- (id)connectTargetAskItemTitle;
- (id)connectTargetGuestItemTitle;
- (void)dealloc;
- (id)initWithDevice:(id)arg1 proxyDevice:(id)arg2 settingsItem:(id)arg3;

@end

