//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIDlgMgr, DUIProgress, NSError, NSString, NSURL;

@protocol DUIUpdateControllerDelegate <NSObject>
@property(readonly, retain, nonatomic) DUIDlgMgr *dlgMgr;
@property(retain, nonatomic) DUIProgress *progress;
- (void)promptForInstallWithTitle:(NSString *)arg1 description:(NSString *)arg2 abortHandler:(void (^)(BOOL, NSError *))arg3 doneHandler:(void (^)(void))arg4;
- (void)noUpdateAvailableIsConnected:(BOOL)arg1 connectResult:(NSString *)arg2;
- (void)showUpdateID:(NSString *)arg1 version:(NSString *)arg2 buildnum:(unsigned int)arg3 htmlString:(NSString *)arg4 url:(NSURL *)arg5 title:(NSString *)arg6 infoString:(NSString *)arg7;
- (void)handleError:(NSError *)arg1 cancelled:(BOOL)arg2;
@end

