//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "DUIUpdateControllerDelegate.h"
#import "NSWindowDelegate.h"

@class DUIDlgMgr, DUIProgress, DUIUpdateController, NSButton, NSProgressIndicator, NSStackView, NSString, NSTextField, NSURL, NSView, WKWebView;

@interface DUIUpdateWindowController : NSWindowController <DUIUpdateControllerDelegate, NSWindowDelegate>
{
    NSTextField *updateTitle;
    NSStackView *stackView;
    NSView *updateInfoView;
    NSView *updateAvailableView;
    NSView *progressView;
    NSView *promptForInstallView;
    NSView *updateContentView;
    NSButton *updateDontShowAgainButton;
    NSButton *updateRemindLaterButton;
    NSButton *updateGoButton;
    NSProgressIndicator *progressIndicator;
    NSButton *installAndRestartButton;
    BOOL mShouldShowLackOfUpdate;
    int mUpdateBuildnum;
    int mUpdateState;
    NSString *mPromptString;
    NSString *mUpdateInfoString;
    DUIProgress *mProgress;
    id mProgressDoneObserver;
    NSString *mUpdateID;
    NSString *mUpdateVersion;
    NSURL *mUpdateURL;
    CDUnknownBlockType mOnInstallPromptDone;
    CDUnknownBlockType mOnInstallPromptAbort;
    DUIDlgMgr *mDlgMgr;
    WKWebView *mUpdateWebView;
    DUIUpdateController *mUpdateController;
}

+ (id)observationKeyPaths;
@property(nonatomic) DUIUpdateController *updateController; // @synthesize updateController=mUpdateController;
@property(retain, nonatomic) WKWebView *updateWebView; // @synthesize updateWebView=mUpdateWebView;
@property(retain, nonatomic) DUIDlgMgr *dlgMgr; // @synthesize dlgMgr=mDlgMgr;
@property(copy, nonatomic) CDUnknownBlockType onInstallPromptAbort; // @synthesize onInstallPromptAbort=mOnInstallPromptAbort;
@property(copy, nonatomic) CDUnknownBlockType onInstallPromptDone; // @synthesize onInstallPromptDone=mOnInstallPromptDone;
@property(nonatomic) BOOL shouldShowLackOfUpdate; // @synthesize shouldShowLackOfUpdate=mShouldShowLackOfUpdate;
@property(nonatomic) int updateState; // @synthesize updateState=mUpdateState;
@property(copy, nonatomic) NSURL *updateURL; // @synthesize updateURL=mUpdateURL;
@property(nonatomic) int updateBuildnum; // @synthesize updateBuildnum=mUpdateBuildnum;
@property(copy, nonatomic) NSString *updateVersion; // @synthesize updateVersion=mUpdateVersion;
@property(copy, nonatomic) NSString *updateID; // @synthesize updateID=mUpdateID;
@property(retain, nonatomic) id progressDoneObserver; // @synthesize progressDoneObserver=mProgressDoneObserver;
@property(retain, nonatomic) DUIProgress *progress; // @synthesize progress=mProgress;
@property(copy, nonatomic) NSString *updateInfoString; // @synthesize updateInfoString=mUpdateInfoString;
@property(copy, nonatomic) NSString *promptString; // @synthesize promptString=mPromptString;
- (void)changeWindowToState:(int)arg1;
- (void)onUpdateDone;
- (void)updateButtonTitles;
- (void)onPercentChanged;
- (void)updateProgressState;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onProgressDone:(id)arg1;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5;
- (id)webView:(id)arg1 contextMenuItemsForElement:(id)arg2 defaultMenuItems:(id)arg3;
- (void)handleError:(id)arg1 cancelled:(BOOL)arg2;
- (void)noUpdateAvailableIsConnected:(BOOL)arg1 connectResult:(id)arg2;
- (void)checkForUpdates:(BOOL)arg1;
- (void)showUpdateID:(id)arg1 version:(id)arg2 buildnum:(unsigned int)arg3 htmlString:(id)arg4 url:(id)arg5 title:(id)arg6 infoString:(id)arg7;
- (void)onInstallAndRestartGo:(id)arg1;
- (void)promptForInstallWithTitle:(id)arg1 description:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (void)onCancel:(id)arg1;
- (void)updateGo:(id)arg1;
- (void)updateRemindLater:(id)arg1;
- (void)updateDontShowAgain:(id)arg1;
- (void)showWindow:(id)arg1;
- (void)initUpdateWebView;
- (void)awakeFromNib;
- (void)dealloc;
- (id)init;
- (id)initWithController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

