//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUICDSController.h"

@class DUIProgressCustom, NSMutableArray, NSWindowController<DUIUpdateControllerDelegate>;

@interface DUIUpdateController : DUICDSController
{
    struct ComponentMgr *componentMgrForUpdates;
    struct DownloadMgr *downloadMgrForUpdates;
    struct ComponentMgr *componentMgr;
    struct DownloadMgr *downloadMgr;
    BOOL mIsInstallInProgress;
    BOOL mShouldShowConnectProgress;
    BOOL mUpdateInProgress;
    BOOL mAdditionalPowerDownsInProgress;
    BOOL mPowerDownHasFailed;
    NSWindowController<DUIUpdateControllerDelegate> *mUpdateDelegate;
    CDUnknownBlockType mOnQuiesceDone;
    CDUnknownBlockType mOnQuiesceAbort;
    DUIProgressCustom *mConnectProgress;
    NSMutableArray *mPowerDownsInProgress;
}

@property(retain, nonatomic) NSMutableArray *powerDownsInProgress; // @synthesize powerDownsInProgress=mPowerDownsInProgress;
@property(retain, nonatomic) DUIProgressCustom *connectProgress; // @synthesize connectProgress=mConnectProgress;
@property(copy, nonatomic) CDUnknownBlockType onQuiesceAbort; // @synthesize onQuiesceAbort=mOnQuiesceAbort;
@property(copy, nonatomic) CDUnknownBlockType onQuiesceDone; // @synthesize onQuiesceDone=mOnQuiesceDone;
@property(retain, nonatomic) NSWindowController<DUIUpdateControllerDelegate> *updateDelegate; // @synthesize updateDelegate=mUpdateDelegate;
@property(nonatomic) BOOL powerDownHasFailed; // @synthesize powerDownHasFailed=mPowerDownHasFailed;
@property(nonatomic) BOOL additionalPowerDownsInProgress; // @synthesize additionalPowerDownsInProgress=mAdditionalPowerDownsInProgress;
@property(nonatomic) BOOL updateInProgress; // @synthesize updateInProgress=mUpdateInProgress;
@property(nonatomic) BOOL shouldShowConnectProgress; // @synthesize shouldShowConnectProgress=mShouldShowConnectProgress;
@property(nonatomic) BOOL isInstallInProgress; // @synthesize isInstallInProgress=mIsInstallInProgress;
- (void)remindLaterForUpdateID:(id)arg1 withURL:(id)arg2;
- (void)ignoreUpdateID:(id)arg1 withURL:(id)arg2;
- (void)showUpdateID:(id)arg1 version:(id)arg2 buildnum:(unsigned int)arg3 htmlString:(id)arg4 url:(id)arg5;
- (void)onLookupProductDone:(shared_ptr_58551066)arg1 updateFlagsArray:(id)arg2 downloadMgr:(struct DownloadMgr *)arg3 showSkippedUpdates:(BOOL)arg4;
- (void)performUpdateChecks:(id)arg1 downloadMgr:(struct DownloadMgr *)arg2 showSkippedUpdates:(BOOL)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (int)adminPermission;
- (int)userPermissons;
- (struct DownloadMgr *)downloadMgrForUpdates:(id)arg1 build:(unsigned int)arg2;
- (struct ComponentMgrCDS *)componentMgrForVersion:(id)arg1 build:(unsigned int)arg2;
- (void)onNewUpdateProgress:(id)arg1;
- (void)onNewDownloadProgress:(id)arg1;
- (void)onConnectStatusChange;
- (void)destroyConnectProgress;
- (void)showConnectProgress;
- (void)promptForInstallWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)promptForDownloads:(const vector_db78adb7 *)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)windowWillClose:(id)arg1;
- (id)updateDelegateLoadIfNeeded;
- (id)dlgMgr;
- (void)dealloc;
- (id)init;
- (void)installUpdate:(id)arg1 build:(unsigned int)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (int)componentCoreProductType;
- (struct DownloadMgr *)downloadMgr;
- (struct ComponentMgr *)componentMgr;
- (BOOL)promptForOtherUsers:(CDUnknownBlockType)arg1;
- (void)checkForUpdates:(BOOL)arg1;
- (void)fetchProduct:(int)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)fetchToolsForGuest:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;

@end

