//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSUserNotificationCenterDelegate.h"

@class DUIActivityViewerMsg, NSString;

@interface DUIUserNotificationDelegate : NSObject <NSUserNotificationCenterDelegate>
{
    DUIActivityViewerMsg *activityViewer;
}

+ (id)defaultUserNotificationDelegate;
- (void)userNotificationCenter:(id)arg1 didActivateNotification:(id)arg2;
- (void)displayMessage:(id)arg1;
- (void)displayOrphanMessage:(id)arg1;
- (void)postMsgNotification:(id)arg1 vmUUID:(id)arg2 noteID:(unsigned long long)arg3;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)dealloc;
- (BOOL)userNotificationCenter:(id)arg1 shouldPresentNotification:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

