//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSOutlineViewDataSource.h"
#import "NSOutlineViewDelegate.h"
#import "NSWindowDelegate.h"

@class NSArray, NSOutlineView, NSString, NSTimer;

@interface DUIUnityStatusViewer : NSWindowController <NSWindowDelegate, NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    NSTimer *timer;
    NSArray *rootData;
    NSOutlineView *unityOutlineView;
}

+ (void)show;
@property(retain) NSOutlineView *unityOutlineView; // @synthesize unityOutlineView;
@property(retain) NSArray *rootData; // @synthesize rootData;
- (void)outlineViewItemWillCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (id)childrenOfItem:(id)arg1;
- (void)reloadData:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

