//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIVMAdaptor.h"

@class DUICopyPasteMgr, DUIDeviceMgr, DUIDnD, DUIMKSOverlayMgr, DUIProxyAppMgr, DUIUnityMgr, DUIVMAutosaveSnapshots, DUIVMConfig, DUIVMFitGuestMgr, DUIVMHardwareVersionManager, DUIVMKeyboardMouseConnection, DUIVMNotificationAreaController, DUIVMScreenshot, DUIVMSharedFolders, DUIVMUSBDevices, NSString;

@interface DUIVM : DUIVMAdaptor
{
    DUIVMAutosaveSnapshots *mAutosaveSnapshots;
    DUIVMConfig *mConfig;
    DUIDeviceMgr *mDeviceMgr;
    DUIDnD *mDnD;
    DUIVMFitGuestMgr *mFitGuestMgr;
    DUIVMHardwareVersionManager *mHardwareVersionManager;
    DUIVMKeyboardMouseConnection *mKeyboardMouseConnection;
    DUIMKSOverlayMgr *mMKSOverlayMgr;
    DUIVMNotificationAreaController *mNotificationAreaController;
    DUIVMScreenshot *mScreenshot;
    DUIVMSharedFolders *mSharedFolders;
    DUIVMUSBDevices *mUSBDevices;
    BOOL _isToolsDownloading;
    BOOL _waitForNextToolsActivation;
    BOOL _isAlertShowing;
    BOOL _isResuming;
    id <NSObject> mActivity;
    DUIProxyAppMgr *_proxyAppMgr;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (void)load;
@property(nonatomic) BOOL isResuming; // @synthesize isResuming=_isResuming;
@property(nonatomic) BOOL isAlertShowing; // @synthesize isAlertShowing=_isAlertShowing;
@property(nonatomic) BOOL waitForNextToolsActivation; // @synthesize waitForNextToolsActivation=_waitForNextToolsActivation;
@property(nonatomic) BOOL isToolsDownloading; // @synthesize isToolsDownloading=_isToolsDownloading;
@property(readonly, nonatomic) DUIProxyAppMgr *proxyAppMgr; // @synthesize proxyAppMgr=_proxyAppMgr;
@property(retain, nonatomic) id <NSObject> activity; // @synthesize activity=mActivity;
@property(retain, nonatomic) DUIVMScreenshot *screenshot; // @synthesize screenshot=mScreenshot;
@property(readonly, retain, nonatomic) DUIVMNotificationAreaController *notificationAreaController; // @synthesize notificationAreaController=mNotificationAreaController;
- (void)connectOnUUIDChanged:(CDUnknownBlockType)arg1;
- (void)onChangedValueForTools:(id)arg1;
- (BOOL)canConnectUSBDevice:(id)arg1;
- (void)updateActivityForPowerState:(int)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)description;
- (id)powerStateChangeNotificationUserInfoWithState:(int)arg1;
- (void)calculateDiskUsageForAllHardDisksWithDoneHandler:(CDUnknownBlockType)arg1;
- (void)onRawDiskAuthPromptDoneWithReturnCode:(long long)arg1 powerOption:(int)arg2;
- (void)onSetOutlookTempFolderAbort;
- (void)updateOutlookTempFolder:(id)arg1;
- (void)onToolsActivate;
- (void)onDefaultSoundDeviceChanged:(id)arg1;
- (void)powerOption;
- (void)powerAction;
- (void)dealloc;
@property(readonly, nonatomic) struct VM *adaptedVM;
- (void)performGuestShellAction:(id)arg1 targetURI:(id)arg2 withLocations:(id)arg3;
- (void)runGuestApplicationWithURI:(id)arg1;
- (void)openGuestSharedFolder:(id)arg1;
- (void)openGuestSharedFolderProxy:(id)arg1;
@property(readonly, nonatomic) BOOL canOpenGuestSharedFolder;
@property(readonly, nonatomic) DUIVMHardwareVersionManager *hardwareVersionManager; // @synthesize hardwareVersionManager=mHardwareVersionManager;
@property(readonly, retain, nonatomic) DUIVMKeyboardMouseConnection *keyboardMouseConnection; // @synthesize keyboardMouseConnection=mKeyboardMouseConnection;
@property(readonly, nonatomic) DUIUnityMgr *unityMgr;
- (void)mountVirtualPrinterInstaller:(id)arg1;
@property(readonly, copy, nonatomic) NSString *toolsCustomPath;
- (void)unmountCustomImage;
- (void)mountCustomImage:(id)arg1;
- (BOOL)canMountCustomImage:(id)arg1;
- (void)onFetchToolsForGuestDoneWithPrompt:(BOOL)arg1;
- (void)installVirtualPrinter;
- (void)toggleToolsInstallWithPrompt:(BOOL)arg1;
- (BOOL)checkCanMountCustomImage:(id)arg1;
- (BOOL)checkCanMountToolsImage;
@property(readonly, copy, nonatomic) NSString *toolsInstallMenuItemLabel;
- (void)bumpUngrabLockCount:(BOOL)arg1;
- (id)initWithAdaptedVM:(const struct DUIAdaptedVMWrapper *)arg1;
- (void)invalidateAdaptation;
@property(readonly, retain, nonatomic) DUIMKSOverlayMgr *mksOverlayMgr; // @synthesize mksOverlayMgr=mMKSOverlayMgr;
@property(readonly, retain, nonatomic) DUIVMFitGuestMgr *fitGuestMgr; // @synthesize fitGuestMgr=mFitGuestMgr;
@property(readonly, nonatomic) DUIVMSharedFolders *sharedFolders; // @synthesize sharedFolders=mSharedFolders;
@property(readonly, nonatomic) DUIVMAutosaveSnapshots *autosaveSnapshots; // @synthesize autosaveSnapshots=mAutosaveSnapshots;
- (void)powerOnWithOption:(int)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)powerOnWithChecksAndOption:(int)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)powerOnWithChecksAndOption:(int)arg1;
- (BOOL)performSnapshotsCompatibilityChecks;
- (void)checkRawDiskAuthorizationAndPowerOnWithOption:(int)arg1;
- (void)powerStateToFirmware:(int)arg1;
- (void)setPowerState:(int)arg1 withOption:(int)arg2 interactive:(BOOL)arg3 abortHandler:(CDUnknownBlockType)arg4 doneHandler:(CDUnknownBlockType)arg5;
- (BOOL)alertToolsRunningScriptWithPowerState:(int)arg1 withOption:(int)arg2;
- (BOOL)isSoftPowerOperationWithPowerState:(int)arg1 withOption:(int)arg2;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
@property(readonly, nonatomic) int hardwareVersion;
- (id)deviceMgr;
- (id)config;
@property(readonly, retain, nonatomic) DUIDnD *dnd; // @synthesize dnd=mDnD;
@property(readonly, retain, nonatomic) DUICopyPasteMgr *copyPaste;
@property(readonly, nonatomic) DUIVMUSBDevices *usbDevices; // @synthesize usbDevices=mUSBDevices;
- (id)powerShortLabel:(int)arg1;
- (id)powerTooltip:(int)arg1;
@property(readonly, nonatomic) BOOL supportsResetAlt;
@property(readonly, nonatomic) BOOL supportsPowerOffAlt;
@property(readonly, nonatomic) BOOL isPowerOffAltEnabled;
@property(readonly, nonatomic) BOOL isPowerOffEnabled;
- (BOOL)testPowerOffActionState:(int)arg1 isHard:(BOOL)arg2;
@property(readonly, nonatomic) BOOL supportsSuspendAlt;
@property(readonly, nonatomic) BOOL isPowerSuspendEnabled;
@property(readonly, nonatomic) BOOL supportsPowerOnAlt;
@property(readonly, nonatomic) BOOL isPowerOnEnabled;
- (BOOL)supportsPowerOption:(int)arg1;
- (int)altPowerOption:(int)arg1;
- (BOOL)isPowerChangeEnabled;
@property(readonly, nonatomic) BOOL canMirrorSharedFolders;
@property(readonly, nonatomic) BOOL isBootCamp;
@property(readonly, nonatomic) BOOL canCacheScreenshots;
- (void)toggleUSBDeviceWithKey:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (id)sharedController;
- (id)sharedTerminationHelper;

@end

