//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface DUIVMNetworkConnection : NSObject
{
    NSString *_macAddress;
    NSString *_connection;
    NSArray *_ipAddresses;
}

@property(copy, nonatomic) NSArray *ipAddresses; // @synthesize ipAddresses=_ipAddresses;
@property(copy, nonatomic) NSString *connection; // @synthesize connection=_connection;
@property(copy, nonatomic) NSString *macAddress; // @synthesize macAddress=_macAddress;
- (void)dealloc;

@end

