//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSToolbarItem.h"

@class DUIVMDevicesLEDManager, DUIVMWindowToolbarDelegate, NSObject<DUIVMContainer>, VMToolbarSegmentedControl;

@interface DUIVMDevicesToolbarItem : NSToolbarItem
{
    DUIVMWindowToolbarDelegate *mActionDelegate;
    VMToolbarSegmentedControl *mSegmentedControl;
    DUIVMDevicesLEDManager *mDevicesLEDManager;
}

+ (id)observationKeyPaths;
@property(retain, nonatomic) DUIVMDevicesLEDManager *devicesLEDManager; // @synthesize devicesLEDManager=mDevicesLEDManager;
@property(retain, nonatomic) VMToolbarSegmentedControl *segmentedControl; // @synthesize segmentedControl=mSegmentedControl;
@property(nonatomic) DUIVMWindowToolbarDelegate *actionDelegate; // @synthesize actionDelegate=mActionDelegate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onSegmentControlClicked:(id)arg1;
- (void)setIsExpandedPreference:(BOOL)arg1;
- (BOOL)isExpandedPreference;
- (void)validate;
@property(nonatomic) NSObject<DUIVMContainer> *vmContainer;
- (void)configureSegmentedControl:(id)arg1;
- (void)dealloc;
- (id)initWithItemIdentifier:(id)arg1;

@end

