//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIFitGuestOperation, DUIVM, NSMutableArray, NSTimer;

@interface DUIVMFitGuestMgr : NSObject
{
    BOOL mCanFitGuest;
    BOOL mIsFitGuestPending;
    BOOL mLastVMCanFitGuestCap;
    BOOL mLastVMCanSetDisplayTopologyCap;
    NSMutableArray *mFitGuestQueue;
    DUIFitGuestOperation *mPendingFitGuestOperation;
    DUIVM *mVM;
    NSTimer *mTimer;
}

+ (id)observationKeyPaths;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=mTimer;
@property(retain, nonatomic) DUIVM *vm; // @synthesize vm=mVM;
@property(retain, nonatomic) DUIFitGuestOperation *pendingFitGuestOperation; // @synthesize pendingFitGuestOperation=mPendingFitGuestOperation;
@property(retain, nonatomic) NSMutableArray *fitGuestQueue; // @synthesize fitGuestQueue=mFitGuestQueue;
@property(nonatomic) BOOL lastVMCanSetDisplayTopologyCap; // @synthesize lastVMCanSetDisplayTopologyCap=mLastVMCanSetDisplayTopologyCap;
@property(nonatomic) BOOL lastVMCanFitGuestCap; // @synthesize lastVMCanFitGuestCap=mLastVMCanFitGuestCap;
@property(nonatomic) BOOL isFitGuestPending; // @synthesize isFitGuestPending=mIsFitGuestPending;
@property(nonatomic) BOOL canFitGuest; // @synthesize canFitGuest=mCanFitGuest;
- (void)onRootedScreensChanged;
- (void)onFitGuestTimeout:(id)arg1;
- (void)invokeCallback:(id)arg1 didFitGuest:(BOOL)arg2 didTimeOut:(BOOL)arg3 error:(id)arg4;
- (void)onOperation:(id)arg1 didFitGuest:(BOOL)arg2 didTimeOut:(BOOL)arg3 error:(id)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)commitOperation:(id)arg1;
- (void)commitNextFitGuestOperation;
- (void)addToFitGuestQueue:(id)arg1;
- (void)fitGuest:(id)arg1 delegate:(id)arg2 callbackSelector:(SEL)arg3 contextInfo:(void *)arg4;
- (id)multiMonWarnings;
- (void)updateGuestDisplayScaling;
- (void)updateCanFitGuest:(BOOL)arg1;
- (BOOL)isTopologySupported:(id)arg1 withError:(id *)arg2;
- (void)dealloc;
- (id)initWithVM:(id)arg1;

@end

