//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIAdaptorBase.h"

@class NSArray;

@interface DUIVMConfigOptions : DUIAdaptorBase
{
}

+ (id)vmConfigOptionsForAdaptedVMConfigOptions:(struct VMConfigOptions *)arg1;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
@property(readonly, nonatomic) struct VMConfigOptions *adaptedVMConfigOptions;
- (id)initWithAdaptedVMConfigOptions:(struct VMConfigOptions *)arg1;
- (void)setCdromBackings:(int)arg1;
- (int)cdromBackings;
- (void)setEvaluating:(BOOL)arg1;
- (BOOL)evaluating;
- (void)setHardwareVersion:(id)arg1;
- (id)hardwareVersion;
@property(readonly, retain, nonatomic) NSArray *canUseVPMCFailureReasons;
@property(readonly, nonatomic) BOOL canUseVPMC;
@property(readonly, retain, nonatomic) NSArray *canUseDefaultDebuggingFailureReasons;
@property(readonly, nonatomic) BOOL canUseDefaultDebugging;
@property(readonly, retain, nonatomic) NSArray *canToolsUseAppDefaultFailureReasons;
@property(readonly, nonatomic) BOOL canToolsUseAppDefault;
@property(readonly, retain, nonatomic) NSArray *canToggleVirtualizedHVFailureReasons;
@property(readonly, nonatomic) BOOL canToggleVirtualizedHV;
@property(readonly, retain, nonatomic) NSArray *canTakeSnapshotAtPowerOffFailureReasons;
@property(readonly, nonatomic) BOOL canTakeSnapshotAtPowerOff;
@property(readonly, retain, nonatomic) NSArray *canSupportWSCloneTemplatesFailureReasons;
@property(readonly, nonatomic) BOOL canSupportWSCloneTemplates;
@property(readonly, retain, nonatomic) NSArray *canSupportVMXProcessPrioritiesFailureReasons;
@property(readonly, nonatomic) BOOL canSupportVMXProcessPriorities;
@property(readonly, retain, nonatomic) NSArray *canSupportSecureBootFailureReasons;
@property(readonly, nonatomic) BOOL canSupportSecureBoot;
@property(readonly, retain, nonatomic) NSArray *canSupportMemPageTrimFailureReasons;
@property(readonly, nonatomic) BOOL canSupportMemPageTrim;
@property(readonly, retain, nonatomic) NSArray *canSupportKeyboardFilterFailureReasons;
@property(readonly, nonatomic) BOOL canSupportKeyboardFilter;
@property(readonly, retain, nonatomic) NSArray *canSupportExitAtPowerOffFailureReasons;
@property(readonly, nonatomic) BOOL canSupportExitAtPowerOff;
@property(readonly, retain, nonatomic) NSArray *canSupportDragAndDropFailureReasons;
@property(readonly, nonatomic) BOOL canSupportDragAndDrop;
@property(readonly, retain, nonatomic) NSArray *canSupportCopyAndPasteFailureReasons;
@property(readonly, nonatomic) BOOL canSupportCopyAndPaste;
@property(readonly, retain, nonatomic) NSArray *canSetWorkingDirFailureReasons;
@property(readonly, nonatomic) BOOL canSetWorkingDir;
@property(readonly, retain, nonatomic) NSArray *canReportBatteryToGuestFailureReasons;
@property(readonly, nonatomic) BOOL canReportBatteryToGuest;
@property(readonly, retain, nonatomic) NSArray *canSupportFullScreenAtPowerOnFailureReasons;
@property(readonly, nonatomic) BOOL canSupportFullScreenAtPowerOn;
@property(readonly, retain, nonatomic) NSArray *canEditPowerOnOptionFailureReasons;
@property(readonly, nonatomic) BOOL canEditPowerOnOption;
@property(readonly, retain, nonatomic) NSArray *canHotRemoveUSBControllerFailureReasons;
@property(readonly, nonatomic) BOOL canHotRemoveUSBController;
@property(readonly, retain, nonatomic) NSArray *canHotRemoveNICFailureReasons;
@property(readonly, nonatomic) BOOL canHotRemoveNIC;
@property(readonly, retain, nonatomic) NSArray *canHotRemoveCDROMFailureReasons;
@property(readonly, nonatomic) BOOL canHotRemoveCDROM;
@property(readonly, retain, nonatomic) NSArray *canHotRemoveAudioFailureReasons;
@property(readonly, nonatomic) BOOL canHotRemoveAudio;
@property(readonly, retain, nonatomic) NSArray *canUseVirtualPrinterFailureReasons;
@property(readonly, nonatomic) BOOL canUseVirtualPrinter;
@property(readonly, retain, nonatomic) NSArray *canUseMultipleCoresFailureReasons;
@property(readonly, nonatomic) BOOL canUseMultipleCores;
@property(readonly, retain, nonatomic) NSArray *canUseClientBackendsFailureReasons;
@property(readonly, nonatomic) BOOL canUseClientBackends;
@property(readonly, retain, nonatomic) NSArray *canUSBSupportVirtualBluetoothFailureReasons;
@property(readonly, nonatomic) BOOL canUSBSupportVirtualBluetooth;
@property(readonly, retain, nonatomic) NSArray *canUSBSupportHIDFailureReasons;
@property(readonly, nonatomic) BOOL canUSBSupportHID;
@property(readonly, retain, nonatomic) NSArray *canUSBSupportXHCIFailureReasons;
@property(readonly, nonatomic) BOOL canUSBSupportXHCI;
@property(readonly, retain, nonatomic) NSArray *canUSBSupportEHCIFailureReasons;
@property(readonly, nonatomic) BOOL canUSBSupportEHCI;
@property(readonly, retain, nonatomic) NSArray *canUSBChangeUHCIFailureReasons;
@property(readonly, nonatomic) BOOL canUSBChangeUHCI;
@property(readonly, retain, nonatomic) NSArray *canUSBAutoConnectDevicesFailureReasons;
@property(readonly, nonatomic) BOOL canUSBAutoConnectDevices;
@property(readonly, retain, nonatomic) NSArray *canSVGASupportMaxMonitorResolutionsFailureReasons;
@property(readonly, nonatomic) BOOL canSVGASupportMaxMonitorResolutions;
@property(readonly, retain, nonatomic) NSArray *canSetProgressLoggingFailureReasons;
@property(readonly, nonatomic) BOOL canSetProgressLogging;
@property(readonly, retain, nonatomic) NSArray *canSetFloppyReadOnlyFailureReasons;
@property(readonly, nonatomic) BOOL canSetFloppyReadOnly;
@property(readonly, retain, nonatomic) NSArray *canReferToRemoteDevicesFailureReasons;
@property(readonly, nonatomic) BOOL canReferToRemoteDevices;
@property(readonly, retain, nonatomic) NSArray *canNICSupportLatencyFailureReasons;
@property(readonly, nonatomic) BOOL canNICSupportLatency;
@property(readonly, retain, nonatomic) NSArray *canNICSupportPacketLossFailureReasons;
@property(readonly, nonatomic) BOOL canNICSupportPacketLoss;
@property(readonly, retain, nonatomic) NSArray *canNICSupportBandwidthLimitsFailureReasons;
@property(readonly, nonatomic) BOOL canNICSupportBandwidthLimits;
@property(readonly, retain, nonatomic) NSArray *canNICPropagateLinkStateFailureReasons;
@property(readonly, nonatomic) BOOL canNICPropagateLinkState;
@property(readonly, retain, nonatomic) NSArray *canEditUSBControllersFailureReasons;
@property(readonly, nonatomic) BOOL canEditUSBControllers;
@property(readonly, retain, nonatomic) NSArray *canEditAudioDevicesFailureReasons;
@property(readonly, nonatomic) BOOL canEditAudioDevices;
@property(readonly, retain, nonatomic) NSArray *canCDROMUsePhysicalRawFailureReasons;
@property(readonly, nonatomic) BOOL canCDROMUsePhysicalRaw;
@property(readonly, retain, nonatomic) NSArray *canCDROMUseClientRawFailureReasons;
@property(readonly, nonatomic) BOOL canCDROMUseClientRaw;
@property(readonly, retain, nonatomic) NSArray *canDiskMountLocallyFailureReasons;
@property(readonly, nonatomic) BOOL canDiskMountLocally;
@property(readonly, retain, nonatomic) NSArray *canCreateSplitDisksFailureReasons;
@property(readonly, nonatomic) BOOL canCreateSplitDisks;
@property(readonly, retain, nonatomic) NSArray *canCreateSparseDisksFailureReasons;
@property(readonly, nonatomic) BOOL canCreateSparseDisks;
@property(readonly, retain, nonatomic) NSArray *canCreatePhysicalDisksFailureReasons;
@property(readonly, nonatomic) BOOL canCreatePhysicalDisks;
@property(readonly, retain, nonatomic) NSArray *canCreateBlankFloppyFailureReasons;
@property(readonly, nonatomic) BOOL canCreateBlankFloppy;

@end

