//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSToolbarItem.h"

@class DUIVMImageView, DUIVMTextField, NSView;

@interface DUIVMPathToolbarItem : NSToolbarItem
{
    DUIVMImageView *mImageView;
    DUIVMTextField *mTextField;
    NSView *mCustomizeView;
}

@property(retain, nonatomic) NSView *customizeView; // @synthesize customizeView=mCustomizeView;
@property(retain, nonatomic) DUIVMTextField *textField; // @synthesize textField=mTextField;
@property(retain, nonatomic) DUIVMImageView *imageView; // @synthesize imageView=mImageView;
- (void)setVMPath:(id)arg1 vmTitle:(id)arg2;
- (id)finderURLForConfigPath:(id)arg1;
- (void)dealloc;
- (id)initWithItemIdentifier:(id)arg1;

@end

