//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIVM, NSArray, NSMutableArray;

@interface DUIVMScreenshot : NSObject
{
    BOOL mRequestingAutomaticSuspendedScreenshot;
    DUIVM *mVM;
    NSMutableArray *mSuspendedScreenshotObservers;
    NSArray *mSuspendedScreenshots;
}

+ (id)observationKeyPaths;
@property(nonatomic) BOOL requestingAutomaticSuspendedScreenshot; // @synthesize requestingAutomaticSuspendedScreenshot=mRequestingAutomaticSuspendedScreenshot;
@property(retain, nonatomic) NSArray *suspendedScreenshots; // @synthesize suspendedScreenshots=mSuspendedScreenshots;
@property(retain, nonatomic) NSMutableArray *suspendedScreenshotObservers; // @synthesize suspendedScreenshotObservers=mSuspendedScreenshotObservers;
@property(retain, nonatomic) DUIVM *vm; // @synthesize vm=mVM;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)removeObserver:(id)arg1 forKeyPath:(id)arg2 context:(void *)arg3;
- (void)endTrackingForObserver:(id)arg1 forKeyPath:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)suspendedScreenshotsWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)screenshotsWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)onAutomaticSuspendedScreenshots:(id)arg1;
- (void)updateSuspendedScreenshots;
- (void)dealloc;
- (id)initWithVM:(id)arg1;

@end

