//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSObject<OS_dispatch_semaphore>, NSString;

@interface FCProgressInfo : NSObject
{
    NSObject<OS_dispatch_semaphore> *semaphore;
    BOOL shouldContinue;
    int currentStep;
    unsigned int percentCompleted;
    int phase;
    void *auxData;
    NSString *diskName;
    NSError *convertStatus;
}

@property(retain, nonatomic) NSError *convertStatus; // @synthesize convertStatus;
@property(retain, nonatomic) NSString *diskName; // @synthesize diskName;
@property(nonatomic) BOOL shouldContinue; // @synthesize shouldContinue;
@property(nonatomic) void *auxData; // @synthesize auxData;
@property(nonatomic) int phase; // @synthesize phase;
@property(nonatomic) unsigned int percentCompleted; // @synthesize percentCompleted;
@property(nonatomic) int currentStep; // @synthesize currentStep;
- (void)deleteSemaphore;
- (void)waitOnSemaphore;
- (void)signalSemaphore;
- (BOOL)createSemaphore;
- (void)setCorrectedPath:(id)arg1;
- (void)setMoreFilesPath:(id)arg1;
- (id)pathOriginalDisk;
- (struct ParsedConfigData *)configData;
- (void)dealloc;

@end

