//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIController.h"

@class FUSUpdateController;

@interface FUSController : DUIController
{
    id mLicenseUpdatedObserver;
    FUSUpdateController *mUpdateController;
}

@property(retain, nonatomic) FUSUpdateController *updateController; // @synthesize updateController=mUpdateController;
@property(retain, nonatomic) id licenseUpdatedObserver; // @synthesize licenseUpdatedObserver=mLicenseUpdatedObserver;
- (BOOL)isFlexEdition;
- (BOOL)isProEdition;
- (void)registerSoundDeviceListener;
- (void)teardownCUI;
- (void)initCUI;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;

@end

