//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIUpdateController.h"

@interface FUSUpdateController : DUIUpdateController
{
}

- (void)invokeQuiesceReady;
- (void)invokeQuiesceCancel;
- (void)invalidateQuiesceBlocks;
- (void)checkIfInstallCanProceed;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onPowerDownAbortForVM:(id)arg1 cancelled:(BOOL)arg2 error:(id)arg3;
- (void)powerDownAllVMs;
- (void)quiesceRequired;
- (void)promptForInstallWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (int)componentCoreProductType;
- (BOOL)isAntivirusOnHost;
- (void)fetchAntivirusWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)fetchToolsForGuest:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (BOOL)needsToolsDownloadForGuest:(id)arg1;

@end

