//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOpenGLView.h"

@class NSColor, NSRecursiveLock;

@interface MKSOpenGLView : NSOpenGLView
{
    int mDrawMode;
    int mTextureMKS;
    int mTextureUI;
    int mFrameBuffer;
    struct CGSize mMKSSurfaceSize;
    NSRecursiveLock *mLock;
    BOOL mOpaque;
    BOOL mForceVSync;
    unsigned int mLastSurfaceID;
    id <MKSOpenGLViewDelegate> mDelegate;
    NSColor *mBackgroundColor;
    struct CGSize mLastUpdatedSize;
}

+ (id)defaultPixelFormat;
@property(nonatomic) BOOL forceVSync; // @synthesize forceVSync=mForceVSync;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=mBackgroundColor;
@property(nonatomic) unsigned int lastSurfaceID; // @synthesize lastSurfaceID=mLastSurfaceID;
@property(nonatomic) struct CGSize lastUpdatedSize; // @synthesize lastUpdatedSize=mLastUpdatedSize;
@property(nonatomic) id <MKSOpenGLViewDelegate> delegate; // @synthesize delegate=mDelegate;
- (void)drawRect:(struct CGRect)arg1;
- (struct UIDrawnMKSReply)handleDrawCommand:(struct UIDrawnMKSCommand *)arg1;
- (void)viewDidEndLiveResize;
- (void)setFrameSize:(struct CGSize)arg1;
- (BOOL)preservesContentDuringLiveResize;
- (BOOL)isOpaque;
- (void)onWindowScreenChanged:(id)arg1;
- (void)onUserSessionChanged:(id)arg1;
- (void)performDelegateOriginUpdate:(id)arg1;
- (void)dealloc;
- (struct CGPoint)topLeftScreenOrigin;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidChangeBackingProperties;
- (void)reshape;
- (void)update;
- (void)prepareOpenGL;
- (void)performDelegateUpdate;
- (id)initWithCoder:(id)arg1;

@end

