//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAffineTransform.h"

@interface NSAffineTransform (VMAppKitAdditions)
+ (id)transformConservingAspectFromBounds:(struct CGRect)arg1 toFrame:(struct CGRect)arg2;
+ (id)transformFromBounds:(struct CGRect)arg1 toFrame:(struct CGRect)arg2;
- (id)transformRectValueArray:(id)arg1;
- (struct CGRect)transformRect:(struct CGRect)arg1;
@end

