//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArrayController.h"

@interface NSArrayController (VMAppKitAdditions)
- (void)moveObjects:(id)arg1 toArrangedObjectIndex:(long long)arg2;
- (void)moveObjectsAtIndexes:(id)arg1 toIndex:(int)arg2;
- (id)singleSelectedObject;
@end

