//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (VMCocoaAdditions)
+ (id)attributedStringWithString:(id)arg1 fontSize:(double)arg2 alignment:(unsigned long long)arg3;
+ (id)attributedStringWithString:(id)arg1 fontSize:(double)arg2 truncateMiddle:(BOOL)arg3 color:(id)arg4;
+ (id)attributedStringForDate:(id)arg1 relativeDateFormatting:(BOOL)arg2 availableWidth:(double)arg3 color:(id)arg4 fontSize:(double)arg5;
+ (id)firstImageInRTFDData:(id)arg1;
+ (id)attributedStringWithAttributedString:(id)arg1 hyperlink:(id)arg2;
+ (id)attributedStringWithImage:(id)arg1 baselineOffset:(int)arg2;
+ (id)attributedStringWithString:(id)arg1 attributes:(id)arg2;
+ (id)attributedStringWithString:(id)arg1;
- (id)firstImage;
- (long long)firstLineBreakForWidth:(float)arg1;
- (id)linkedAttributedString;
@end

