//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBitmapImageRep.h"

@interface NSBitmapImageRep (VMAppKitAdditions)
+ (id)safeImageRepWithPasteboard:(id)arg1;
+ (id)imageRepWithSize:(struct CGSize)arg1 scale:(unsigned long long)arg2;
+ (id)imageRepFromFlippedBGRABuffer:(char *)arg1 pixelsWide:(long long)arg2 pixelsHigh:(long long)arg3 bytesPerRow:(long long)arg4;
+ (id)imageRepWith32bitBuffer:(char *)arg1 pixelsWide:(long long)arg2 pixelsHigh:(long long)arg3 bitmapFormat:(unsigned long long)arg4 bytesPerRow:(long long)arg5;
- (BOOL)multiplyPixelDataIntoBitmapRep:(id)arg1 offset:(struct CGPoint)arg2;
- (BOOL)convertBitmapDataFromFormat:(unsigned long long)arg1 toFormat:(unsigned long long)arg2;
- (void)setColorProfileFromBitmap:(id)arg1;
- (BOOL)colorProfileMatchesBitmap:(id)arg1;
- (BOOL)uses32BitValues;
- (BOOL)is32bitNonPlanarRGBWithAlpha;
- (BOOL)drawWithBilinearScalingIntoBitmapRep:(id)arg1 targetRect:(struct CGRect)arg2;
- (BOOL)copyBitmapDataIntoRep:(id)arg1 offset:(struct CGPoint)arg2;
@end

