//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (VMAppKitAdditions)
+ (id)colorWithTemplatePatternImage:(id)arg1 withColor:(id)arg2;
+ (id)grayWithInt:(int)arg1;
+ (id)semiDarkBorderForView:(id)arg1;
+ (id)darkBorderForView:(id)arg1;
+ (BOOL)shouldDrawSecondaryHighlightForView:(id)arg1;
+ (id)whiteWithAlpha:(double)arg1;
+ (id)blackWithAlpha:(double)arg1;
- (struct CGColor *)cgColor;
@end

