//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (VMFoundationAdditions)
+ (id)pathToUseAndDisplayForCurrentPath:(id)arg1 localizedFolderPath:(id)arg2 localizedFolderDisplayName:(id)arg3;
- (id)appInfoDictionary:(id)arg1;
- (unsigned long long)directorySizeAtPath:(id)arg1;
- (BOOL)createUserApplicationsDirectory;
- (id)userApplicationsDirectory;
- (id)applicationsDirectory;
- (void)setSharedPermissions:(id)arg1 toMatchPath:(id)arg2 recursive:(BOOL)arg3;
- (BOOL)setSharedPermissions:(id)arg1 toMatchPath:(id)arg2 recursive:(BOOL)arg3 forceCreate:(BOOL)arg4;
- (id)sharedAttributesMatchingPath:(id)arg1 isExecutable:(BOOL)arg2;
- (id)localizedPath:(id)arg1;
- (BOOL)isSharedFileAtPath:(id)arg1;
- (id)uniqueFileNamesForParentPath:(id)arg1 basenameTemplate:(id)arg2 extension:(id)arg3 fileCount:(int)arg4;
- (id)uniquePathForParentPath:(id)arg1 basenameTemplate:(id)arg2 extension:(id)arg3 error:(id *)arg4;
- (id)uniquePathForParentPath:(id)arg1 basenameTemplate:(id)arg2 extension:(id)arg3;
- (BOOL)canMoveFileToTrash:(id)arg1;
- (BOOL)isFileInTrash:(id)arg1;
- (id)configFileForBundlePath:(id)arg1 error:(id *)arg2;
- (BOOL)copyLocalizedPath:(id)arg1 toPath:(id)arg2;
- (id)moveItemAtPath:(id)arg1 toParentPath:(id)arg2 basenameTemplate:(id)arg3 extension:(id)arg4 error:(id *)arg5;
- (id)copyItemAtPath:(id)arg1 toParentPath:(id)arg2 basenameTemplate:(id)arg3 extension:(id)arg4 error:(id *)arg5;
@end

