//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenu.h"

@interface NSMenu (VMAppKitAdditions)
- (struct OpaqueMenuRef *)menuRef;
- (void)removeMenuItemsBeforeTag:(int)arg1;
- (void)removeMenuItemsAfterTag:(int)arg1;
- (void)removeMenuItemsStartingAtTag:(int)arg1;
- (id)pop;
- (BOOL)empty;
- (void)addItemsFromMenu:(id)arg1;
@end

