//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenuItem.h"

@interface NSMenuItem (VMAppKitAdditions)
- (id)initWithTitle:(id)arg1 action:(SEL)arg2 target:(id)arg3 icon:(id)arg4 representedObject:(id)arg5;
- (long long)caseInsensitiveTitleCompare:(id)arg1;
@end

