//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (VMFoundationAdditions)
- (const char *)utf8Description;
- (void)invokeDeferredSelector:(SEL)arg1;
- (void)invokeSelector:(SEL)arg1;
- (void)removeObserver:(id)arg1 forKeyPaths:(id)arg2 context:(void *)arg3;
- (void)removeObserver:(id)arg1 forKeyPaths:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPaths:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)addObserver:(id)arg1 forKeyPaths:(id)arg2;
@end

