//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (VMFoundationAdditions)
+ (id)stringWithPatternFormat:(id)arg1 values:(id)arg2;
+ (id)stringWithPrefix:(id)arg1 uniqueFromStringsInArray:(id)arg2;
+ (id)stringForAddBackSlash:(id)arg1 escapedCharacters:(id)arg2;
+ (id)stringWithUTF8Format:(id)arg1;
- (id)pathExtensionUTI;
- (id)stringBySanitizingPathComponent;
- (id)lowercasePathExtension;
- (unsigned long long)lengthOfBytesUsingUTF8;
- (BOOL)isPathInDirectory:(id)arg1;
- (id)stringByAppendingPathComponents:(id)arg1;
- (BOOL)hasCaseInsensitivePrefix:(id)arg1;
- (id)stringByAddingPercentEscapesWithEncoding:(unsigned int)arg1 escapedLegalCharacters:(id)arg2 unescapedCharacters:(id)arg3;
- (long long)compareStringsAsPaths:(id)arg1;
- (id)initWithUTF8Format:(id)arg1;
- (id)initWithUTF8Format:(id)arg1 arguments:(struct __va_list_tag [1])arg2;
@end

