//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString;

@interface PLAlertAccessoryItem : NSObject
{
    NSString *mTitle;
    NSImage *mPathImage;
}

@property(retain, nonatomic) NSImage *pathImage; // @synthesize pathImage=mPathImage;
@property(copy, nonatomic) NSString *title; // @synthesize title=mTitle;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 pathImage:(id)arg2;

@end

