//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class PLMultiStateAssistant;

@interface PLAssistantPanelController : NSViewController
{
    BOOL mDisableCancel;
    BOOL mDisableGoForward;
    BOOL mDisableGoBackward;
    PLMultiStateAssistant *mAssistant;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) BOOL disableGoBackward; // @synthesize disableGoBackward=mDisableGoBackward;
@property(nonatomic) BOOL disableGoForward; // @synthesize disableGoForward=mDisableGoForward;
@property(nonatomic) BOOL disableCancel; // @synthesize disableCancel=mDisableCancel;
@property(nonatomic) PLMultiStateAssistant *assistant; // @synthesize assistant=mAssistant;
@property(nonatomic) BOOL canGoBackward;
@property(nonatomic) BOOL canGoForward;
@property(nonatomic) BOOL canCancel;
- (void)assistantWillUnload;
- (void)assistantWillStart;
- (void)configureView;
- (void)resetView;
- (void)dealloc;
- (id)initWithAssistant:(id)arg1;
- (id)initWithAssistant:(id)arg1 nibName:(id)arg2 bundle:(id)arg3;

@end

