//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class DUIInventoryVMNode, DUIVM, NSString;

@interface PLAutoDiskCleanupActivityController : NSViewController
{
    BOOL showAutoDiskCleanupProgressCircle;
    unsigned int autoDiskCleanupJobPercent;
    DUIInventoryVMNode *mNode;
    DUIVM *mVM;
    NSString *mAutoDiskCleanupJobTooltip;
}

+ (id)controllerWithVM:(id)arg1;
+ (id)controllerWithInventoryNode:(id)arg1;
+ (id)controller;
@property(copy, nonatomic) NSString *autoDiskCleanupJobTooltip; // @synthesize autoDiskCleanupJobTooltip=mAutoDiskCleanupJobTooltip;
@property(nonatomic) unsigned int autoDiskCleanupJobPercent; // @synthesize autoDiskCleanupJobPercent;
@property(nonatomic) BOOL showAutoDiskCleanupProgressCircle; // @synthesize showAutoDiskCleanupProgressCircle;
@property(retain, nonatomic) DUIVM *vm; // @synthesize vm=mVM;
@property(retain, nonatomic) DUIInventoryVMNode *node; // @synthesize node=mNode;
- (void)removeFromSuperview;
- (void)addToSuperview:(id)arg1;
- (void)autoDiskCleanupUpdateDiskSpaceInfo:(id)arg1;
- (void)autoDiskCleanupJobDidEnd:(id)arg1;
- (void)autoDiskCleanupJobPercentDidChange:(id)arg1;
- (void)autoDiskCleanupJobDidBegin:(id)arg1;
- (id)currentVMID;
- (id)currentVM;
- (id)diskCleanupMgr;
- (void)dealloc;

@end

