//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, PLVMCreationHelper;

@protocol PLChooseOSDelegate
@property(copy, nonatomic) NSString *selectedGuestOSName;
@property(nonatomic) BOOL hasSelectedGuestOS;
@property(readonly, retain, nonatomic) PLVMCreationHelper *vmCreationHelper;
@end

