//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLCreationAssistantPanel.h"

@interface PLCreationAssistantToolsDownloadPanel : PLCreationAssistantPanel
{
    BOOL mIsDownloadingTools;
}

@property(nonatomic) BOOL isDownloadingTools; // @synthesize isDownloadingTools=mIsDownloadingTools;
- (void)downloadTools:(id)arg1;
- (void)resetView;
- (id)initWithAssistant:(id)arg1;

@end

