//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class NSArray, NSString, NSTableView;

@interface PLCreationAssistantImportVAppPanel : PLAssistantPanelController <NSTableViewDelegate, NSTableViewDataSource>
{
    NSArray *mSourceVMs;
    NSTableView *_importVMsTableView;
}

@property(nonatomic) NSTableView *importVMsTableView; // @synthesize importVMsTableView=_importVMsTableView;
@property(retain, nonatomic) NSArray *sourceVMs; // @synthesize sourceVMs=mSourceVMs;
- (void)dealloc;
- (id)getOutput;
- (void)setInputWithSourceVMs:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

