//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

@class PLBaseVMCreationAssistant;

@interface PLCreationAssistantPanel : PLAssistantPanelController
{
}

- (id)initWithAssistant:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) PLBaseVMCreationAssistant *assistant; // @dynamic assistant;

@end

