//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLCreationAssistantPanel.h"

@class NSMutableArray, NSStackView;

@interface PLCreationAssistantFinishPanel : PLCreationAssistantPanel
{
    NSStackView *stackView;
    BOOL mHideCustomizeSettings;
    NSMutableArray *mInfoViewControllers;
}

@property(nonatomic) BOOL hideCustomizeSettings; // @synthesize hideCustomizeSettings=mHideCustomizeSettings;
@property(retain, nonatomic) NSMutableArray *infoViewControllers; // @synthesize infoViewControllers=mInfoViewControllers;
- (void)configureDetailViewWithCreationHelper:(id)arg1;
- (void)configureDetailViewWithVM:(id)arg1;
- (void)addDeviceDetailsForDeviceMgr:(id)arg1 transaction:(id)arg2;
- (void)addInfoLabel:(id)arg1 intMBValue:(int)arg2;
- (void)addInfoLabel:(id)arg1 stringValue:(id)arg2;
- (void)addInfoLabel:(id)arg1 stringValue:(id)arg2 fullValue:(id)arg3;
- (void)resetLabels;
- (void)awakeFromNib;
- (void)showSettings:(id)arg1;
- (void)dealloc;
- (id)initWithAssistant:(id)arg1;

@end

