//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCollectionViewItem.h"

@class NSObject<PLCreationHomeEntryDelegate>, PLCreationHomeEntryView;

@interface PLCreationHomeEntryViewItem : NSCollectionViewItem
{
    BOOL mSelected;
    NSObject<PLCreationHomeEntryDelegate> *_delegate;
    PLCreationHomeEntryView *_entryView;
}

@property(nonatomic) PLCreationHomeEntryView *entryView; // @synthesize entryView=_entryView;
@property(nonatomic) NSObject<PLCreationHomeEntryDelegate> *delegate; // @synthesize delegate=_delegate;
- (BOOL)isSelected;
- (void)mouseDown:(id)arg1;
- (void)setSelected:(BOOL)arg1;

@end

