//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

@class NSArrayController, NSTableView, PLRecoveryPtnAssistant;

@interface PLCreationAssistantRecoveryChooseDiskPanel : PLAssistantPanelController
{
    NSArrayController *diskArrayController;
    NSTableView *diskTableView;
}

- (void)onAllRecoveryPtnDisksDone:(id)arg1;
- (void)onRecoveryPtnDiskDone:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)selectedObject;
- (void)assistantWillUnload;
- (void)configureView;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, nonatomic) PLRecoveryPtnAssistant *assistant; // @dynamic assistant;

@end

