//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMOneShotWindowController.h"

#import "PLLicenseKeyViewControllerDelegate.h"

@class NSButton, NSData, NSImage, NSString, NSTextField, NSTextView, NSView, PLLicenseKeyHelper, PLLicenseKeyViewController;

@interface PLFirstRunWindowController : VMOneShotWindowController <PLLicenseKeyViewControllerDelegate>
{
    NSView *mPlaceholderView;
    NSView *mEULAView;
    NSTextView *mEULATextView;
    NSView *mLicenseKeyView;
    NSButton *mLicenseKeyBuyRadioButton;
    NSButton *mLicenseKeyTryRadioButton;
    NSTextField *mLicenseKeyField;
    PLLicenseKeyViewController *mLicenseKeyViewController;
    NSView *mTrialSelectionView;
    NSButton *mTrialSelectionStandardRadioButton;
    NSButton *mTrialSelectionProRadioButton;
    NSView *mThankYouView;
    NSButton *mCollectInfoButton;
    NSTextView *mCustomerDataCollectionInformView;
    int _licensingResult;
    int _fusionType;
    PLLicenseKeyHelper *mLicenseKeyHelper;
    NSData *mEULA;
    NSView *_currentView;
}

+ (void)show;
+ (BOOL)showAlertsForChineseOnlyVersion;
+ (BOOL)startupShowIfNecessary;
+ (id)windowNibName;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) int fusionType; // @synthesize fusionType=_fusionType;
@property(nonatomic) int licensingResult; // @synthesize licensingResult=_licensingResult;
@property(nonatomic) NSView *currentView; // @synthesize currentView=_currentView;
@property(retain, nonatomic) NSData *eula; // @synthesize eula=mEULA;
@property(readonly, nonatomic) NSButton *collectInfoButton; // @synthesize collectInfoButton=mCollectInfoButton;
@property(readonly, nonatomic) NSButton *trialSelectionProRadioButton; // @synthesize trialSelectionProRadioButton=mTrialSelectionProRadioButton;
@property(readonly, nonatomic) NSButton *trialSelectionStandardRadioButton; // @synthesize trialSelectionStandardRadioButton=mTrialSelectionStandardRadioButton;
@property(readonly, nonatomic) NSButton *licenseKeyTryRadioButton; // @synthesize licenseKeyTryRadioButton=mLicenseKeyTryRadioButton;
@property(readonly, nonatomic) NSButton *licenseKeyBuyRadioButton; // @synthesize licenseKeyBuyRadioButton=mLicenseKeyBuyRadioButton;
@property(readonly, nonatomic) PLLicenseKeyViewController *licenseKeyViewController; // @synthesize licenseKeyViewController=mLicenseKeyViewController;
@property(retain, nonatomic) PLLicenseKeyHelper *licenseKeyHelper; // @synthesize licenseKeyHelper=mLicenseKeyHelper;
- (void)userEnteredInvalidKey:(id)arg1 onTextField:(id)arg2 error:(id)arg3;
- (void)didPresentErrorWithRecovery:(BOOL)arg1 contextInfo:(void *)arg2;
- (void)showThankYouView;
- (void)showTrialSelectionView;
- (void)showLicenseKeyView;
- (void)showEULAView;
- (void)swapView:(id)arg1;
@property(readonly, nonatomic) NSString *eulaHash;
- (void)onThankYouDone:(id)arg1;
@property(readonly, nonatomic) NSImage *thankYouImage;
@property(readonly, nonatomic) NSString *thankYouText;
- (void)trialSelectionHandleError:(id)arg1;
- (void)onTrialSelectionGoBack:(id)arg1;
- (void)onTrialSelectionContinue:(id)arg1;
- (void)onTrialSelectionSelectPro:(id)arg1;
- (void)onTrialSelectionSelectStandard:(id)arg1;
@property(readonly, nonatomic) BOOL trialSelectionContinueIsEnabled;
- (void)onLicenseKeyBuy:(id)arg1;
- (void)onLicenseKeyCancel:(id)arg1;
- (void)onLicenseKeyContinue:(id)arg1;
- (void)onLicenseKeySelectTry:(id)arg1;
- (void)onLicenseKeySelectBuy:(id)arg1;
@property(readonly, nonatomic) BOOL licenseKeyContinueIsEnabled;
@property(readonly, nonatomic) BOOL licenseKeyTryViewsAreEnabled;
@property(readonly, nonatomic) BOOL licenseKeyFieldIsEnabled;
- (void)onEulaSave:(id)arg1;
- (void)onEulaDecline:(id)arg1;
- (void)onEulaAgree:(id)arg1;
@property(readonly, nonatomic) BOOL shouldShowEULA;
- (id)trialSelectionSelectProTitle;
- (id)trialSelectionSelectStandardTitle;
- (id)licenseKeySelectTryTitle;
- (id)licenseKeySelectBuyTitle;
- (void)configureButton:(id)arg1;
- (const char *)versionNumber;
- (void)close;
- (id)licenseMgr;
- (void)awakeFromNib;
- (void)dealloc;

@end

