//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMBaseWindow.h"

#import "DUIMKSChromeOverlayParent.h"
#import "PLFTBTargetWindow.h"
#import "PLMKSRestorableWindow.h"

@class NSString, NSToolbar, NSWindow, PLFTBAccessoryView;

@interface PLFSMWindow : VMBaseWindow <DUIMKSChromeOverlayParent, PLFTBTargetWindow, PLMKSRestorableWindow>
{
    PLFTBAccessoryView *toolbarAux;
    NSToolbar *savedToolbar;
    BOOL mWasOnActiveSpace;
    BOOL mUseDisplayBugWindow;
    NSWindow *displayBugWindow;
    NSWindow *mOverlayWindow;
}

@property(nonatomic) BOOL useDisplayBugWindow; // @synthesize useDisplayBugWindow=mUseDisplayBugWindow;
@property(retain, nonatomic) NSWindow *overlayWindow; // @synthesize overlayWindow=mOverlayWindow;
- (void)toggleTabOverview:(id)arg1;
- (void)toggleTabBar:(id)arg1;
- (void)mergeAllWindows:(id)arg1;
- (void)moveTabToNewWindow:(id)arg1;
- (void)selectPreviousTab:(id)arg1;
- (void)selectNextTab:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2 animate:(BOOL)arg3;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2;
- (void)synchronizeOverlayWindow;
- (id)displayBugWindow;
- (BOOL)needsOverlayWindow;
- (void)restoreStateWithCoder:(id)arg1;
- (void)attachOverlayWindow;
- (void)removeOverlayWindow:(id)arg1;
- (void)addOverlayWindow:(id)arg1;
- (void)onWindowWillExitFullScreen:(id)arg1;
- (void)onWindowDidEnterFullScreen:(id)arg1;
- (void)updateMinibar:(id)arg1;
- (id)windowProvider;
- (id)targetWindow;
- (BOOL)overlapsActiveMenu;
- (BOOL)overlapsMenu;
- (id)accessoryView;
- (void)close;
- (BOOL)squareCorners;
- (BOOL)validateMenuItem:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (void)orderWindow:(long long)arg1 relativeTo:(long long)arg2;
- (void)makeKeyAndOrderFront:(id)arg1;
- (void)onSpaceDidChange:(id)arg1;
- (BOOL)isOnMainScreen;
- (BOOL)switchToFullScreen:(BOOL)arg1;
- (void)toggleFullScreen:(id)arg1;
- (BOOL)isFullScreen;
- (id)kioskDelegate;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

