//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLVMCommonWindowProvider.h"

#import "PLFSMWindowDelegate.h"

@class NSMutableArray, NSString, NSWindow, PLVMSession;

@interface PLFSMWindowProvider : PLVMCommonWindowProvider <PLFSMWindowDelegate>
{
    BOOL mUseDefaultMode;
    BOOL mHideMenuBar;
    BOOL mInRestoration;
    BOOL mInExpose;
    NSMutableArray *mMksWindowControllers;
    id mRestorationObserver;
    NSWindow *mWindowDidFailToEnterFullScreen;
    CDUnknownBlockType mWindowDidEnterFullScreenBlock;
    struct CGRect mRelativeContentRect;
}

+ (double)workspacesSwooshAnimationDuration;
+ (id)observationKeyPaths;
@property(copy, nonatomic) CDUnknownBlockType windowDidEnterFullScreenBlock; // @synthesize windowDidEnterFullScreenBlock=mWindowDidEnterFullScreenBlock;
@property(nonatomic) NSWindow *windowDidFailToEnterFullScreen; // @synthesize windowDidFailToEnterFullScreen=mWindowDidFailToEnterFullScreen;
@property(nonatomic) BOOL inExpose; // @synthesize inExpose=mInExpose;
@property(nonatomic) BOOL inRestoration; // @synthesize inRestoration=mInRestoration;
@property(retain, nonatomic) id restorationObserver; // @synthesize restorationObserver=mRestorationObserver;
@property(nonatomic) BOOL hideMenuBar; // @synthesize hideMenuBar=mHideMenuBar;
@property(nonatomic) BOOL useDefaultMode; // @synthesize useDefaultMode=mUseDefaultMode;
@property(nonatomic) struct CGRect relativeContentRect; // @synthesize relativeContentRect=mRelativeContentRect;
@property(retain, nonatomic) NSMutableArray *mksWindowControllers; // @synthesize mksWindowControllers=mMksWindowControllers;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)windowDidChangeScreen:(id)arg1;
- (void)windowDidFailToExitFullScreen:(id)arg1;
- (void)windowDidFailToEnterFullScreen:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)windowDidChangeViewMode:(id)arg1;
- (BOOL)switchWindow:(id)arg1 toFullScreen:(BOOL)arg2;
- (void)windowDidBecomeKey:(id)arg1;
- (BOOL)windowIsVMLayerWindow:(id)arg1;
- (void)updateMinibarForFullScreen:(BOOL)arg1;
- (id)windowForScreen:(id)arg1;
- (void)minibarSettingsDidChange;
- (void)updateMinibarOptions;
- (void)configureHideMenuBar;
- (void)synchronizeWindowTitleWithDocumentName;
- (BOOL)canSwitchVMLayers;
- (void)updateWindowProviderForLayer:(id)arg1;
- (BOOL)isInFullScreen;
- (BOOL)restoreWindow:(id)arg1 withCoder:(id)arg2;
- (void)restoreSessionWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)configureRestorableWindows;
- (id)keyMKSWindow;
- (id)guestPrimary;
- (id)allMKSWindows;
- (void)updateActiveLayer;
- (void)updateWindowsForLayer:(id)arg1 shouldShow:(BOOL)arg2;
- (id)windowForRestoration:(id)arg1;
- (void)makeWindowsForScreens:(id)arg1;
- (BOOL)toggleFullScreenForLayer:(id)arg1;
- (BOOL)switchWindowsToFullScreen:(BOOL)arg1;
- (void)showWindows;
- (void)showMKSWindowsIfNeeded;
- (void)synchronizeWindowsAndSpaces;
- (void)showMKSWindows;
- (void)delayedMakeKeyAndOrderFrontForWindow:(id)arg1 withWaitTime:(double)arg2;
- (void)closeVMLayerWindowsExcluding:(id)arg1;
- (void)closeForBackgroundProcessing;
- (void)closeAllMKSWindows;
- (void)close;
- (id)createMKSWindowController;
- (void)configureWindow:(id)arg1;
- (void)updateWindowsForFullScreenState;
- (void)onDisplayReconfigured:(id)arg1;
- (void)clearWindowDidFailToEnterFullScreen:(id)arg1;
- (void)onExitExpose;
- (void)onEnterExpose;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) PLVMSession *session; // @dynamic session;
@property(readonly) Class superclass;

@end

