//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLFTBBackgroundView.h"

@class NSButton, NSMutableArray, NSTrackingArea, NSWindow<PLFTBTargetWindow>, PLFTBMinibarViewController;

@interface PLFTBMinibarView : PLFTBBackgroundView
{
    PLFTBMinibarViewController *viewController;
    NSButton *mPowerButton;
    NSButton *mMenuButton;
    NSButton *mFullscreenButton;
    NSMutableArray *mToolbarButtons;
    NSTrackingArea *mDragTrackingArea;
    BOOL mTemporarilyDisabled;
    BOOL mIsDisabled;
    NSWindow<PLFTBTargetWindow> *mPlaceholderTarget;
    struct CGRect mDragRect;
    long long mPushCount;
    NSButton *_miniaturizeButton;
}

+ (id)templateColorForCell:(id)arg1;
@property(readonly, retain, nonatomic) NSButton *miniaturizeButton; // @synthesize miniaturizeButton=_miniaturizeButton;
@property(retain, nonatomic) NSWindow<PLFTBTargetWindow> *placeholderTarget; // @synthesize placeholderTarget=mPlaceholderTarget;
@property(nonatomic) BOOL isDisabled; // @synthesize isDisabled=mIsDisabled;
@property(nonatomic) BOOL temporarilyDisabled; // @synthesize temporarilyDisabled=mTemporarilyDisabled;
@property(retain, nonatomic) NSTrackingArea *dragTrackingArea; // @synthesize dragTrackingArea=mDragTrackingArea;
@property(retain, nonatomic) NSMutableArray *toolbarButtons; // @synthesize toolbarButtons=mToolbarButtons;
@property(retain, nonatomic) NSButton *fullscreenButton; // @synthesize fullscreenButton=mFullscreenButton;
@property(retain, nonatomic) NSButton *menuButton; // @synthesize menuButton=mMenuButton;
@property(retain, nonatomic) NSButton *powerButton; // @synthesize powerButton=mPowerButton;
- (BOOL)shouldShowButtons;
- (id)menuForEvent:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (id)updateTrackingAreaWithRect:(struct CGRect)arg1;
- (BOOL)isMouseInsideRect:(struct CGRect)arg1;
- (void)resetCursor;
- (void)drawRect:(struct CGRect)arg1;
- (void)validateUserInterface;
- (void)syncButtonsToView:(id)arg1;
- (void)syncButton:(id)arg1 toButton:(id)arg2;
- (void)addStandardWindowButtons;
- (void)toggleFullScreen:(id)arg1;
- (id)target;
- (id)placeholderButtonFromButton:(id)arg1;
- (void)performLayout;
- (id)standardWindowButton:(unsigned long long)arg1;
- (double)minLength;
- (BOOL)disabled;
- (void)configureToolbarButton:(id)arg1;
- (id)viewController;
- (BOOL)isOpaque;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 targetWindow:(id)arg2 originalView:(id)arg3;

@end

