//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSMenuDelegate.h"

@class NSMenu, NSString;

@interface PLFTBMinibarViewController : NSViewController <NSMenuDelegate>
{
    NSMenu *minibarMenu;
}

+ (id)observationKeyPaths;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onPowerButtonClicked:(id)arg1;
- (id)powerButtonAction;
- (void)updatePowerButton;
- (void)setTemporarilyDisabled:(BOOL)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)updateDeviceMenuItems:(id)arg1;
- (id)deviceMenuItems;
- (id)session;
- (void)awakeFromNib;
- (id)minibarView;
- (void)closeSession;
- (void)dealloc;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

