//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "PLPrefsPaneController.h"

@class NSComboBox, NSStackView, NSString, PLGeneralSettingView, PLVMStartMenuShortcutFieldEditor;

@interface PLGeneralPrefsPaneController : NSViewController <PLPrefsPaneController>
{
    NSStackView *mStackView;
    PLGeneralSettingView *mClosePrefs;
    PLGeneralSettingView *mShortcutPrefs;
    PLGeneralSettingView *mGamingPrefs;
    PLGeneralSettingView *mUpdatePrefs;
    PLGeneralSettingView *mStartMenuPrefs;
    NSComboBox *shortcutComboBox;
    PLVMStartMenuShortcutFieldEditor *mFieldEditor;
}

+ (id)observationKeyPaths;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) PLVMStartMenuShortcutFieldEditor *fieldEditor; // @synthesize fieldEditor=mFieldEditor;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)comboBox:(id)arg1 objectValueForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsInComboBox:(id)arg1;
- (void)onShortcutChanged:(id)arg1;
- (void)updateStartMenuShortcut;
- (void)setShowStartMenu:(int)arg1;
- (int)showStartMenu;
- (void)setStartMenuShortcutEnabled:(BOOL)arg1;
- (BOOL)startMenuShortcutEnabled;
- (id)fieldEditorForObject:(id)arg1;
- (void)setSelectedObject:(id)arg1;
- (void)addViewToStack:(id)arg1;
- (void)awakeFromNib;
- (id)plController;
- (id)prefs;
- (id)icon;
- (id)label;
- (id)identifier;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

