//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSBox, NSButton, NSLayoutConstraint, NSView, PLImportSavePanelAccessory;

@interface PLImportSavePanelViewController : NSViewController
{
    NSView *normalSpaceView;
    NSView *insufficientSpaceView;
    NSBox *spaceView;
    NSButton *sharingCheckbox;
    NSLayoutConstraint *spaceViewHeightConstraint;
    BOOL mDidAwakeFromNib;
    PLImportSavePanelAccessory *mAccessory;
    double mViewHeight;
}

@property(nonatomic) NSButton *sharingCheckbox; // @synthesize sharingCheckbox;
@property(nonatomic) double viewHeight; // @synthesize viewHeight=mViewHeight;
@property(nonatomic) BOOL didAwakeFromNib; // @synthesize didAwakeFromNib=mDidAwakeFromNib;
@property(nonatomic) PLImportSavePanelAccessory *accessory; // @synthesize accessory=mAccessory;
- (void)installViewOnSavePanel:(id)arg1;
- (void)onSharingCheckboxPressed:(id)arg1;
- (void)awakeFromNib;
- (id)init;

@end

