//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLPreprocessedVMAssistant.h"

#import "PLVMCreationAssistantURLTarget.h"

@class NSString, NSURL, PLCreationAssistantImportAdditionalSettingsPanel, PLCreationAssistantImportChooseFilePanel, PLCreationAssistantImportDeploymentPanel, PLCreationAssistantImportEULAPanel, PLCreationAssistantImportProgressPanel, PLCreationAssistantImportVAppFinishPanel, PLCreationAssistantImportVAppPanel, PLImportCreationDelegate, PLOVFImportController;

@interface PLImportAssistant : PLPreprocessedVMAssistant <PLVMCreationAssistantURLTarget>
{
    PLCreationAssistantImportChooseFilePanel *chooseFilePanel;
    PLCreationAssistantImportProgressPanel *importPanel;
    BOOL mIsImporting;
    BOOL mPrefCheckDone;
    NSURL *mDefaultDirectoryURL;
    PLImportCreationDelegate *mImportDelegate;
    NSURL *mDestFileURL;
    PLCreationAssistantImportEULAPanel *mEulaPanel;
    PLCreationAssistantImportDeploymentPanel *mDeploymentPanel;
    PLCreationAssistantImportAdditionalSettingsPanel *mAdditionalSettingsPanel;
    PLCreationAssistantImportVAppPanel *mVAppPanel;
    PLCreationAssistantImportVAppFinishPanel *mVAppFinishPanel;
    PLOVFImportController *mOvfImportController;
}

+ (BOOL)acceptsURL:(id)arg1;
+ (id)supportedTypes;
@property(retain, nonatomic) PLOVFImportController *ovfImportController; // @synthesize ovfImportController=mOvfImportController;
@property(retain, nonatomic) PLCreationAssistantImportVAppFinishPanel *vAppFinishPanel; // @synthesize vAppFinishPanel=mVAppFinishPanel;
@property(retain, nonatomic) PLCreationAssistantImportVAppPanel *vAppPanel; // @synthesize vAppPanel=mVAppPanel;
@property(retain, nonatomic) PLCreationAssistantImportAdditionalSettingsPanel *additionalSettingsPanel; // @synthesize additionalSettingsPanel=mAdditionalSettingsPanel;
@property(retain, nonatomic) PLCreationAssistantImportDeploymentPanel *deploymentPanel; // @synthesize deploymentPanel=mDeploymentPanel;
@property(retain, nonatomic) PLCreationAssistantImportEULAPanel *eulaPanel; // @synthesize eulaPanel=mEulaPanel;
@property(nonatomic) BOOL prefCheckDone; // @synthesize prefCheckDone=mPrefCheckDone;
@property(nonatomic) BOOL isImporting; // @synthesize isImporting=mIsImporting;
@property(retain, nonatomic) NSURL *destFileURL; // @synthesize destFileURL=mDestFileURL;
@property(retain, nonatomic) PLImportCreationDelegate *importDelegate; // @synthesize importDelegate=mImportDelegate;
@property(retain, nonatomic) NSURL *defaultDirectoryURL; // @synthesize defaultDirectoryURL=mDefaultDirectoryURL;
- (void)finishVAppCreation;
- (void)choosePanelDidEnd:(id)arg1;
- (void)finishVAppImportWithTempFolder:(id)arg1 destination:(id)arg2;
- (void)moveImportedVMsFrom:(id)arg1 to:(id)arg2 onAbort:(CDUnknownBlockType)arg3 onDone:(CDUnknownBlockType)arg4;
- (BOOL)moveVMFrom:(id)arg1 to:(id)arg2;
- (id)makeTempFolderAtPath:(id)arg1 error:(id *)arg2;
- (void)powerOnOrShowSettings:(id)arg1 powerOn:(BOOL)arg2;
- (void)savePanelDidEnd:(id)arg1;
- (void)doCleanupOnFailure;
- (id)importFilePath;
- (void)findAvailableDidEndWithName:(id)arg1;
- (void)configureSaveVAppPanel:(id)arg1;
- (void)configureSavePanel:(id)arg1 displayName:(id)arg2;
- (void)showSaveVAppPanel;
- (void)showSavePanel;
- (void)resetImportButtons;
- (BOOL)needsToolsDownload;
- (id)toolsGuestKey;
- (void)loadFromPrefs;
- (void)loadForeignPrefs;
- (void)simpleParser:(id)arg1 foundElement:(id)arg2 withValue:(id)arg3;
- (void)setDefaultVmFolderFromXML:(id)arg1;
- (id)addImportableURL:(id)arg1;
- (void)setFallbackDefaultVmFolder;
- (void)draggingExited:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (id)draggedTypesForState:(int)arg1;
- (BOOL)chooseURLs:(id)arg1;
- (id)converterForURL:(id)arg1;
- (BOOL)isOVFTypeOfURL:(id)arg1;
- (void)configureChooseFileView;
- (void)finishCreation;
- (void)openURLs:(id)arg1;
- (id)resultBundleURL;
- (void)assistantWillUnload;
- (void)cancel;
- (BOOL)start;
- (void)goBackward;
- (BOOL)goForward;
- (void)configOutputForState:(int)arg1;
- (void)configInputForState:(int)arg1;
- (int)previousStateWithState:(int)arg1;
- (int)nextStateWithState:(int)arg1;
- (void)probeOVFWithURL:(id)arg1;
- (long long)stepIndexForState:(int)arg1;
- (id)localizedNameForStep:(long long)arg1;
- (void)stateDidChangeFromState:(int)arg1;
- (id)viewForState:(int)arg1;
- (long long)helpTag;
- (id)title;
- (id)subtitleForState:(int)arg1;
- (id)titleForState:(int)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initWithAssistantManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

