//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMTreeCollectionViewItem.h"

@class DUIInventory, DUIInventoryNode, NSImage, NSImageView, PLInventoryResponder, VMItemTextField;

@interface PLInventoryCollectionViewItem : VMTreeCollectionViewItem
{
    NSImageView *itemImageView;
    VMItemTextField *itemTextField;
    PLInventoryResponder *inventoryResponder;
    DUIInventoryNode *node;
    NSImage *image;
    DUIInventory *mInventory;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) DUIInventory *inventory; // @synthesize inventory=mInventory;
@property(nonatomic) DUIInventoryNode *node; // @synthesize node;
@property(nonatomic) PLInventoryResponder *inventoryResponder; // @synthesize inventoryResponder;
@property(retain, nonatomic) NSImage *image; // @synthesize image;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)menuNeedsUpdate:(id)arg1;
- (BOOL)validateTitle:(id *)arg1 error:(id *)arg2;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)detail;
- (void)editItem;
@property(readonly, nonatomic) BOOL canRename;
- (void)unloadView;
- (void)dealloc;
- (void)awakeFromNib;

@end

