//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLInventoryVMInfoViewController.h"

#import "PLInventoryInfoViewController.h"

@class DUIInventoryNode, NSArray, NSLayoutConstraint, NSPopover, NSString, NSView, PLAutoDiskCleanupActivityController, PLVMDiskSpace;

@interface PLInventoryLocalInfoViewController : PLInventoryVMInfoViewController <PLInventoryInfoViewController>
{
    NSView *diskSpaceView;
    PLVMDiskSpace *diskSpaceCalculator;
    NSPopover *popover;
    NSView *notesView;
    NSLayoutConstraint *diskSpaceHeightConstraint;
    NSArray *clonesTableContent;
    BOOL showDiskSpace;
    BOOL showCleanupLabel;
    NSView *autoDiskCleanupActivityContainerView;
    BOOL mCloneInfo;
    double mDiskSpaceHeight;
    PLAutoDiskCleanupActivityController *mAutoDiskCleanupActivityController;
}

+ (id)observationKeyPaths;
@property(retain, nonatomic) PLAutoDiskCleanupActivityController *autoDiskCleanupActivityController; // @synthesize autoDiskCleanupActivityController=mAutoDiskCleanupActivityController;
@property(nonatomic) double diskSpaceHeight; // @synthesize diskSpaceHeight=mDiskSpaceHeight;
@property(copy, nonatomic) NSArray *clonesTableContent; // @synthesize clonesTableContent;
@property(nonatomic) BOOL showCloneInfo; // @synthesize showCloneInfo=mCloneInfo;
@property(nonatomic) BOOL showCleanupLabel; // @synthesize showCleanupLabel;
@property(nonatomic) BOOL showDiskSpace; // @synthesize showDiskSpace;
@property(readonly, retain, nonatomic) PLVMDiskSpace *diskSpaceCalculator; // @synthesize diskSpaceCalculator;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onDUIInventoryDidChange:(id)arg1;
- (id)finderPathFromCfgPath:(id)arg1;
- (void)updateCloneInfo;
- (BOOL)shouldShowCleanupLabel;
- (BOOL)hasShrinkableContent;
- (void)updateDataSource;
- (void)updateDiskSpace:(id)arg1;
- (id)infoIcon;
- (id)infoString;
@property(readonly, copy, nonatomic) NSString *cloneInfoTooltip;
- (void)toggleLinkedCloneInfo:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithInventoryNode:(id)arg1;

// Remaining properties
@property(retain, nonatomic) DUIInventoryNode *node;

@end

