//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIMKSChrome.h"

#import "VMDraggableViewInteractiveChild.h"

@class PLInventoryCollectionViewVMItem;

@interface PLInventoryMKSView : DUIMKSChrome <VMDraggableViewInteractiveChild>
{
    PLInventoryCollectionViewVMItem *vmItem;
}

- (BOOL)acceptsNonDragMouseClick:(id)arg1;
- (void)handleNonDragMouseClick:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1;
- (void)mouseDown:(id)arg1;
- (double)preferredHeightForSize:(struct CGSize)arg1;
- (void)initialize;

@end

