//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DUIInventoryNode, NSArray, NSIndexPath, NSNotification, NSTreeNode, NSView;

@protocol PLInventoryViewController
- (void)closeView;
- (void)editItem:(DUIInventoryNode *)arg1 atIndexPath:(NSIndexPath *)arg2 target:(id)arg3;
- (void)onWindowWillClose:(NSNotification *)arg1;
- (NSView *)initialKeyView;
- (void)viewWillShowWithTreeNode:(NSTreeNode *)arg1;
- (void)expandTreeNode:(NSTreeNode *)arg1;
- (void)showContentsAtIndexPath:(NSIndexPath *)arg1;
- (void)setSelectionIndexPath:(NSIndexPath *)arg1;
- (NSArray *)selectedNodes;
- (void)navigateToTreeNode:(NSTreeNode *)arg1;
- (NSIndexPath *)selectedFolderIndexPath;
- (NSIndexPath *)navigationIndexPath;
@end

