//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLSessionWindowController.h"

//#import "NSToolbarDelegate.h"
//#import "NSTouchBarDelegate.h"
//#import "PLLibraryLayer.h"

@class DUIDlgMgr, DUIInventoryNode, NSArray, NSArrayController, NSBox, NSLayoutConstraint, NSMutableDictionary, NSPathComponentCell, NSPathControl, NSSegmentedControl, NSString, NSTextField, NSTimer, NSViewController, PLInventoryCollectionViewController, PLInventoryManager, PLInventoryOutlineViewController, PLInventoryResponder, PLWindowedSession, VMTreeArrayController;

@interface PLInventoryWindowController : PLSessionWindowController //PLSessionWindowController <NSTouchBarDelegate, NSToolbarDelegate, PLLibraryLayer>
{
    NSBox *contentBox;
    VMTreeArrayController *treeController;
    NSArrayController *searchResultsController;
    PLInventoryOutlineViewController *outlineStyleViewController;
    PLInventoryCollectionViewController *collectionStyleViewController;
    PLInventoryResponder *inventoryResponder;
    NSSegmentedControl *viewStyleControl;
    NSPathControl *pathControl;
    NSTextField *searchField;
    NSLayoutConstraint *pathContainerHeight;
    BOOL mShowSearchResults;
    BOOL mIsObservingKeyPaths;
    DUIInventoryNode *mSelectedNode;
    VMTreeArrayController *mTreeController;
    PLInventoryResponder *mInventoryResponder;
    PLInventoryManager *mInventoryMgr;
    NSViewController *mActiveViewController;
    //NSViewController<PLInventoryViewController> *mActiveViewController;
    NSString *mWindowTitle;
    DUIDlgMgr *mDlgMgr;
    NSTimer *mCloseNodesTimer;
    NSArray *mVMsToClose;
    NSMutableDictionary *mOpenedVMMap;
    NSPathComponentCell *mPathComponentPrototypeCell;
}

+ (id)observationKeyPaths;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) BOOL isObservingKeyPaths; // @synthesize isObservingKeyPaths=mIsObservingKeyPaths;
@property(retain, nonatomic) NSPathComponentCell *pathComponentPrototypeCell; // @synthesize pathComponentPrototypeCell=mPathComponentPrototypeCell;
@property(nonatomic) BOOL showSearchResults; // @synthesize showSearchResults=mShowSearchResults;
@property(retain, nonatomic) NSMutableDictionary *openedVMMap; // @synthesize openedVMMap=mOpenedVMMap;
@property(retain, nonatomic) NSArray *vmsToClose; // @synthesize vmsToClose=mVMsToClose;
@property(retain, nonatomic) NSTimer *closeNodesTimer; // @synthesize closeNodesTimer=mCloseNodesTimer;
@property(retain, nonatomic) DUIDlgMgr *dlgMgr; // @synthesize dlgMgr=mDlgMgr;
@property(retain, nonatomic) NSString *windowTitle; // @synthesize windowTitle=mWindowTitle;
@property(nonatomic) NSViewController *activeViewController;
//@property(nonatomic) NSViewController<PLInventoryViewController> *activeViewController; // @synthesize activeViewController=mActiveViewController;
@property(retain, nonatomic) PLInventoryManager *inventoryMgr; // @synthesize inventoryMgr=mInventoryMgr;
@property(nonatomic) PLInventoryResponder *inventoryResponder; // @synthesize inventoryResponder=mInventoryResponder;
@property(nonatomic) VMTreeArrayController *treeController; // @synthesize treeController=mTreeController;
@property(retain, nonatomic) DUIInventoryNode *selectedNode; // @synthesize selectedNode=mSelectedNode;
- (id)touchBar:(id)arg1 makeItemForIdentifier:(id)arg2;
- (id)makeTouchBar;
- (void)invalidateTouchBar;
- (id)features;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)clearSearchResults;
- (void)toolbarDidRemoveItem:(id)arg1;
- (void)updateSearchResults:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)windowDidChangeOcclusionState:(id)arg1;
- (void)onNewVMAddedNotification:(id)arg1;
- (void)openVMForNode:(id)arg1;
- (id)selectedVMNode;
- (void)writeSelectionPersistentObjects;
- (void)restoreSelectionPersistentObjects;
- (id)selectedInventoryNodes;
- (void)closeNodesTimerFired:(id)arg1;
- (void)updateCloseNodesTimer;
- (void)closeVMWithID:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)openDroppedNodes:(id)arg1;
- (void)updateCurrentSelection;
- (void)updatePathControl;
- (void)selectNodeForInventory:(id)arg1;
- (void)expandNode:(id)arg1;
- (void)onPathControlAction:(id)arg1;
- (id)componentCellForTreeRoot:(id)arg1;
- (id)componentCellFromNode:(id)arg1;
- (void)loadViewForStyleTag:(int)arg1;
- (void)changeViewStyle:(id)arg1;
- (void)onSearchResultsDidChange:(id)arg1;
- (void)updateSelectionForDeletion:(id)arg1;
- (void)onInventoryDidChange:(id)arg1;
- (id)windowTitleForDocumentDisplayName:(id)arg1;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;
- (void)awakeFromNib;
- (void)dealloc;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)close;
- (void)prepareToCloseContentWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (BOOL)canSessionCloseForTermination:(BOOL)arg1;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) PLWindowedSession *session; // @dynamic session;
@property(readonly) Class superclass;

@end

