//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBox.h"

@interface PLInventoryLineView : NSBox
{
    BOOL mUseGradient;
}

@property(nonatomic) BOOL useGradient; // @synthesize useGradient=mUseGradient;
- (void)drawRect:(struct CGRect)arg1;

@end

