//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSComboBox.h"

@class DUIKeyboardAndMouseMappingInfo;

@interface PLKeyboardShortcutComboBox : NSComboBox
{
    DUIKeyboardAndMouseMappingInfo *mShortcut;
}

@property(retain, nonatomic) DUIKeyboardAndMouseMappingInfo *shortcut; // @synthesize shortcut=mShortcut;
- (void)textDidChange:(id)arg1;
- (void)updateStringValue;
- (void)dealloc;

@end

