//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@class DUIKeyboardAndMouseMappingInfo;

@interface PLKeyboardShortcutTextFieldCell : NSTextFieldCell
{
    DUIKeyboardAndMouseMappingInfo *mShortcut;
    BOOL mDisableDrawingModifiers;
    BOOL mShowWarning;
}

@property(nonatomic) BOOL showWarning; // @synthesize showWarning=mShowWarning;
@property(retain, nonatomic) DUIKeyboardAndMouseMappingInfo *shortcut; // @synthesize shortcut=mShortcut;
@property(nonatomic) BOOL disableDrawingModifiers; // @synthesize disableDrawingModifiers=mDisableDrawingModifiers;
- (struct CGRect)expansionFrameWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)drawObject:(id)arg1 inFrame:(struct CGRect)arg2 xPos:(double *)arg3;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)applyAttributesToString:(id)arg1;
- (void)setObjectValue:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)updateStringValue;
- (void)dealloc;

@end

