//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "PLPrefsPaneController.h"

@class DUIKeyboardAndMouseProfile, NSPopUpButton, NSString, NSView, PLKeyboardProfileEditor;

@interface PLKeyboardPrefsPaneController : NSViewController <PLPrefsPaneController>
{
    DUIKeyboardAndMouseProfile *selectedProfile;
    PLKeyboardProfileEditor *profileEditor;
    NSPopUpButton *profilesPopup;
    NSView *profileContainerView;
}

+ (id)identifier;
@property(retain) PLKeyboardProfileEditor *profileEditor; // @synthesize profileEditor;
@property(retain) DUIKeyboardAndMouseProfile *selectedProfile; // @synthesize selectedProfile;
- (void)onKeyboardProfilesSheetDone:(id)arg1 contextInfo:(id)arg2;
- (id)profiles;
- (void)selectProfile:(id)arg1;
- (void)onProfileChanged:(id)arg1;
- (void)updateProfilesMenu;
- (void)setSelectedObject:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)onProfilesPopup:(id)arg1;
- (id)icon;
- (id)label;
- (id)identifier;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

