//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMOneShotWindowController.h"

#import "WebPolicyDelegate.h"
#import "WebResourceLoadDelegate.h"

@class NSString, WebView;

@interface PLLearningCenterWindowController : VMOneShotWindowController <WebPolicyDelegate, WebResourceLoadDelegate>
{
    WebView *learningCenterView;
}

+ (BOOL)showURLWithIndex:(int)arg1;
+ (id)windowNibName;
- (void)webView:(id)arg1 resource:(id)arg2 didFailLoadingWithError:(id)arg3 fromDataSource:(id)arg4;
- (void)webView:(id)arg1 resource:(id)arg2 didFinishLoadingFromDataSource:(id)arg3;
- (void)webView:(id)arg1 decidePolicyForNewWindowAction:(id)arg2 request:(id)arg3 newFrameName:(id)arg4 decisionListener:(id)arg5;
- (void)loadErrorPage;
- (void)loadURLWithIndex:(int)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

