//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PLLicenseKeyHelper : NSObject
{
}

- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (BOOL)applyLicenseKey:(id)arg1 error:(id *)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (BOOL)applyFLEXLicenseKey:(id)arg1 error:(id *)arg2;
- (BOOL)checkSerialNumber:(id)arg1 error:(id *)arg2;
- (id)localizedErrorForError:(id)arg1;

@end

