//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, VMLicense;

@interface PLLicenseMgr : NSObject
{
    VMLicense *currentLicense;
    BOOL isFromMacAppStore;
    int appStoreLicenseType;
    BOOL isProEdition;
    BOOL isFlexEdition;
    BOOL _isSimplifiedChineseEdition;
    NSString *mDisplayVersionNumber;
}

+ (BOOL)isFromMacAppStore;
+ (BOOL)isSimplifiedChineseEdition;
+ (BOOL)isFlexEdition;
+ (BOOL)isProEdition;
+ (id)lastModifiedDate;
+ (id)expirationInfoDictionary;
+ (BOOL)isLicensed;
+ (BOOL)hadOlderLicense;
+ (int)licenseType;
+ (int)licenseTypeForVersion:(const char *)arg1;
+ (id)supportId;
+ (id)olderSerialNumber;
+ (id)serialNumber;
+ (id)serialNumberForVersion:(const char *)arg1;
+ (BOOL)isValidSerialNumber:(id)arg1;
+ (id)sharedLicenseMgr;
@property(nonatomic) BOOL isSimplifiedChineseEdition; // @synthesize isSimplifiedChineseEdition=_isSimplifiedChineseEdition;
@property(copy, nonatomic) NSString *displayVersionNumber; // @synthesize displayVersionNumber=mDisplayVersionNumber;
@property(nonatomic) BOOL isFlexEdition; // @synthesize isFlexEdition;
@property(nonatomic) BOOL isProEdition; // @synthesize isProEdition;
@property(readonly, nonatomic) int appStoreLicenseType; // @synthesize appStoreLicenseType;
@property(readonly, nonatomic) BOOL isFromMacAppStore; // @synthesize isFromMacAppStore;
@property(retain, nonatomic) VMLicense *currentLicense; // @synthesize currentLicense;
- (BOOL)checkSerialNumber:(id)arg1 error:(id *)arg2;
- (BOOL)checkFLEXSerialNumber:(id)arg1 error:(id *)arg2;
- (BOOL)registerSerialNumber:(id)arg1 error:(id *)arg2;
- (int)parseMessages:(id)arg1 registerCode:(int *)arg2;
- (void)updateCurrentLicense;
- (void)testAppStore;
- (void)dealloc;
- (id)init;

@end

