//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "VMSerialFormatterDelegate.h"

@class NSImage, NSObject<PLLicenseKeyViewControllerDelegate>, NSString, NSTextField, VMSerialFormatter;

@interface PLLicenseKeyViewController : NSViewController <VMSerialFormatterDelegate>
{
    NSObject<PLLicenseKeyViewControllerDelegate> *delegate;
    NSTextField *licenseKeyField;
    BOOL _continueIsEnabled;
    BOOL _statusImageIsHidden;
    NSImage *mSuccessStatusImage;
    NSImage *mFailureStatusImage;
    VMSerialFormatter *mSerialFormatter;
    NSImage *_statusImage;
}

@property(nonatomic) BOOL statusImageIsHidden; // @synthesize statusImageIsHidden=_statusImageIsHidden;
@property(nonatomic) NSImage *statusImage; // @synthesize statusImage=_statusImage;
@property(nonatomic) BOOL continueIsEnabled; // @synthesize continueIsEnabled=_continueIsEnabled;
@property(retain, nonatomic) VMSerialFormatter *serialFormatter; // @synthesize serialFormatter=mSerialFormatter;
@property(retain, nonatomic) NSImage *failureStatusImage; // @synthesize failureStatusImage=mFailureStatusImage;
@property(retain, nonatomic) NSImage *successStatusImage; // @synthesize successStatusImage=mSuccessStatusImage;
- (id)serialInputFieldEditor;
- (void)serialInputBlank;
- (void)serialInputCompleteWithString:(id)arg1;
- (void)serialInputInProgress;
- (void)resetLicenseKeyField;
- (void)updateLicenseKeyField;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

