//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLContent.h"

@class DUIInventory, DUIVMID, NSArray;

@protocol PLLibraryLayer <PLContent>
- (void)closeVMWithID:(DUIVMID *)arg1 abortHandler:(void (^)(BOOL, NSError *))arg2 doneHandler:(void (^)(void))arg3;
- (void)selectNodeForInventory:(DUIInventory *)arg1;
- (NSArray *)selectedInventoryNodes;
@end

