//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSControl, NSString, PLNetworkTableItem;

@protocol PLNetworkConfigDelegate
- (void)showNoNetcfgMgrAlert;
- (id)representedObject;
- (void)dataSourceDidReload;
- (void)selectionDidChange:(PLNetworkTableItem *)arg1;
- (void)changeActiveTableItem:(PLNetworkTableItem *)arg1;
- (void)configureInfoViewForItem:(PLNetworkTableItem *)arg1;

@optional
- (void)showInvalidNameAlertForControl:(NSControl *)arg1 withOldName:(NSString *)arg2;
- (void)dataSourceDidChanged;
- (BOOL)allowChanges;
@end

