//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSTextFieldDelegate.h"

@class DUIPortForwardEntry, NSObject<PLPortForwardEditDelegate>, NSString, NSTextField;

@interface PLPortForwardEditWindowController : NSWindowController <NSTextFieldDelegate>
{
    NSTextField *hostPortField;
    NSTextField *vmPortField;
    NSTextField *ipField;
    NSTextField *descField;
    NSObject<PLPortForwardEditDelegate> *mConfigDelegate;
    DUIPortForwardEntry *mPortForwardEntry;
    CDUnknownBlockType mCompletionHandler;
}

+ (id)beginSheetModalForWindow:(id)arg1 portForwardEntry:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=mCompletionHandler;
@property(retain, nonatomic) DUIPortForwardEntry *portForwardEntry; // @synthesize portForwardEntry=mPortForwardEntry;
@property(nonatomic) NSObject<PLPortForwardEditDelegate> *configDelegate; // @synthesize configDelegate=mConfigDelegate;
- (void)setDesc:(id)arg1;
- (id)desc;
- (void)setIp:(id)arg1;
- (id)ip;
- (void)setVmPort:(id)arg1;
- (id)vmPort;
- (void)setHostPort:(id)arg1;
- (id)hostPort;
- (void)onInvalidInput:(id)arg1;
- (BOOL)validateDesc:(id *)arg1 error:(id *)arg2;
- (BOOL)validateIp:(id *)arg1 error:(id *)arg2;
- (BOOL)portValidation:(int)arg1 error:(id *)arg2;
- (BOOL)validateVmPort:(id *)arg1 error:(id *)arg2;
- (BOOL)validateHostPort:(id *)arg1 error:(id *)arg2;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1 modalForWindow:(id)arg2 portForwardEntry:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)onOK:(id)arg1;
- (void)onCancel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

