//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMOneShotWindowController.h"

#import "NSToolbarDelegate.h"

@class DUIFeatures, NSArray, NSDictionary, NSString;

@interface PLPrefsWindowController : VMOneShotWindowController <NSToolbarDelegate>
{
    NSArray *paneIdentifiers;
    NSDictionary *paneControllers;
    NSString *networkPaneIdentifier;
    NSString *generalPaneIdentifier;
    NSString *currentPaneIdentifier;
}

+ (void)show;
+ (void)showWithPane:(id)arg1;
+ (void)showWithPane:(id)arg1 selectedObject:(id)arg2;
+ (id)windowNibName;
+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSString *currentPaneIdentifier; // @synthesize currentPaneIdentifier;
- (void)onToolbarItemClicked:(id)arg1;
- (void)createToolbar;
- (void)showPreferencePane:(id)arg1 shouldAnimate:(BOOL)arg2;
- (void)showPreferencePane:(id)arg1 shouldAnimate:(BOOL)arg2 selectedObject:(id)arg3;
- (id)toolbarSelectableItemIdentifiers:(id)arg1;
- (id)toolbar:(id)arg1 itemForItemIdentifier:(id)arg2 willBeInsertedIntoToolbar:(BOOL)arg3;
- (id)toolbarDefaultItemIdentifiers:(id)arg1;
- (id)toolbarAllowedItemIdentifiers:(id)arg1;
- (void)cancel:(id)arg1;
- (id)windowWillReturnFieldEditor:(id)arg1 toObject:(id)arg2;
- (BOOL)windowShouldClose:(id)arg1;
- (void)windowDidLoad;
- (void)window:(id)arg1 willEncodeRestorableState:(id)arg2;
- (void)window:(id)arg1 didDecodeRestorableState:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)awakeFromNib;
- (void)dealloc;
@property(readonly, retain, nonatomic) DUIFeatures *features;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

