//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString, NSText, NSView;

@protocol PLPrefsPaneController <NSObject>
- (void)setSelectedObject:(id)arg1;
- (NSView *)view;
- (NSImage *)icon;
- (NSString *)label;
- (NSString *)identifier;

@optional
- (BOOL)windowShouldClose:(id)arg1;
- (NSText *)fieldEditorForObject:(id)arg1;
@end

