//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLBaseVMCreationAssistant.h"

@class DUIOpenedVM;

@interface PLPreprocessedVMAssistant : PLBaseVMCreationAssistant
{
    DUIOpenedVM *mOpenedVM;
}

@property(retain, nonatomic) DUIOpenedVM *openedVM; // @synthesize openedVM=mOpenedVM;
- (void)finishCreation;
- (id)resultID;
- (id)resultBundleURL;
- (void)configureDetailView;
- (void)configureFinishView;
- (void)prepareForApplicationTerminationWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (BOOL)canApplicationTerminate;
- (void)finish;
- (void)dealloc;

@end

