//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMOneShotWindowController.h"

#import "DUIApplicationTerminationDelegate.h"

@class DUIDlgMgr, DUIInventoryFolderNode, DUIInventoryVMNode, DUIOVFTool, DUIOpenedVM, DUIVMUploader, DUIWeakRef, NSArray, NSArrayController, NSButton, NSImage, NSOutlineView, NSString, NSTabView, NSTableView, NSTreeController;

@interface PLRemoteCnxUploadChooser : VMOneShotWindowController <DUIApplicationTerminationDelegate>
{
    NSTabView *tabView;
    NSArrayController *serversController;
    NSTreeController *foldersController;
    NSArrayController *hostsController;
    NSArrayController *datastoresController;
    NSTableView *serversTableView;
    NSOutlineView *foldersOutlineView;
    NSTableView *hostsTableView;
    NSTableView *datastoresTableView;
    NSButton *foldersContinueButton;
    BOOL mHideBackButton;
    BOOL misVIMCnxType;
    BOOL _isConnecting;
    DUIInventoryFolderNode *mFolder;
    DUIInventoryVMNode *mNode;
    NSArray *mInventories;
    NSArray *mHostNodes;
    DUIWeakRef *mWeakDlgMgr;
    NSString *mVMName;
    NSImage *mDatastoreIcon;
    DUIOpenedVM *mOpenedVM;
    DUIDlgMgr *mWindowDlgMgr;
    id mInventoryChangeObserver;
    DUIOVFTool *mOVFTool;
    DUIVMUploader *mVMUploader;
}

+ (id)windowNibName;
+ (void)showChooserWithNode:(id)arg1 folder:(id)arg2 dlgMgr:(id)arg3;
@property(nonatomic) BOOL isConnecting; // @synthesize isConnecting=_isConnecting;
@property(retain, nonatomic) DUIVMUploader *vmUploader; // @synthesize vmUploader=mVMUploader;
@property(retain, nonatomic) DUIOVFTool *ovfTool; // @synthesize ovfTool=mOVFTool;
@property(nonatomic) BOOL isVIMCnxType; // @synthesize isVIMCnxType=misVIMCnxType;
@property(retain, nonatomic) id inventoryChangeObserver; // @synthesize inventoryChangeObserver=mInventoryChangeObserver;
@property(retain, nonatomic) DUIDlgMgr *windowDlgMgr; // @synthesize windowDlgMgr=mWindowDlgMgr;
@property(retain, nonatomic) DUIOpenedVM *openedVM; // @synthesize openedVM=mOpenedVM;
@property(nonatomic) BOOL hideBackButton; // @synthesize hideBackButton=mHideBackButton;
@property(retain, nonatomic) NSImage *datastoreIcon; // @synthesize datastoreIcon=mDatastoreIcon;
@property(retain, nonatomic) NSString *vmName; // @synthesize vmName=mVMName;
@property(retain, nonatomic) DUIWeakRef *weakDlgMgr; // @synthesize weakDlgMgr=mWeakDlgMgr;
@property(retain, nonatomic) NSArray *hostNodes; // @synthesize hostNodes=mHostNodes;
@property(retain, nonatomic) NSArray *inventories; // @synthesize inventories=mInventories;
@property(retain, nonatomic) DUIInventoryVMNode *node; // @synthesize node=mNode;
@property(retain, nonatomic) DUIInventoryFolderNode *folder; // @synthesize folder=mFolder;
- (void)prepareForApplicationTerminationWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL canApplicationTerminate;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)choose:(id)arg1;
- (void)showUploadHelp:(id)arg1;
- (void)onRefresh:(id)arg1;
- (void)goBack:(id)arg1;
- (void)goBackToServers:(id)arg1;
- (void)goForwardFromFolders:(id)arg1;
- (id)uploadFolder;
- (void)setUploadFolder:(id)arg1;
- (void)configureWithInventory:(id)arg1;
- (void)goForwardWithInventory:(id)arg1;
- (void)goForwardFromServers:(id)arg1;
- (void)loadInventories;
- (void)loadDatastoresForInventory:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)windowDidLoad;
- (void)configureContents;
- (id)dlgMgr;
- (void)dealloc;

@end

