//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

#import "NSTableViewDelegate.h"

@class DUIHostInfo, NSArray, NSArrayController, NSImage, NSString, NSTableView, PLRemoteVMCreationAssistant;

@interface PLRemoteDatastoreAssistantPanel : PLAssistantPanelController <NSTableViewDelegate>
{
    NSArrayController *hostsController;
    NSArrayController *datastoresController;
    NSTableView *hostsTableView;
    NSTableView *datastoresTableView;
    BOOL mDidAwakeFromNib;
    NSArray *mHostNodes;
    NSImage *mDatastoreIcon;
    DUIHostInfo *mHostInfo;
}

+ (id)observationKeyPaths;
@property(retain, nonatomic) DUIHostInfo *hostInfo; // @synthesize hostInfo=mHostInfo;
@property(nonatomic) NSArrayController *hostsController; // @synthesize hostsController;
@property(nonatomic) BOOL didAwakeFromNib; // @synthesize didAwakeFromNib=mDidAwakeFromNib;
@property(retain, nonatomic) NSImage *datastoreIcon; // @synthesize datastoreIcon=mDatastoreIcon;
@property(retain, nonatomic) NSArray *hostNodes; // @synthesize hostNodes=mHostNodes;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)loadDatastoresForCnx:(id)arg1 host:(id)arg2;
- (id)dsInfo;
- (id)hostNode;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)resetView;
- (void)configureView;
- (void)assistantWillUnload;
- (void)assistantWillStart;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, nonatomic) PLRemoteVMCreationAssistant *assistant; // @dynamic assistant;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

