//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable;

@interface PLRestrictedVMWindowMgr : NSObject
{
    NSMapTable *mRvmWindows;
}

+ (void)teardownSharedRestrictedVMWindowMgr;
+ (id)sharedRestrictedVMWindowMgr;
@property(retain, nonatomic) NSMapTable *rvmWindows; // @synthesize rvmWindows=mRvmWindows;
- (void)closeWindows;
- (void)rvmWindowClosing:(id)arg1;
- (void)dealloc;
- (id)showRestrictedVMInventoryForCnx:(id)arg1;
- (id)init;

@end

