//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsWindowController.h"

#import "PLContent.h"

@class NSString, PLWindowedSession;

@interface PLSettingsWindowController : DUISettingsWindowController <PLContent>
{
    PLWindowedSession *mSession;
}

@property(readonly, retain, nonatomic) PLWindowedSession *session; // @synthesize session=mSession;
- (id)windowTitle;
- (BOOL)canSessionCloseForTermination:(BOOL)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)prepareToCloseContentWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

