//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemBase.h"

#import "VMSettingsOutlineTarget.h"

@class DUIFeatures, NSDictionary, NSLayoutConstraint, NSOutlineView, NSString, NSTextView, VMSettingsOutlineDictionary;

@interface PLSettingsItemAdvanced : DUISettingsItemBase <VMSettingsOutlineTarget>
{
    NSTextView *detailView;
    NSOutlineView *outlineView;
    NSLayoutConstraint *outlineHeightConstraint;
    VMSettingsOutlineDictionary *outlineData;
    double preferredViewHeight;
    NSDictionary *mOutlineDictionary;
    DUIFeatures *mDuiFeatures;
}

+ (id)keyPathsAffectingSettingsValueForKey:(id)arg1;
@property(retain, nonatomic) DUIFeatures *duiFeatures; // @synthesize duiFeatures=mDuiFeatures;
@property(retain, nonatomic) NSDictionary *outlineDictionary; // @synthesize outlineDictionary=mOutlineDictionary;
@property(nonatomic) double preferredViewHeight; // @synthesize preferredViewHeight;
@property(retain) VMSettingsOutlineDictionary *outlineData; // @synthesize outlineData;
- (id)warnings;
- (BOOL)isVBSSettingItemVisible;
- (void)setNilValueForKey:(id)arg1;
- (id)vmSettingsOutlineDictionary;
- (id)rawDiskRequiresAuthenticationStrings;
- (void)setRawDiskRequiresAuthentication:(int)arg1;
- (int)rawDiskRequiresAuthentication;
- (id)hardDiskHostBufferStateStrings;
- (id)monitorTypeStrings;
- (id)firmwareTypeStrings;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)canEditProperty:(id)arg1;
- (id)powerStringsForPopup:(id)arg1;
- (id)powerStringsForState:(int)arg1;
- (void)setUseHardPowerReset:(BOOL)arg1;
- (BOOL)useHardPowerReset;
- (void)setUseHardPowerSuspend:(BOOL)arg1;
- (BOOL)useHardPowerSuspend;
- (void)setUseHardPowerOff:(BOOL)arg1;
- (BOOL)useHardPowerOff;
- (void)setUseHardPowerOn:(BOOL)arg1;
- (BOOL)useHardPowerOn;
- (void)setFirmwareMode:(int)arg1;
- (int)firmwareMode;
- (BOOL)validateVncPort:(id *)arg1 error:(id *)arg2;
- (BOOL)validateVncPassword:(id *)arg1 error:(id *)arg2;
- (void)setVncPassword:(id)arg1;
- (id)vncPassword;
- (BOOL)hasVNCKey;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)closeView;
- (void)openView;
- (BOOL)canHWSupportSecureBoot;
- (BOOL)powerResetOptionSupported;
- (void)setPowerResetOption:(int)arg1;
- (int)powerResetOption;
- (BOOL)powerSuspendOptionSupported;
- (void)setPowerSuspendOption:(int)arg1;
- (int)powerSuspendOption;
- (BOOL)powerOnOptionSupported;
- (void)setPowerOnOption:(int)arg1;
- (int)powerOnOption;
- (BOOL)powerOffOptionSupported;
- (void)setPowerOffOption:(int)arg1;
- (int)powerOffOption;
- (BOOL)macOSXHardDiskHostBufferStateSupported;
- (void)setMacOSXHardDiskHostBufferState:(int)arg1;
- (int)macOSXHardDiskHostBufferState;
- (BOOL)monitorTypeSupported;
- (void)setMonitorType:(int)arg1;
- (int)monitorType;
- (BOOL)vncPortSupported;
- (void)setVncPort:(int)arg1;
- (int)vncPort;
- (BOOL)isVncEnabledSupported;
- (void)setIsVncEnabled:(BOOL)arg1;
- (BOOL)isVncEnabled;
- (BOOL)isVBSEnabledSupported;
- (void)setIsVBSEnabled:(BOOL)arg1;
- (BOOL)isVBSEnabled;
- (BOOL)isSecureBootEnabledSupported;
- (void)setIsSecureBootEnabled:(BOOL)arg1;
- (BOOL)isSecureBootEnabled;
- (BOOL)isEfiPresentSupported;
- (void)setIsEfiPresent:(BOOL)arg1;
- (BOOL)isEfiPresent;
- (BOOL)shouldToolsSyncTimeSupported;
- (void)setShouldToolsSyncTime:(BOOL)arg1;
- (BOOL)shouldToolsSyncTime;
- (BOOL)isVirtualBatteryEnabledSupported;
- (void)setIsVirtualBatteryEnabled:(BOOL)arg1;
- (BOOL)isVirtualBatteryEnabled;
- (BOOL)enableUSBAnalyzerSupported;
- (void)setEnableUSBAnalyzer:(BOOL)arg1;
- (BOOL)enableUSBAnalyzer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

