//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemBase.h"

#import "NSTableViewDataSource.h"
#import "PLHotKeyFieldDelegate.h"

@class DUIPerVMHotKey, DUIPrefs, NSButton, NSStackView, NSString, NSTableView, NSView, PLHotKeyField, PLKeyboardProfilesTableDataSource;

@interface PLSettingsItemProfile : DUISettingsItemBase <NSTableViewDataSource, PLHotKeyFieldDelegate>
{
    NSTableView *tableView;
    NSButton *removeButton;
    PLKeyboardProfilesTableDataSource *tableDataSource;
    NSView *profileContainerView;
    NSStackView *stackLayout;
    NSView *profilesView;
    NSView *perVMHotKeysView;
    BOOL _perVMHotKeyConflictsWithSystemHotKey;
    PLHotKeyField *_hotKeyField;
}

+ (id)observationKeyPaths;
+ (id)keyPathsAffectingSettingsValueForKey:(id)arg1;
@property(nonatomic) BOOL perVMHotKeyConflictsWithSystemHotKey; // @synthesize perVMHotKeyConflictsWithSystemHotKey=_perVMHotKeyConflictsWithSystemHotKey;
@property(nonatomic) PLHotKeyField *hotKeyField; // @synthesize hotKeyField=_hotKeyField;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)updateButtons;
- (void)updateHotKeysView;
- (void)onProfileChanged:(id)arg1;
- (id)duiFeatures;
- (void)closeView;
- (void)openView;
- (void)onMakeDefaultProfile:(id)arg1;
- (void)onRename:(id)arg1;
- (void)onDuplicate:(id)arg1;
- (void)onEdit:(id)arg1;
- (void)onRemove:(id)arg1;
- (void)onAdd:(id)arg1;
@property(readonly, copy, nonatomic) NSString *macOSShortcutsState;
@property(readonly, copy, nonatomic) NSString *languageSpecificState;
- (id)stringForEnabledState:(BOOL)arg1;
- (BOOL)validateHotKey:(id)arg1;
- (void)hotKeyFieldDidClear:(id)arg1;
- (void)hotKeyField:(id)arg1 didReceiveHotKey:(id)arg2;
@property(readonly, retain, nonatomic) DUIPerVMHotKey *perVMHotKey;
- (void)showPerVMHotKeyConfirmationAlertForHotKey:(id)arg1;
@property(readonly, nonatomic) BOOL canEnablePerVMHotKeys;
@property(readonly, nonatomic) BOOL perVMHotKeysIsEnabled;
@property(readonly, nonatomic) BOOL perVMHotKeysIsHidden;
@property(readonly, nonatomic) DUIPrefs *prefs;
- (id)warnings;
@property(readonly, copy, nonatomic) NSString *profileName;
@property(readonly, copy, nonatomic) NSString *profileType;
- (id)currentProfile;
- (id)keyboardAndMousePreferences;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

