//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DUIWeakRef, NSMutableArray;

@interface PLSessionMgr : NSObject
{
    NSMutableArray *mAllSessions;
    DUIWeakRef *mWeakUnitySessionRef;
}

+ (id)sharedSessionMgr;
@property(retain, nonatomic) DUIWeakRef *weakUnitySessionRef; // @synthesize weakUnitySessionRef=mWeakUnitySessionRef;
@property(retain, nonatomic) NSMutableArray *allSessions; // @synthesize allSessions=mAllSessions;
- (void)unregisterSession:(id)arg1;
- (void)registerSession:(id)arg1;
- (void)closeVMWithID:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)iterateCloseVMWithID:(id)arg1 sessions:(id)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (BOOL)canShowWindowsForVMWithID:(id)arg1;
- (void)showSettingsForVMWithID:(id)arg1 forItemWithKey:(id)arg2;
- (void)showSnapshotsForVMWithID:(id)arg1;
- (void)showWindowsForVMWithID:(id)arg1;
- (void)showWindowsForVMWithID:(id)arg1 allWindows:(BOOL)arg2;
- (void)showWindowsForVMWithID:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3 allWindows:(BOOL)arg4;
- (void)openVMSessionForVMWithID:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)showLibrarySessionWithInventory:(id)arg1;
- (id)findSessionForVMWithID:(id)arg1 excludingSession:(id)arg2;
- (id)findSessionForVMWithID:(id)arg1;
- (id)findVMSessionForVMWithID:(id)arg1;
- (void)setLastUsedViewMode:(int)arg1 forVMWithID:(id)arg2;
- (int)lastUsedViewModeForVMWithID:(id)arg1;
- (void)terminateAllSessions;
- (void)loadInitialSessions;
- (id)nodesToPowerOnAtStartup;
- (id)startMenuSession;
- (id)openLibrarySession;
- (id)currentLibrarySession;
- (id)responderSession;
- (void)updateUnitySession:(id)arg1;
- (id)unitySession;
- (id)fallbackUnitySession;
- (id)sessionForMainWindow;
- (id)sessionForWindow:(id)arg1;
- (void)dealloc;

@end

