//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PLSessionWindowMenu : NSObject
{
}

+ (id)sharedSessionWindowMenu;
- (id)nonSessionWindowMenuItemsFromMenu:(id)arg1;
- (BOOL)addSessionWindowsMenusToMenu:(id)arg1 addInitialSeparator:(BOOL)arg2 attachGuestAppsMenu:(BOOL)arg3;
- (void)onSelectSession:(id)arg1;
- (void)showWindowFromDock:(id)arg1;
- (void)updateWindowsMenu:(id)arg1;
- (id)applicationDockMenu:(id)arg1;

@end

