//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUISettingsItemBase.h"

@class NSButton, NSMutableArray, NSTableView, NSWindow;

@interface PLSettingsItemApplicationsMenu : DUISettingsItemBase
{
    NSMutableArray *pinnedAppsArray;
    NSTableView *pinnedAppsTableView;
    NSButton *removePinnedAppButton;
    NSWindow *appListWindow;
    NSTableView *appListTableView;
    NSButton *appListAddButton;
    NSMutableArray *pinnableAppsArray;
    BOOL commitPending;
}

- (void)shouldCloseViewWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (BOOL)canCloseView;
- (BOOL)tableView:(id)arg1 acceptDrop:(id)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (unsigned long long)tableView:(id)arg1 validateDrop:(id)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (BOOL)tableView:(id)arg1 writeRowsWithIndexes:(id)arg2 toPasteboard:(id)arg3;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)appListWindowCancel:(id)arg1;
- (void)appListWindowAdd:(id)arg1;
- (void)onPinnedAppsListChanged:(id)arg1;
- (void)clearRecentApplications:(id)arg1;
- (void)removePinnedApplication:(id)arg1;
- (void)addPinnedApplication:(id)arg1;
- (void)addItemsFromArray:(id)arg1 toArray:(id)arg2;
- (void)updatePinnableAppsArray;
- (void)updatePinnedAppsArray;
- (void)updateButtons;
- (void)dealloc;
- (void)awakeFromNib;
- (id)guestAppList;
- (id)proxyAppMgr;

@end

