//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DUIApplicationTerminationDelegate.h"
#import "NSWindowRestoration.h"

@class NSString, PLVMController;

@interface PLSession : NSObject <DUIApplicationTerminationDelegate, NSWindowRestoration>
{
    BOOL mAppWillTerminate;
    BOOL mIsOpen;
    PLVMController *mActiveVMController;
}

+ (void)restoreWindowWithIdentifier:(id)arg1 state:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(nonatomic) BOOL isOpen; // @synthesize isOpen=mIsOpen;
@property(nonatomic) BOOL appWillTerminate; // @synthesize appWillTerminate=mAppWillTerminate;
@property(retain, nonatomic) PLVMController *activeVMController; // @synthesize activeVMController=mActiveVMController;
@property(readonly, copy) NSString *description;
- (void)prepareForApplicationTerminationWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL canApplicationTerminate;
- (void)closeSessionWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)closeSession;
- (BOOL)canSessionCloseForTermination:(BOOL)arg1;
- (void)prepareToCloseWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)prepareToCloseContents:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)closeContent:(id)arg1;
@property(readonly, nonatomic) BOOL isTerminating;
- (double)closeSessionTimeDelay;
- (void)closeVMWithID:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (void)updateViewMode:(int)arg1 forVMController:(id)arg2;
- (void)updateViewMode:(int)arg1 forVMController:(id)arg2 withRetryCount:(int)arg3;
- (id)actionController;
- (id)allLayersAndContents;
@property(readonly, nonatomic) int sessionType;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

