//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLSessionWindowController.h"

//#import "PLContent.h"

@class DUIDlgMgr, NSString, PLVMController;

@interface PLSessionAuxWindowController : PLSessionWindowController //<PLContent>
{
    PLVMController *mVMController;
    DUIDlgMgr *mDlgMgr;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(readonly, retain, nonatomic) PLVMController *vmController; // @synthesize vmController=mVMController;
@property(readonly, retain, nonatomic) DUIDlgMgr *dlgMgr; // @synthesize dlgMgr=mDlgMgr;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)prepareToCloseContentWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (BOOL)canSessionCloseForTermination:(BOOL)arg1;
- (id)windowTitle;
- (void)configureWindow;
- (void)close;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1 withSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

