//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSMenu, NSString;

@protocol PLSnapshotDataSource
- (void)dataSourcePerformTakeActionForItem:(id)arg1 name:(NSString *)arg2 description:(NSString *)arg3;
- (BOOL)dataSourceShowInfoButtonForItem:(id)arg1;
- (void)dataSourcePerformInfoActionForItem:(id)arg1;
- (void)dataSourcePerformDefaultActionForItems:(NSArray *)arg1;
- (void)dataSourceCloseInfoViewForItem:(id)arg1;
- (void)dataSourceKeepItem:(id)arg1;
- (void)dataSourceDeleteItems:(NSArray *)arg1;
- (void)dataSourceRevertItem:(id)arg1;
- (NSMenu *)dataSourceContextMenuForItem:(id)arg1;
- (int)dataSourceSnapshotCount;
- (void)dataSourceSelectionDidChange;
- (BOOL)dataSourceCanExtendSelectionForItem:(id)arg1;
- (BOOL)dataSourceShouldSelectItem:(id)arg1;
- (BOOL)dataSourceShouldEndEditField:(int)arg1 ofItem:(id)arg2 objectValue:(id)arg3 reason:(int)arg4;
- (BOOL)dataSourceShouldEditField:(int)arg1 ofItem:(id)arg2;
- (void)dataSourceSetValue:(id)arg1 forField:(int)arg2 ofItem:(id)arg3;
- (id)dataSourceValueForField:(int)arg1 ofItem:(id)arg2;
- (long long)dataSourceNumberOfChildrenOfItem:(id)arg1;
- (id)dataSourceChild:(long long)arg1 ofItem:(id)arg2;
- (BOOL)disableActions;
@end

