//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class DUIProgress, NSObject<PLSnapshotProgressViewDelegate>, NSViewController;

@interface PLSnapshotProgressView : NSView
{
    DUIProgress *progress;
    NSViewController *viewController;
    NSObject<PLSnapshotProgressViewDelegate> *delegate;
}

@property NSObject<PLSnapshotProgressViewDelegate> *delegate; // @synthesize delegate;
@property(retain, nonatomic) NSViewController *viewController; // @synthesize viewController;
@property(retain, nonatomic) DUIProgress *progress; // @synthesize progress;
- (void)performLayout;
- (void)onProgressDone:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)addProgress:(id)arg1 withViewController:(id)arg2;

@end

