//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "PLPrefsPaneController.h"

@class NSMenu, NSMutableArray, NSStackView, NSString, NSView, NSWindow;

@interface PLURLHandlingPrefsPaneController : NSViewController <PLPrefsPaneController>
{
    NSStackView *containerView;
    NSWindow *addProtocolSheet;
    NSMenu *protocolMenu;
    NSView *noTemplateView;
    NSMutableArray *handlerViews;
}

+ (id)prefPaneIdentifier;
- (id)handlerViewTemplateForTag:(int)arg1;
- (id)handlerViewTemplateForProtocols:(id)arg1;
- (void)addNoTemplateView;
- (void)updatePrefs;
- (id)knownProtocolsForProtocols:(id)arg1;
- (id)knownProtocolForTag:(id)arg1;
- (id)allKnownProtocols;
- (void)addTemplateForKnownTag:(id)arg1 enabled:(BOOL)arg2;
- (void)addTemplateForName:(id)arg1 protocols:(id)arg2 knownProtocolsTag:(id)arg3 enabled:(BOOL)arg4;
- (void)addTemplateWithProperties:(id)arg1;
- (void)addTemplate:(id)arg1;
- (void)rebuildKnownProtocolsMenu;
- (void)loadHandlers;
- (id)handlersToPush;
- (void)onAddProtocols:(id)arg1;
- (void)resetDefaults:(id)arg1;
- (void)removeTemplate:(id)arg1;
- (void)setSelectedObject:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)icon;
- (id)label;
- (id)identifier;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

