//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIProgress, PLVM;

@interface PLVMProgressHandler : NSObject
{
    PLVM *mVM;
    DUIProgress *mActiveProgress;
}

@property(retain, nonatomic) DUIProgress *activeProgress; // @synthesize activeProgress=mActiveProgress;
@property(nonatomic) PLVM *vm; // @synthesize vm=mVM;
- (void)addProgressToActivityViewer:(id)arg1;
- (BOOL)redisplayProgressIfNeeded:(id)arg1;
- (void)onProgressDone:(id)arg1;
- (void)onNewProgress:(id)arg1;
- (id)newestBlockingProgress;
- (void)dealloc;
- (id)initWithVM:(id)arg1;

@end

