//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSView.h"

//#import "DUIMKSChromeDelegate.h"
//#import "NSTextFieldDelegate.h"

@class DUIMKSChrome, DUIProgress, NSArray, NSBox, NSButton, NSImage, NSImageView, NSNumber, NSProgressIndicator, NSString, NSTextField, PLVMController;

@interface PLVMSnapshotNodeView : NSView //<DUIMKSChromeDelegate, NSTextFieldDelegate>
{
    DUIMKSChrome *mksChrome;
    NSBox *selectionBox;
    NSString *name;
    id status;
    DUIProgress *progress;
    int powerState;
    NSArray *screenshots;
    BOOL isOnTrunk;
    BOOL isCurrentState;
    NSImage *badgeImage;
    PLVMSnapshotNodeView *parentNode;
    NSArray *childNodes;
    //id <PLVMSnapshotNodeViewDelegate> delegate;
    id delegate;
    BOOL isSelected;
    BOOL needsLayout;
    BOOL imagesChanged;
    BOOL shouldAnimateScreenshot;
    BOOL endEditingPending;
    BOOL isNameEditable;
    struct CGRect statusFrame;
    struct CGRect nameFrame;
    struct CGRect animationTargetFrame;
    NSTextField *editingField;
    NSProgressIndicator *progressIndicator;
    long long trackingRectTag;
    BOOL hasMouse;
    BOOL isEditingName;
    NSButton *infoButton;
    NSImageView *hasClonesImage;
    double aspectRatio;
    BOOL isNextAutoProtect;
    BOOL mHasClones;
    BOOL mIsPerformingLayout;
    NSNumber *mTimestamp;
    PLVMController *mVMController;
}

+ (id)observationKeyPaths;
@property(nonatomic) BOOL isPerformingLayout; // @synthesize isPerformingLayout=mIsPerformingLayout;
@property(nonatomic) double aspectRatio; // @synthesize aspectRatio;
@property(nonatomic) struct CGRect animationTargetFrame; // @synthesize animationTargetFrame;
@property(nonatomic) BOOL isEditingName; // @synthesize isEditingName;
@property(nonatomic) BOOL isNameEditable; // @synthesize isNameEditable;
@property(retain, nonatomic) NSArray *childNodes; // @synthesize childNodes;
@property(retain, nonatomic) PLVMSnapshotNodeView *parentNode; // @synthesize parentNode;
@property(retain, nonatomic) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
@property(retain, nonatomic) NSTextField *editingField; // @synthesize editingField;
@property(retain, nonatomic) DUIMKSChrome *mksChrome; // @synthesize mksChrome;
@property(nonatomic) BOOL isSelected; // @synthesize isSelected;
@property(nonatomic) id  delegate;
//@property(nonatomic) id <PLVMSnapshotNodeViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSImage *badgeImage; // @synthesize badgeImage;
@property(nonatomic) BOOL hasClones; // @synthesize hasClones=mHasClones;
@property(nonatomic) BOOL isNextAutoProtect; // @synthesize isNextAutoProtect;
@property(nonatomic) BOOL isCurrentState; // @synthesize isCurrentState;
@property(nonatomic) BOOL isOnTrunk; // @synthesize isOnTrunk;
@property(retain, nonatomic) PLVMController *vmController; // @synthesize vmController=mVMController;
@property(retain, nonatomic) NSArray *screenshots; // @synthesize screenshots;
@property(nonatomic) int powerState; // @synthesize powerState;
@property(retain, nonatomic) DUIProgress *progress; // @synthesize progress;
@property(retain, nonatomic) NSNumber *timestamp; // @synthesize timestamp=mTimestamp;
@property(retain, nonatomic) id status; // @synthesize status;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void)onWindowDidResignKey:(id)arg1;
- (void)onWindowDidBecomeKey:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)removeTrackingRect;
- (void)updateTrackingRect:(id)arg1;
- (struct CGRect)trackingRect;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (id)droppedFileBasenameTemplateForMKSChrome:(id)arg1;
- (BOOL)allowInteractionWithMKSChrome:(id)arg1;
- (id)menuForEvent:(id)arg1 mksChrome:(id)arg2;
- (void)mouseClick:(id)arg1 forMKSChrome:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)openInfoPanel:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (id)attributedStatusStringForWidth:(double)arg1;
- (id)attributedNameString;
- (void)performLayout;
- (void)setNeedsLayout:(BOOL)arg1;
- (void)onVMControllerChanged;
- (void)onProgressDone:(id)arg1;
- (void)onIsCancellableChanged;
- (void)onPercentChanged;
- (void)forceLayout;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)screenshotView;
- (struct CGRect)screenRectForScreenshot;
- (id)dictionaryForAnimation;
- (void)beginEditingName;
- (struct CGRect)nameEditorFrame;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (id)accessibilityFocusedUIElement;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityRoleDescription;
- (id)accessibilityDescription;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

