//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class DUIMKSChrome, NSArray, NSLayoutConstraint;

@interface PLVMUnityConsoleTabView : NSView
{
    id delegate;
    DUIMKSChrome *mksChrome;
    NSLayoutConstraint *tabAreaHeight;
    long long mSelectedTabIndex;
    NSArray *mTabButtons;
}

@property(retain, nonatomic) NSArray *tabButtons; // @synthesize tabButtons=mTabButtons;
@property(nonatomic) long long selectedTabIndex; // @synthesize selectedTabIndex=mSelectedTabIndex;
@property(readonly, nonatomic) DUIMKSChrome *mksChrome; // @synthesize mksChrome;
@property(nonatomic) id delegate; // @synthesize delegate;
- (void)onTabButtonClicked:(id)arg1;
- (void)dealloc;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)updateConstraints;
- (void)layout;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawBorderLinesInRect:(struct CGRect)arg1 excluding:(struct CGRect)arg2;
- (void)drawTabForFrame:(struct CGRect)arg1 index:(long long)arg2;
- (void)drawRightEdge:(struct CGRect)arg1 radius:(double)arg2;
- (void)drawLeftEdge:(struct CGRect)arg1 radius:(double)arg2;
- (void)reloadTabs;
- (void)switchToTabAtIndex:(int)arg1;
- (void)awakeFromNib;

@end

