//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIDlgMgr, NSView, PLVMSettingsTransactionHelper;

@protocol PLVMSettingsTransactionHelperDelegate <NSObject>
- (void)onValidateAndApplyDone:(int)arg1 forTransactionHelper:(PLVMSettingsTransactionHelper *)arg2;
- (NSView *)viewForTransactionHelper:(PLVMSettingsTransactionHelper *)arg1;
- (DUIDlgMgr *)dlgMgr;
@end

