//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

#import "NSTableViewDelegate.h"

@class NSArray, NSArrayController, NSString, NSTableView;

@interface PLVMCreationAssistantChooseServerPanel : PLAssistantPanelController <NSTableViewDelegate>
{
    NSArrayController *serversController;
    NSTableView *serversTableView;
    NSArray *mInventories;
    id mInventoryChangeObserver;
}

@property(retain, nonatomic) id inventoryChangeObserver; // @synthesize inventoryChangeObserver=mInventoryChangeObserver;
@property(retain, nonatomic) NSArray *inventories; // @synthesize inventories=mInventories;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)selectedCnx;
- (void)configureView;
- (void)resetView;
- (void)loadInventories;
- (void)assistantWillStart;
- (void)dealloc;
- (id)initWithAssistant:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

