//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

@class DUISupportedHardwareVersion, NSArray, NSPopUpButton, NSTableView, PLVMCreationAssistant;

@interface PLVMCreationAssistantHWVersionPanel : PLAssistantPanelController
{
    NSPopUpButton *hwVersionButton;
    NSTableView *productsTableView;
    NSTableView *limitsTableView;
    DUISupportedHardwareVersion *mHardwareVersionInfo;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) DUISupportedHardwareVersion *hardwareVersionInfo; // @synthesize hardwareVersionInfo=mHardwareVersionInfo;
- (void)updateHWVersionButton;
@property(readonly, copy, nonatomic) NSArray *featureRestrictions;
@property(readonly, copy, nonatomic) NSArray *productCompatNames;
- (void)changeHardwareVersionInfo:(id)arg1;
- (id)hardwareVersionInfo:(int)arg1;
- (void)configureView;
- (id)initWithAssistant:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) PLVMCreationAssistant *assistant; // @dynamic assistant;

@end

