//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "PLInfoViewController.h"

@class NSButton, NSLayoutConstraint, NSTextField, PLAlertAccessoryTableViewController, VMStackLayoutView;

@interface PLVMSnapshotInfoViewController : NSViewController <PLInfoViewController>
{
    NSTextField *nameTextField;
    NSTextField *statusTextField;
    NSTextField *notesTextField;
    NSTextField *fileSizeTextField;
    NSTextField *linkedCloneTextField;
    NSButton *saveCheckBox;
    NSButton *revertButton;
    NSButton *takeButton;
    NSButton *deleteButton;
    NSButton *keepButton;
    NSButton *doneButton;
    VMStackLayoutView *accessoryViewContainer;
    NSLayoutConstraint *linkedCloneConstraint;
    id mItem;
    id <PLSnapshotDataSource> mDataSource;
    PLAlertAccessoryTableViewController *mAccessory;
    double mLinkedCloneConstraintConstant;
}

@property(nonatomic) double linkedCloneConstraintConstant; // @synthesize linkedCloneConstraintConstant=mLinkedCloneConstraintConstant;
@property(retain, nonatomic) PLAlertAccessoryTableViewController *accessory; // @synthesize accessory=mAccessory;
@property(nonatomic) id <PLSnapshotDataSource> dataSource; // @synthesize dataSource=mDataSource;
@property(retain, nonatomic) id item; // @synthesize item=mItem;
@property(readonly, retain, nonatomic) NSTextField *nameTextField; // @synthesize nameTextField;
- (void)shouldCloseViewWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)updateButtons;
- (void)addClones;
- (void)reloadData;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (void)controlTextDidEndEditing:(id)arg1;
- (int)fieldForControl:(id)arg1;
- (BOOL)endEditing;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onCancel:(id)arg1;
- (void)onDone:(id)arg1;
- (void)onKeep:(id)arg1;
- (void)onDelete:(id)arg1;
- (void)onTake:(id)arg1;
- (void)onRevert:(id)arg1;

@end

