//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

#import "NSOutlineViewDelegate.h"

@class DUIInventory, DUIInventoryFolderNode, NSOutlineView, NSString, NSTreeController, PLRemoteVMCreationAssistant;

@interface PLVMCreationAssistantChooseFolderPanel : PLAssistantPanelController <NSOutlineViewDelegate>
{
    NSOutlineView *foldersOutlineView;
    NSTreeController *foldersController;
    DUIInventory *mInventory;
}

@property(retain, nonatomic) DUIInventory *inventory; // @synthesize inventory=mInventory;
@property(readonly, retain, nonatomic) DUIInventoryFolderNode *selectedFolderNode;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)configureView;
- (void)resetView;
- (void)assistantWillStart;
- (void)dealloc;
- (id)initWithAssistant:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) PLRemoteVMCreationAssistant *assistant; // @dynamic assistant;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

