//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSOpenSavePanelDelegate.h"

@class NSSet, NSString, PLVMOpenHelperAccessoryView, VMButtonGroup;

@interface PLVMDKOpenHelper : NSViewController <NSOpenSavePanelDelegate>
{
    PLVMOpenHelperAccessoryView *openPanelAccessory;
    VMButtonGroup *operationButtonGroup;
    int fileOperation;
    NSSet *setOfVMDKs;
    NSString *restrictedPath;
    NSString *currentPath;
    BOOL sufficientSpaceForCopy;
    long long spaceAvailable;
    long long selectedDiskSize;
    NSString *mCurrentPath;
}

+ (void)initialize;
@property(copy, nonatomic) NSString *currentPath; // @synthesize currentPath=mCurrentPath;
@property long long selectedDiskSize; // @synthesize selectedDiskSize;
@property long long spaceAvailable; // @synthesize spaceAvailable;
@property BOOL sufficientSpaceForCopy; // @synthesize sufficientSpaceForCopy;
@property int fileOperation; // @synthesize fileOperation;
- (id)runModalForDirectory:(id)arg1 excludingSet:(id)arg2 restrictingPath:(id)arg3;
- (id)accessoryView;
- (void)dealloc;
- (void)awakeFromNib;
- (id)init;
- (void)panelSelectionDidChange:(id)arg1;
- (BOOL)panel:(id)arg1 shouldShowFilename:(id)arg2;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

