//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCustomTouchBarItem.h"

#import "NSScrubberDataSource.h"
#import "NSScrubberDelegate.h"
#import "NSScrubberFlowLayoutDelegate.h"

@class NSString;

@interface PLVMFnScrubberBarItem : NSCustomTouchBarItem <NSScrubberDelegate, NSScrubberDataSource, NSScrubberFlowLayoutDelegate>
{
    struct CGSize mItemSize;
}

@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=mItemSize;
- (struct CGSize)scrubber:(id)arg1 layout:(id)arg2 sizeForItemAtIndex:(long long)arg3;
- (void)scrubber:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)scrubber:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsForScrubber:(id)arg1;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

