//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface PLVMScanController : NSObject
{
    BOOL mIsScannning;
    BOOL _showVMLibrary;
    NSMutableArray *mScannedVMs;
    NSMutableArray *mScanPaths;
}

+ (id)sharedScanController;
@property(nonatomic) BOOL showVMLibrary; // @synthesize showVMLibrary=_showVMLibrary;
@property(nonatomic) BOOL isScanning; // @synthesize isScanning=mIsScannning;
@property(retain, nonatomic) NSMutableArray *scanPaths; // @synthesize scanPaths=mScanPaths;
@property(retain, nonatomic) NSMutableArray *scannedVMs; // @synthesize scannedVMs=mScannedVMs;
- (BOOL)isApplicationBundle:(id)arg1;
- (BOOL)shouldShowVMLibrary;
- (BOOL)isValidVMWithURL:(id)arg1;
- (BOOL)scanVMsInDirectory:(id)arg1 into:(id)arg2;
- (void)refreshPowerStateWithNode:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (id)addInventoryNodeWithPath:(id)arg1;
- (void)addIntoInventoryIndividuallySinceIndex:(long long)arg1;
- (void)addVMsIntoInventory;
- (void)scanVMXFiles;
- (void)postUserNotification;
- (void)alertNumberLimitation;
- (void)autoScanLocalVMs;
- (id)loadScanPathsFromUserDefaults;
- (void)saveScanPathsIntoUserDefaults;
- (void)removeScanPathsAtIndexes:(id)arg1;
- (id)addScanPaths:(id)arg1;
@property(readonly, nonatomic) BOOL canScanForVMs;
- (void)dealloc;
- (id)init;

@end

