//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

@class PLVMScanAssistant;

@interface PLVMScanAssistantInteractionPanel : PLAssistantPanelController
{
}


// Remaining properties
@property(readonly, nonatomic) PLVMScanAssistant *assistant; // @dynamic assistant;
@end

