//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIVMActionController.h"

@class DUIInventoryVMNode, PLVMUIActionController;

@interface PLVMActionController : DUIVMActionController
{
    DUIInventoryVMNode *mInventoryNode;
    PLVMUIActionController *mVMUIActionController;
}

+ (id)actionControllerForVMWithID:(id)arg1 node:(id)arg2;
@property(retain, nonatomic) PLVMUIActionController *vmUIActionController; // @synthesize vmUIActionController=mVMUIActionController;
@property(retain, nonatomic) DUIInventoryVMNode *inventoryNode; // @synthesize inventoryNode=mInventoryNode;
- (void)powerOnInUnity;
- (void)vmPowerOnAlt:(id)arg1;
- (void)vmPowerOn:(id)arg1;
- (void)launchGuestApp:(id)arg1;
- (void)runGuestApp:(id)arg1;
- (void)toggleStartUI:(id)arg1;
- (void)toggleShowSystemTray:(id)arg1;
- (void)toggleShowTaskbarInUnityMode:(id)arg1;
- (void)onExportOVF:(id)arg1;
- (void)createCloneLinked:(id)arg1;
- (void)createClone:(id)arg1;
- (void)showSnapshots:(id)arg1;
- (void)showAllWindows:(id)arg1;
- (void)revertToParentSnapshot:(id)arg1;
- (void)takeSnapshot:(id)arg1;
- (void)showVMProcessorsAndRAM:(id)arg1;
- (void)showVMInfo:(id)arg1;
- (void)showSettingsForItemWithKey:(id)arg1;
- (void)showReadmeFiles:(id)arg1;
- (void)doShowSettingsForItemWithKey:(id)arg1;
- (BOOL)doShowReadmeFiles;
- (void)showVMSettings:(id)arg1;
- (BOOL)validateSelector:(SEL)arg1;
- (id)accessibilityDescriptionForAction:(SEL)arg1 from:(id)arg2;
- (BOOL)activateAppForAction:(SEL)arg1 from:(id)arg2;
- (id)toolbarSquareImageNameForAction:(SEL)arg1 from:(id)arg2;
- (id)shortLabelForAction:(SEL)arg1 from:(id)arg2;
- (id)tooltipForAction:(SEL)arg1 from:(id)arg2;
- (id)descriptionLabelForAction:(SEL)arg1;
- (id)menuTitleForAction:(SEL)arg1 from:(id)arg2;
- (BOOL)enabledStateForAction:(SEL)arg1 from:(id)arg2;
- (BOOL)canOpenVM;
- (void)openVMWithAbortHandler:(CDUnknownBlockType)arg1 DoneHandler:(CDUnknownBlockType)arg2;
- (void)cancelAutomaticDiskCleanup;
- (id)diskCleanupMgr;
-(void)duiWeakRef;
- (id)nextActionController;
- (void)updateNode:(id)arg1;
- (void)dealloc;
- (id)initWithVMID:(id)arg1 node:(id)arg2;

@end

