//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowDelegate.h"

@class NSCoder, NSWindow;

@protocol PLVMCommonWindowDelegate <NSWindowDelegate>
- (BOOL)restoreWindow:(NSWindow *)arg1 withCoder:(NSCoder *)arg2;
- (void)windowOnActiveSpaceDidChange:(NSWindow *)arg1;
- (BOOL)windowShouldDisableClose:(id)arg1;
- (BOOL)windowShouldToggleFullScreen:(id)arg1;
- (void)window:(NSWindow *)arg1 updateUngrabRect:(struct CGRect)arg2;
@end

