//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class PLVMController, PLVMUnityConsoleTabView;

@interface PLVMUnityConsoleViewController : NSViewController
{
    PLVMUnityConsoleTabView *tabView;
    BOOL mShowLiveMKS;
    PLVMController *mVMController;
}

+ (id)observationKeyPaths;
@property(nonatomic) PLVMUnityConsoleTabView *tabView; // @synthesize tabView;
@property(nonatomic) BOOL showLiveMKS; // @synthesize showLiveMKS=mShowLiveMKS;
@property(retain, nonatomic) PLVMController *vmController; // @synthesize vmController=mVMController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)tabViewSelectionChanged;
- (id)iconOfTabAtIndex:(int)arg1;
- (id)titleOfTabAtIndex:(int)arg1;
- (int)numberOfTabs;
- (void)updateMKSView;
- (id)guestScreens;
- (void)updateSelectedGuestScreen;
- (void)attachToMKS:(BOOL)arg1;
- (void)windowDidChangeOcclusionState:(id)arg1;
- (void)close;
- (void)switchToSingleWindowViewMode:(id)arg1;
- (void)dealloc;
- (id)init;

@end

