//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

//#import "DUIApplicationTerminationDelegate.h"

@class DUIOpenedVM, DUIProgress, DUIVM, NSMutableArray, NSString, NSTimer;

@interface PLVMDiskCleanupManager : NSObject //<DUIApplicationTerminationDelegate>
{
    BOOL _isCanceling;
    BOOL _isTerminating;
    NSMutableArray *mVMConfigPaths;
    DUIProgress *mProgress;
    NSString *_jobVMConfigPath;
    DUIOpenedVM *_openedVM;
    DUIVM *_vm;
    CDUnknownBlockType _onCancelDoneBlock;
    NSTimer *_delayedJobExecutor;
}

@property(retain, nonatomic) NSTimer *delayedJobExecutor; // @synthesize delayedJobExecutor=_delayedJobExecutor;
@property(nonatomic) BOOL isTerminating; // @synthesize isTerminating=_isTerminating;
@property(nonatomic) BOOL isCanceling; // @synthesize isCanceling=_isCanceling;
@property(copy, nonatomic) CDUnknownBlockType onCancelDoneBlock; // @synthesize onCancelDoneBlock=_onCancelDoneBlock;
@property(retain, nonatomic) DUIVM *vm; // @synthesize vm=_vm;
@property(retain, nonatomic) DUIOpenedVM *openedVM; // @synthesize openedVM=_openedVM;
@property(copy, nonatomic) NSString *jobVMConfigPath; // @synthesize jobVMConfigPath=_jobVMConfigPath;
@property(retain, nonatomic) DUIProgress *progress; // @synthesize progress=mProgress;
@property(retain, nonatomic) NSMutableArray *vmConfigPaths; // @synthesize vmConfigPaths=mVMConfigPaths;
- (void)prepareForApplicationTerminationWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) BOOL canApplicationTerminate;
- (void)cancelJobWithVM:(id)arg1;
- (void)cancelJobWithVMID:(id)arg1;
- (void)cancelJobWithConfigPath:(id)arg1;
- (BOOL)isJobRunningWithVM:(id)arg1;
- (BOOL)isJobRunningWithVMID:(id)arg1;
- (BOOL)isJobRunningWithConfigPath:(id)arg1;
- (BOOL)isCurrentJobWithVM:(id)arg1;
- (BOOL)isCurrentJobWithVMID:(id)arg1;
- (BOOL)isCurrentJobWithConfigPath:(id)arg1;
@property(readonly, copy, nonatomic) NSString *jobTooltip;
@property(readonly, nonatomic) unsigned int jobPercent;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)init;
- (void)cancelAllJobs;
- (void)cancelCurrentJob;
- (void)cancelCurrentJobWithDoneHandler:(CDUnknownBlockType)arg1;
- (void)onPowerStateChanged:(id)arg1;
- (void)delayedStartCleanup;
- (void)startCleanup:(id)arg1;
- (void)doStartCleanup;
- (BOOL)shouldStartCleanup;
- (BOOL)hasShrinkableContent;
- (void)doShrinkDiskTree;
- (void)doConsolidate;
- (void)onPercentChanged;
- (void)onDone;
- (void)onAbort:(BOOL)arg1 error:(id)arg2;
- (void)onNext;

@end

