//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLSession.h"

@class DUIInventoryVMNode, DUIOpenedVM, NSArray, NSRunningApplication, NSTimer, NSTreeController, PLInventoryManager, PLVMStartMenuHotKey, PLVMStartMenuProxy;

@interface PLVMStartMenuManager : PLSession
{
    PLInventoryManager *dataSource;
    PLVMStartMenuProxy *startMenuProxy;
    NSTreeController *treeController;
    NSArray *mObservedEntries;
    NSRunningApplication *mStartMenuApp;
    NSRunningApplication *mDockMenuApp;
    NSTimer *mQuitTimer;
    DUIOpenedVM *mOpenedVM;
    unsigned long long mSelectedItemIndex;
    DUIInventoryVMNode *mSelectedItemNode;
    PLVMStartMenuHotKey *mHotKey;
    id mVmPowerStateChangeObserver;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) id vmPowerStateChangeObserver; // @synthesize vmPowerStateChangeObserver=mVmPowerStateChangeObserver;
@property(retain, nonatomic) PLVMStartMenuHotKey *hotKey; // @synthesize hotKey=mHotKey;
@property(retain, nonatomic) DUIInventoryVMNode *selectedItemNode; // @synthesize selectedItemNode=mSelectedItemNode;
@property(nonatomic) unsigned long long selectedItemIndex; // @synthesize selectedItemIndex=mSelectedItemIndex;
@property(retain, nonatomic) DUIOpenedVM *openedVM; // @synthesize openedVM=mOpenedVM;
@property(retain, nonatomic) NSTimer *quitTimer; // @synthesize quitTimer=mQuitTimer;
@property(retain, nonatomic) NSRunningApplication *dockMenuApp; // @synthesize dockMenuApp=mDockMenuApp;
@property(retain, nonatomic) NSRunningApplication *startMenuApp; // @synthesize startMenuApp=mStartMenuApp;
@property(retain, nonatomic) NSArray *observedEntries; // @synthesize observedEntries=mObservedEntries;
- (void)onStartMenuDidClose;
- (void)onStartMenuSelectIndex:(unsigned long long)arg1;
- (void)onStartMenuShowMenuSettings:(id)arg1;
- (void)updateMenu:(id)arg1 forNode:(id)arg2;
- (void)onStartMenuRefresh:(id)arg1;
- (id)nodeFromInfo:(id)arg1;
- (id)menuForNode:(id)arg1;
- (id)builderForNode:(id)arg1;
- (void)onStartMenuPerformAction:(id)arg1 withInfo:(id)arg2;
- (void)closeOpenedVM;
- (void)updateOpenedVM:(id)arg1;
- (id)activeVMController;
- (id)actionController;
- (id)actionControllerForNode:(id)arg1;
- (id)selectedNode;
- (id)activeNodes;
- (void)onLibraryContentUpdated:(id)arg1;
- (unsigned long long)nodeIndexFromVmUUID:(id)arg1;
- (void)onOpenStartMenu:(id)arg1;
- (void)onPowerStateChanged:(id)arg1;
- (void)quitDockMenuApp;
- (void)quitStartMenuApp;
- (void)onQuitTimerDidFire:(id)arg1;
- (void)runDockMenuApp;
- (void)runStartMenuApp;
- (void)runStartMenuAppWithArgument:(id)arg1;
- (BOOL)isDockMenuAppRunning;
- (BOOL)isStartMenuAppRunning;
- (void)delayedUpdateStartMenu;
- (void)updateStartMenu;
- (void)dealloc;
- (void)closeSession;
- (BOOL)canSessionCloseForTermination:(BOOL)arg1;
- (void)prepareToCloseWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)disconnect;
- (id)initWithDataSource:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *predefinedStartMenuShortcuts;
@property(nonatomic) PLVMStartMenuHotKey *startMenuShortcut;
@property(nonatomic) BOOL startMenuShortcutEnabled;
- (BOOL)shouldQuitOnDisconnect;
- (BOOL)shouldStartMenuBeRunning;
- (void)updateLoginItem;
@property(nonatomic) int shouldShowStartMenu;
- (void)closeVMWithID:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (int)sessionType;

@end

