//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLVMLayerWindowed.h"

@class NSArray, NSImage, NSTimer;

@interface PLVMLayerFullScreen : PLVMLayerWindowed
{
    BOOL mUseNameBadge;
    BOOL mIsObservingKeyPaths;
    BOOL mIgnoreAutofitMode;
    int mMappedWindowGroupID;
    NSTimer *mScreenMismatchFitGuestTimer;
    NSImage *mTitleImage;
    NSTimer *mTitleDisplayTimer;
    NSArray *mWindows;
}

+ (id)observationOldKeyPaths;
+ (id)observationKeyPaths;
@property(nonatomic) BOOL ignoreAutofitMode; // @synthesize ignoreAutofitMode=mIgnoreAutofitMode;
@property(retain, nonatomic) NSArray *windows; // @synthesize windows=mWindows;
@property(nonatomic) BOOL isObservingKeyPaths; // @synthesize isObservingKeyPaths=mIsObservingKeyPaths;
@property(nonatomic) BOOL useNameBadge; // @synthesize useNameBadge=mUseNameBadge;
@property(retain, nonatomic) NSTimer *titleDisplayTimer; // @synthesize titleDisplayTimer=mTitleDisplayTimer;
@property(retain, nonatomic) NSImage *titleImage; // @synthesize titleImage=mTitleImage;
@property(retain, nonatomic) NSTimer *screenMismatchFitGuestTimer; // @synthesize screenMismatchFitGuestTimer=mScreenMismatchFitGuestTimer;
@property(nonatomic) int mappedWindowGroupID; // @synthesize mappedWindowGroupID=mMappedWindowGroupID;
- (int)displayMode;
- (void)updateDisplayMode;
@property(readonly, nonatomic) int autofitMode;
- (void)windowDidChangeOcclusionState:(id)arg1;
- (int)viewMode;
- (struct CGRect)preferredContentBoundsForWindow:(id)arg1;
- (id)hostScreensForTopology;
- (void)updateWithWindows:(id)arg1;
- (void)configureMKSChrome:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)prefs;
- (id)features;
- (void)updateWindowGroup;
- (void)titleDisplayTimerFired:(id)arg1;
- (void)windowOnActiveSpaceDidChange:(id)arg1;
- (void)startTitleDisplayTimer;
- (void)synchronizeWindowTitleWithDocumentName;
- (void)updateAllNameImages;
- (BOOL)isPoweredOn;
- (id)generateTitleImage;
- (id)titleForImage;
- (void)onScreenMismatchFitGuestTimer:(id)arg1;
- (id)guestScreens;
- (void)updateMKSScreensWithGuestScreens:(id)arg1;
- (void)mapMKSChrome:(id)arg1 toGuestScreen:(id)arg2;
- (void)onMKSChromeFrameChanged:(id)arg1;
- (void)fitGuestMgr:(id)arg1 didFitGuest:(BOOL)arg2 didTimeOut:(BOOL)arg3 error:(id)arg4 contextInfo:(void *)arg5;
- (void)forceFitGuest;
- (void)fitGuest;
- (id)desiredTopology;
- (void)onVMChangedFrom:(id)arg1;
- (void)close;
- (void)dealloc;
- (id)initWithSession:(id)arg1;

@end

