//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCustomTouchBarItem.h"

@class NSButton;

@interface PLVMPrtScnBarItem : NSCustomTouchBarItem
{
    NSButton *mPrtScnButton;
}

@property(retain, nonatomic) NSButton *prtScnButton; // @synthesize prtScnButton=mPrtScnButton;
- (id)keyboard;
- (void)updateTouchBarItem;
- (void)prtScnAction:(id)arg1;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

@end

