//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DUIVM.h"

@class FUSProxyAppMgr, PLGuestAppMgrDelegate, PLSnapshotController, PLVMEditingBuffer, PLVMProgressHandler;

@interface PLVM : DUIVM
{
    PLGuestAppMgrDelegate *mGuestAppMgrDelegate;
    FUSProxyAppMgr *mProxyAppMgr;
    BOOL mHasShownAntivirusInfo;
    PLSnapshotController *mSnapshotController;
    PLVMEditingBuffer *mEditingBuffer;
    PLVMProgressHandler *mProgressHandler;
}

+ (id)observationKeyPaths;
+ (void)load;
@property(nonatomic) BOOL hasShownAntivirusInfo; // @synthesize hasShownAntivirusInfo=mHasShownAntivirusInfo;
@property(retain, nonatomic) PLVMProgressHandler *progressHandler; // @synthesize progressHandler=mProgressHandler;
@property(retain, nonatomic) PLVMEditingBuffer *editingBuffer; // @synthesize editingBuffer=mEditingBuffer;
@property(retain, nonatomic) PLSnapshotController *snapshotController; // @synthesize snapshotController=mSnapshotController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)onAntivirusAbortAnsweredWithReturnCode:(int)arg1 customPath:(id)arg2;
- (void)installAntivirus;
- (void)onToolsActivate;
- (BOOL)shouldSkipAntivirusCheck;
- (void)onFetchProductAbortWithError:(id)arg1 path:(id)arg2;
- (BOOL)canInstallAntivirus;
- (void)onAntivirusDialogAnswered:(long long)arg1;
- (BOOL)hasAntivirusForGuest;
- (id)antivirusPath;
- (void)prepareVMForDeletion;
- (void)initializeGuestAndProxyAppMgr;
- (id)proxyAppMgr;
- (id)guestAppMgr;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;
- (void)invalidateAdaptation;
- (id)initWithAdaptedVM:(const struct DUIAdaptedVMWrapper *)arg1;

@end

