//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "PLInfoViewController.h"

@class NSButton, NSPopUpButton, NSStepper, NSTextField, NSTimer, PLVMController;

@interface PLVMAutoProtectSettings : NSViewController <PLInfoViewController>
{
    NSPopUpButton *intervalPopUp;
    NSTextField *maximumTextField;
    NSStepper *maximumStepper;
    NSTextField *descriptionTextField;
    NSButton *doneButton;
    NSButton *autoProtectCheckBox;
    int pendingMaximum;
    BOOL pendingCommit;
    BOOL enabled;
    BOOL commitFailed;
    NSTimer *commitTimer;
    id item;
    id <PLSnapshotDataSource> dataSource;
    PLVMController *mVMController;
}

+ (id)observationKeyPaths;
@property(nonatomic) BOOL enabled; // @synthesize enabled;
@property(retain, nonatomic) PLVMController *vmController; // @synthesize vmController=mVMController;
@property(nonatomic) id <PLSnapshotDataSource> dataSource; // @synthesize dataSource;
@property(retain, nonatomic) id item; // @synthesize item;
- (BOOL)control:(id)arg1 didFailToFormatString:(id)arg2 errorDescription:(id)arg3;
- (void)shouldCloseViewWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)updateButtons;
- (void)reloadData;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)buildDescription;
- (void)onCommitTimer:(id)arg1;
- (void)setCommitTimer:(id)arg1;
- (void)commitPendingMaximum;
- (void)onVMControllerChanged;
- (BOOL)endEditing;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onToggleAutoProtect:(id)arg1;
- (void)onDone:(id)arg1;
- (void)onSetMaximum:(id)arg1;
- (void)onSetInterval:(id)arg1;

@end

