//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLVMLayer.h"

@class PLVMUnityConsoleViewController, PLVMUnityController;

@interface PLVMLayerUnity : PLVMLayer
{
    PLVMUnityConsoleViewController *mConsoleViewController;
    BOOL mShouldShowConsole;
    BOOL mShouldForceConsole;
    PLVMUnityController *mUnityController;
    BOOL mIsObservingDlgMgr;
}

+ (id)observationPriorKeyPaths;
+ (id)observationKeyPaths;
@property(nonatomic) BOOL isObservingDlgMgr; // @synthesize isObservingDlgMgr=mIsObservingDlgMgr;
@property(retain, nonatomic) PLVMUnityController *unityController; // @synthesize unityController=mUnityController;
@property(nonatomic) BOOL shouldForceConsole; // @synthesize shouldForceConsole=mShouldForceConsole;
@property(nonatomic) BOOL shouldShowConsole; // @synthesize shouldShowConsole=mShouldShowConsole;
@property(retain, nonatomic) PLVMUnityConsoleViewController *consoleViewController; // @synthesize consoleViewController=mConsoleViewController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateDlgMgrObservers:(id)arg1;
- (void)onDialogManagerDidDisplayDialog:(id)arg1;
- (int)viewMode;
- (void)close;
- (void)layerWillOpen;
- (void)windowDidChangeOcclusionState:(id)arg1;
- (void)updateWithWindows:(id)arg1;
- (struct CGRect)preferredContentBounds;
- (BOOL)shouldHideWindows;
- (void)onShouldShowConsoleChanged;
- (BOOL)needsConsole;
- (void)dealloc;
- (id)initWithSession:(id)arg1;

@end

