//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLAssistantPanelController.h"

@class NSButton, PLBaseVMCreationAssistant<PLChooseFirmware>;

@interface PLVMCreationAssistantChooseFirmwarePanel : PLAssistantPanelController
{
    NSButton *_buttonUEFISecureBoot;
    NSButton *_buttonUEFI;
    NSButton *_buttonBIOS;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)observationKeyPaths;
@property(nonatomic) NSButton *buttonBIOS; // @synthesize buttonBIOS=_buttonBIOS;
@property(nonatomic) NSButton *buttonUEFI; // @synthesize buttonUEFI=_buttonUEFI;
@property(nonatomic) NSButton *buttonUEFISecureBoot; // @synthesize buttonUEFISecureBoot=_buttonUEFISecureBoot;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(nonatomic) BOOL isSecureBootEnabled;
@property(nonatomic) BOOL isEfiPresent;
@property(readonly, nonatomic) BOOL canSupportSecureBoot;
- (void)onSelectFirmwareType:(id)arg1;
- (void)awakeFromNib;
- (id)initWithAssistant:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) PLBaseVMCreationAssistant<PLChooseFirmware> *assistant; // @dynamic assistant;

@end

