//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DUIDeviceNIC, DUIGuestOSInfo, DUIHost, DUIVMCreator, NSArray, NSDictionary, NSString;

@interface PLVMCreationHelper : NSObject
{
    BOOL mHidePasswordField;
    DUIVMCreator *mCreator;
    NSString *mBundlePath;
    NSString *mGuessedOSName;
    DUIDeviceNIC *mDefaultNIC;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) DUIDeviceNIC *defaultNIC; // @synthesize defaultNIC=mDefaultNIC;
@property(copy, nonatomic) NSString *guessedOSName; // @synthesize guessedOSName=mGuessedOSName;
@property(readonly, nonatomic) BOOL hidePasswordField; // @synthesize hidePasswordField=mHidePasswordField;
@property(retain, nonatomic) NSString *bundlePath; // @synthesize bundlePath=mBundlePath;
@property(retain, nonatomic) DUIVMCreator *creator; // @synthesize creator=mCreator;
- (void)saveWithAbortHandler:(CDUnknownBlockType)arg1 doneHandler:(CDUnknownBlockType)arg2;
- (void)createVMBundleAtPath:(id)arg1 abortHandler:(CDUnknownBlockType)arg2 doneHandler:(CDUnknownBlockType)arg3;
- (BOOL)configureCDROMFromProxy:(id)arg1 error:(id *)arg2;
- (BOOL)prepareEasyInstallForCDROMProxy:(id)arg1 error:(id *)arg2;
- (void)removeDefaultNIC;
- (void)addDefaultNIC;
- (id)addNIC;
- (id)addCDROMFromProxy:(id)arg1;
- (void)configureCDROM:(id)arg1 fromProxy:(id)arg2;
- (id)addCDROM;
- (void)validateCDROMs;
- (void)addHardDiskForPath:(id)arg1 preferredBusType:(int)arg2 abortHandler:(CDUnknownBlockType)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (id)addHardDiskForBusType:(int)arg1;
- (id)addHardDisk;
- (void)setTargetVMFolder:(id)arg1;
- (void)configureSharedFolders:(BOOL)arg1;
- (void)configureIntegrationLevel:(BOOL)arg1;
- (id)sfConfig;
@property(readonly, nonatomic) BOOL allowBlankLicense;
@property(readonly, nonatomic) BOOL passwordRequired;
@property(readonly, nonatomic) BOOL hasProductKey;
@property(readonly, nonatomic) BOOL canEditShortName;
- (struct AutoInstallConfigInfo)autoInstallConfig;
- (BOOL)validateGuestPassword:(id *)arg1 error:(id *)arg2;
- (BOOL)validateGuestUsername:(id *)arg1 error:(id *)arg2;
- (BOOL)validateGuestFullname:(id *)arg1 error:(id *)arg2;
- (id)errorForIllegalName:(struct AutoInstallConfigIllegalName)arg1 fieldValue:(id)arg2;
- (id)errorForFieldTooLong:(int)arg1 fieldValue:(id)arg2;
@property(retain, nonatomic) NSString *guestUsername;
@property(retain, nonatomic) NSString *guestPasswordConfirmation;
@property(retain, nonatomic) NSString *guestPassword;
@property(retain, nonatomic) NSString *guestLicenseKey;
@property(retain, nonatomic) NSString *guestFullname;
@property(retain, nonatomic) NSString *guestChosenVariant;
@property(retain, nonatomic) NSString *guestChosenLanguage;
@property(nonatomic) CDStruct_14321004 guessedOSInfo;
@property(nonatomic) BOOL easyInstallSelected;
@property(readonly, nonatomic) BOOL supportedGuest;
@property(readonly, retain, nonatomic) NSDictionary *guestVariants;
@property(readonly, retain, nonatomic) NSArray *guestLanguages;
- (unsigned long long)maxDiskSizeForBusType:(int)arg1;
@property(nonatomic) int hardwareVersion;
@property(retain, nonatomic) NSString *workingDir;
@property(retain, nonatomic) NSString *filename;
@property(retain, nonatomic) NSString *name;
- (void)setInstallationSourceDevice:(id)arg1;
- (void)setMacOSXForceRecoveryModeInstall:(BOOL)arg1;
@property(nonatomic) BOOL isSecureBootEnabled;
@property(nonatomic) BOOL isEfiPresent;
@property(nonatomic) BOOL isSuspendDisabled;
@property(retain, nonatomic) DUIGuestOSInfo *guestOSInfo;
@property(readonly, retain, nonatomic) DUIHost *host;
- (BOOL)isLocalHost;
- (void)setBundleURL:(id)arg1;
- (void)configureEasyInstallPaths;
- (void)setGuestOSSpecificDefaults;
- (void)setVMDefaults;
- (void)dealloc;
- (id)initWithDlgMgr:(id)arg1;
- (id)initWithDlgMgr:(id)arg1 connection:(id)arg2 host:(id)arg3;

@end

