//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLBaseVMCreationAssistant.h"

#import "PLChooseFirmware.h"
#import "PLChooseOSDelegate.h"
#import "PLVMCreationAssistantURLTarget.h"

@class DUIDeviceHardDiskProxy, NSString, PLVMCreationAssistantChooseFirmwarePanel, PLVMCreationAssistantChooseOSPanel, PLVMCreationAssistantChooseVMDKPanel, PLVMCreationAssistantEasyInstallPanel, PLVMCreationAssistantIntegrationPanel, PLVMCreationAssistantLocalInstallMediaPanel, PLVMCreationHelper;

@interface PLVMCreationAssistant : PLBaseVMCreationAssistant <PLVMCreationAssistantURLTarget, PLChooseOSDelegate, PLChooseFirmware>
{
    BOOL mIsSecondaryDisc;
    BOOL mEnableFileSharing;
    BOOL mHasSelectedGuestOS;
    int mLastState;
    int mIntegrationLevel;
    int mCreationMode;
    int mDiskCreationOption;
    PLVMCreationHelper *mVmCreationHelper;
    PLVMCreationAssistantEasyInstallPanel *mEasyInstallPanel;
    PLVMCreationAssistantLocalInstallMediaPanel *mInstallMediaPanel;
    PLVMCreationAssistantIntegrationPanel *mIntegrationPanel;
    PLVMCreationAssistantChooseVMDKPanel *mLocalVMDKPanel;
    PLVMCreationAssistantChooseOSPanel *mOperatingSystemPanel;
    PLVMCreationAssistantChooseFirmwarePanel *mFirmwarePanel;
    NSString *mSelectedGuestOSName;
    DUIDeviceHardDiskProxy *mHardDiskProxy;
    NSString *mBundlePath;
}

+ (int)assistantTypeForURL:(id)arg1;
+ (BOOL)isInstallURL:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) BOOL hasSelectedGuestOS; // @synthesize hasSelectedGuestOS=mHasSelectedGuestOS;
@property(nonatomic) int diskCreationOption; // @synthesize diskCreationOption=mDiskCreationOption;
@property(nonatomic) BOOL enableFileSharing; // @synthesize enableFileSharing=mEnableFileSharing;
@property(copy, nonatomic) NSString *bundlePath; // @synthesize bundlePath=mBundlePath;
@property(nonatomic) int creationMode; // @synthesize creationMode=mCreationMode;
@property(nonatomic) int integrationLevel; // @synthesize integrationLevel=mIntegrationLevel;
@property(nonatomic) int lastState; // @synthesize lastState=mLastState;
@property(nonatomic) BOOL isSecondaryDisc; // @synthesize isSecondaryDisc=mIsSecondaryDisc;
@property(retain, nonatomic) DUIDeviceHardDiskProxy *hardDiskProxy; // @synthesize hardDiskProxy=mHardDiskProxy;
@property(copy, nonatomic) NSString *selectedGuestOSName; // @synthesize selectedGuestOSName=mSelectedGuestOSName;
@property(retain, nonatomic) PLVMCreationAssistantChooseFirmwarePanel *firmwarePanel; // @synthesize firmwarePanel=mFirmwarePanel;
@property(retain, nonatomic) PLVMCreationAssistantChooseOSPanel *operatingSystemPanel; // @synthesize operatingSystemPanel=mOperatingSystemPanel;
@property(retain, nonatomic) PLVMCreationAssistantChooseVMDKPanel *localVMDKPanel; // @synthesize localVMDKPanel=mLocalVMDKPanel;
@property(retain, nonatomic) PLVMCreationAssistantIntegrationPanel *integrationPanel; // @synthesize integrationPanel=mIntegrationPanel;
@property(retain, nonatomic) PLVMCreationAssistantLocalInstallMediaPanel *installMediaPanel; // @synthesize installMediaPanel=mInstallMediaPanel;
@property(retain, nonatomic) PLVMCreationAssistantEasyInstallPanel *easyInstallPanel; // @synthesize easyInstallPanel=mEasyInstallPanel;
@property(retain, nonatomic) PLVMCreationHelper *vmCreationHelper; // @synthesize vmCreationHelper=mVmCreationHelper;
- (BOOL)isUEFISettingAvailable;
- (id)resultID;
- (void)doCleanupOnFailure;
- (void)saveVM;
- (void)createVMDK2;
- (void)createVMDK1;
- (void)createVMDKForPath:(id)arg1 withOperation:(int)arg2 proxy:(id)arg3 defaultName:(id)arg4 doneHandler:(CDUnknownBlockType)arg5;
- (void)configureCDROM;
- (void)applyChangesForDisk:(id)arg1 proxy:(id)arg2 defaultName:(id)arg3 doneHandler:(CDUnknownBlockType)arg4;
- (void)savePanelDidEnd:(id)arg1;
- (void)findAvailableDidEndWithName:(id)arg1;
- (void)createLocal;
- (void)finishCreation;
- (id)toolsGuestKey;
@property(readonly, nonatomic) BOOL isValidIntegrationLevel;
- (void)configureCustomDetailViewContents;
- (id)displayNameByTruncatingMiddle:(id)arg1;
- (void)configureFinishView;
- (id)hardDiskFileOperationLabel;
- (void)updateVirtualDisk:(id)arg1 name:(id)arg2 operation:(int)arg3;
@property(readonly, nonatomic) BOOL isValidDiskCreationState;
@property(readonly, nonatomic) BOOL makeCustomVMDK;
- (void)resetVMDKButtons;
- (void)draggingExited:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (id)draggedTypesForState:(int)arg1;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (id)panel:(id)arg1 userEnteredFilename:(id)arg2 confirmed:(BOOL)arg3;
- (void)overwriteVMDK2:(id)arg1 nodeName:(id)arg2;
- (void)onOverwriteVMDK2Error;
- (void)openURLs:(id)arg1;
- (void)loadPanels;
- (void)configureVMCreation;
- (BOOL)start;
- (void)goBackward;
- (BOOL)goForward;
- (void)goBackwardCustom;
- (BOOL)goForwardCustom;
- (void)goBackwardInstallOS;
- (void)goBackwardForEasyInstall;
- (void)goForwardFromEasyInstall;
- (void)goForwardFromValidEasyInstall;
- (BOOL)goForwardInstallOS;
- (void)goForwardWithToolsCheck;
- (BOOL)showIntegrationPane;
- (int)startState;
- (void)gotoState:(int)arg1;
- (void)assistantWillUnload;
- (void)disableButtonsForState:(int)arg1;
- (void)stateDidChangeFromState:(int)arg1;
- (id)viewForState:(int)arg1;
- (long long)helpTag;
- (id)title;
- (id)subtitleForState:(int)arg1;
- (id)titleForState:(int)arg1;
- (id)host;
- (void)dealloc;
- (id)localizedNameForStepCustom:(long long)arg1;
- (id)localizedNameForStepInstallOS:(long long)arg1;
- (id)localizedNameForStep:(long long)arg1;
- (id)predefinedCreationSteps;
- (long long)stepIndexForStateCustom:(int)arg1;
- (long long)stepIndexForStateInstallOS:(int)arg1;
- (long long)stepIndexForState:(int)arg1;
- (id)initWithAssistantManager:(id)arg1 creationMode:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

