//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAlert, NSString;

@interface RunningProcessAlert : NSObject
{
    NSString *brePrefix;
    NSString *path;
    NSString *breSuffix;
    NSAlert *alert;
}

- (void)setInformativeText:(id)arg1;
- (void)setMessageText:(id)arg1;
- (void)dealloc;
- (void)timerHandler:(id)arg1;
- (BOOL)waitModal;
- (BOOL)waitCondition;
- (id)initWithBrePrefix:(id)arg1 path:(id)arg2 breSuffix:(id)arg3;

@end

