//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "VMIPCMessageReceiverDelegate.h"

@class MKSOpenGLView, NSString, VMIPCMessageReceiver;

@interface UIDrawnMKSController : NSObject <VMIPCMessageReceiverDelegate>
{
    unsigned int mWindowId;
    VMIPCMessageReceiver *mMessageReceiver;
    MKSOpenGLView *mView;
    NSString *mPortName;
}

+ (id)generateMachPortNameFromWindowId:(unsigned int)arg1 baseName:(id)arg2;
@property(copy) NSString *portName; // @synthesize portName=mPortName;
@property(retain) MKSOpenGLView *view; // @synthesize view=mView;
@property unsigned int windowId; // @synthesize windowId=mWindowId;
@property(retain) VMIPCMessageReceiver *messageReceiver; // @synthesize messageReceiver=mMessageReceiver;
- (void)onMessageReceiverDidTerminate:(id)arg1;
- (void)onRemoteMessageReceived:(id)arg1;
- (void)onMessageReceiverDidInitialize:(id)arg1;
- (void)shutdown;
- (void)dealloc;
- (id)initWithWindowId:(unsigned int)arg1 view:(id)arg2 portName:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

