//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMOneShotWindowController.h"

@class NSButton, NSImageView, NSTextField, VMColoredBackgroundView;

@interface VMAboutWindowController : VMOneShotWindowController
{
    VMColoredBackgroundView *backgroundView;
    VMColoredBackgroundView *bottomView;
    NSButton *acknowledgementsButton;
    NSButton *licenseAgreementButton;
    NSImageView *applicationIcon;
    NSImageView *companyIcon;
    NSTextField *applicationField;
    NSTextField *versionField;
    NSTextField *licenseField;
    NSTextField *copyrightField;
}

+ (id)windowNibName;
- (void)showLicenseAgreement:(id)arg1;
- (void)showAcknowledgements:(id)arg1;
- (void)setCompanyIcon:(id)arg1;
- (void)setApplicationIcon:(id)arg1;
- (void)setCopyrightInfo:(id)arg1;
- (void)setLicenseFieldText:(id)arg1;
- (void)setVersionString:(id)arg1;
- (void)awakeFromNib;
- (void)showWindow:(id)arg1;

@end

