//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@interface VMAlternateKeyButtonCell : NSButtonCell
{
    BOOL mIsAltEnabled;
    BOOL mIsAltKeyDown;
}

@property(nonatomic) BOOL isAltKeyDown; // @synthesize isAltKeyDown=mIsAltKeyDown;
@property(nonatomic) BOOL isAltEnabled; // @synthesize isAltEnabled=mIsAltEnabled;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)attributedAlternateTitle;
- (BOOL)isEnabled;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;

@end

