//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSLayoutConstraint, NSTextField, NSView, VMAssistant, VMColoredBackgroundView, VMDragTargetBox;

@interface VMAssistantManager : NSWindowController
{
    VMColoredBackgroundView *mainView;
    NSView *assistantView;
    NSView *containerView;
    NSView *overviewView;
    VMDragTargetBox *dragTargetView;
    NSButton *backButton;
    NSButton *forwardButton;
    NSButton *cancelButton;
    NSButton *helpButton;
    NSTextField *titleField;
    NSTextField *subtitleField;
    NSLayoutConstraint *containerViewWidth;
    NSLayoutConstraint *containerViewHeight;
    NSLayoutConstraint *overviewViewHeight;
    VMAssistant *mAssistant;
    BOOL mAppIsQuitting;
    BOOL mDisableHomePane;
    BOOL mCanCancel;
    BOOL mCanGoForward;
    BOOL mCanGoBackward;
    BOOL mShowHelpButton;
    BOOL mHideCancel;
    BOOL mHideGoForward;
    BOOL mHideGoBackward;
    VMAssistant *mHomeAssistant;
}

+ (id)assistantManager;
+ (id)allAssistantManagers;
@property(retain, nonatomic) VMAssistant *homeAssistant; // @synthesize homeAssistant=mHomeAssistant;
@property(nonatomic) BOOL hideGoBackward; // @synthesize hideGoBackward=mHideGoBackward;
@property(nonatomic) BOOL hideGoForward; // @synthesize hideGoForward=mHideGoForward;
@property(nonatomic) BOOL hideCancel; // @synthesize hideCancel=mHideCancel;
@property(nonatomic) BOOL showHelpButton; // @synthesize showHelpButton=mShowHelpButton;
@property(nonatomic) BOOL canGoBackward; // @synthesize canGoBackward=mCanGoBackward;
@property(nonatomic) BOOL canGoForward; // @synthesize canGoForward=mCanGoForward;
@property(nonatomic) BOOL canCancel; // @synthesize canCancel=mCanCancel;
@property(nonatomic) BOOL disableHomePane; // @synthesize disableHomePane=mDisableHomePane;
@property(nonatomic) BOOL appIsQuitting; // @synthesize appIsQuitting=mAppIsQuitting;
@property(retain, nonatomic) VMAssistant *assistant; // @synthesize assistant=mAssistant;
- (void)terminateAssistant:(id)arg1;
- (void)goHomeFromAssistant:(id)arg1;
- (BOOL)canGoHomeFromAssistant:(id)arg1;
- (void)assistant:(id)arg1 shouldCancel:(BOOL)arg2;
- (id)contentViewForAssistant:(id)arg1;
- (void)assistant:(id)arg1 isDragTarget:(BOOL)arg2;
- (void)assistant:(id)arg1 setContentView:(id)arg2;
- (void)assistant:(id)arg1 setContentView:(id)arg2 registerForDraggedTypes:(id)arg3;
- (void)refreshOverviewViewHeight:(double)arg1;
- (void)assistant:(id)arg1 setOverviewContentView:(id)arg2;
- (BOOL)assistant:(id)arg1 makeFirstResponder:(id)arg2;
- (BOOL)assistant:(id)arg1 makeButtonFirstResponder:(int)arg2;
- (void)assistant:(id)arg1 setForwardButtonTitle:(id)arg2;
- (void)assistant:(id)arg1 setSubtitle:(id)arg2;
- (void)assistant:(id)arg1 setTitle:(id)arg2;
- (void)installAssistant:(id)arg1;
- (void)installHomeView;
- (void)resetAssistantState;
- (id)windowTitle;
- (id)forwardButtonTitle;
- (void)cancel:(id)arg1;
- (void)forward:(id)arg1;
- (void)back:(id)arg1;
- (void)startWithAssistant:(id)arg1;
- (void)loadHomeView;
- (void)windowDidLoad;
- (void)awakeFromNib;
- (void)dealloc;

@end

