//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class NSString;

@interface VMBaseWindow : NSWindow
{
    NSString *restorationID;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *restorationID; // @synthesize restorationID;
- (void)sendEvent:(id)arg1;
- (long long)userPreferenceForTabView;
- (long long)modeForTabView;
- (void)setModeForTabView:(long long)arg1;
- (void)dragImage:(id)arg1 at:(struct CGPoint)arg2 offset:(struct CGSize)arg3 event:(id)arg4 pasteboard:(id)arg5 source:(id)arg6 slideBack:(BOOL)arg7;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)dealloc;

@end

