//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSObject, NSTextField;

@interface VMBrowseButton : NSButton
{
    NSTextField *pathTextField;
    NSObject *delegate;
}

- (void)sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)saveToFile:(id)arg1;
- (void)browseForFile:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isSaveButton;
- (void)performDefaultActionForVMBrowseButton:(id)arg1;

@end

