//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSBezierPath, NSColor;

@interface VMBubbleView : NSView
{
    float radius;
    NSBezierPath *path;
    NSColor *fillColor;
    NSColor *strokeColor;
}

- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (void)setLineWidth:(float)arg1;
- (void)setStrokeColor:(id)arg1;
- (void)setFillColor:(id)arg1;
- (id)initWithInnerView:(id)arg1 radius:(float)arg2;

@end

