//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCollectionViewDelegate.h"

@class NSCollectionView;

@protocol VMCollectionViewDelegate <NSCollectionViewDelegate>

@optional
- (void)collectionViewDeleteSelection:(NSCollectionView *)arg1;
- (BOOL)collectionViewCanDeleteSelection:(NSCollectionView *)arg1;
@end

