//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCollectionView.h"

@interface VMCollectionView : NSCollectionView
{
    BOOL isInMouseTracking;
}

@property(nonatomic) BOOL isInMouseTracking; // @synthesize isInMouseTracking;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)delete:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)keyDown:(id)arg1;
- (id)interactiveViewForEvent:(id)arg1;

@end

