//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCell.h"

@interface VMCodeExchangeCell : NSCell
{
    int mDigit;
    struct CGSize mSubcellSize;
}

@property(nonatomic) int digit; // @synthesize digit=mDigit;
@property(nonatomic) struct CGSize subcellSize; // @synthesize subcellSize=mSubcellSize;
- (id)backgroundColor;
- (id)shadowColor;
- (id)borderColor;
- (id)textColor;
- (id)shadowPathForRect:(struct CGRect)arg1;
- (void)drawFocusRingWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)digitString;
- (id)initTextCell:(id)arg1;

@end

