//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@interface VMDarkThemeWidgetCell : NSButtonCell
{
    BOOL temporarilyDisabled;
    BOOL obscured;
    long long buttonID;
}

@property(nonatomic, getter=isObscured) BOOL obscured; // @synthesize obscured;
@property(nonatomic, getter=isTemporarilyDisabled) BOOL temporarilyDisabled; // @synthesize temporarilyDisabled;
@property(nonatomic) long long buttonID; // @synthesize buttonID;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)update;
- (BOOL)isEdited;
- (int)getState:(id)arg1;
- (unsigned long long)hitTestForEvent:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3;
- (struct CGSize)cellSizeForBounds:(struct CGRect)arg1;
- (BOOL)isEnabled;
- (BOOL)_needsRedrawOnWindowChangedKeyState;
- (BOOL)_hasRolloverContentArt;

@end

