//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSThemeFrame.h"

@interface VMDarkThemeFrame : NSThemeFrame
{
}

- (void)_drawTitleBar:(struct CGRect)arg1;
- (BOOL)_inactiveButtonsNeedMask;
- (id)newCloseButton;
- (id)newMiniaturizeButton;
- (id)newZoomButton;
- (BOOL)_isDarkWindow;
- (id)bezierPathWithTitlebarRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 styleMask:(long long)arg2 owner:(id)arg3;

@end

