//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface VMDisclosureButton : NSButton
{
}

+ (Class)cellClass;
- (double)baselineOffsetFromBottom;
- (struct CGSize)triangleSize;
- (struct CGSize)intrinsicContentSize;
- (void)awakeFromNib;

@end

