//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VMDnd : NSObject
{
}

+ (void)beginDragForView:(id)arg1 withPasteboardItems:(id)arg2;
+ (id)fakeMouseEventForView:(id)arg1;
+ (id)dragImageForRTFText:(id)arg1 plainText:(id)arg2;

@end

