//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface VMDocker : NSObject
{
    NSDictionary *infoPlist;
    NSString *dockerPath;
    NSString *mVMUUID;
}

@property(copy, nonatomic) NSString *vmUUID; // @synthesize vmUUID=mVMUUID;
- (void)writeInfoPlistToDisk;
- (id)infoPlistPath;
- (void)setInfoPlist:(id)arg1;
- (void)dealloc;
- (id)viewAppEntitlementID;
- (id)viewConnectionServerURL;
- (id)urlHandlers;
- (id)fileHandlers;
- (BOOL)isDefaultGuestApp;
- (id)guestAppName;
- (id)guestAppURI;
- (id)vmConfigPath;
- (id)hostAppBundleIdentifier;
- (id)hostAppName;
- (void)setHasUI:(BOOL)arg1;
- (BOOL)hasUI;
- (id)initWithDockerAtPath:(id)arg1;

@end

