//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@class NSView;

@interface VMDualViewScrollView : NSScrollView
{
    NSView *childView;
}

- (void)tile;
- (void)overlayTile;
- (void)legacyTile;
- (void)awakeFromNib;

@end

