//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSProgressIndicator, NSWindow;

@interface VMFileDescriptorProgress : NSObject
{
    NSWindow *win;
    NSProgressIndicator *progress;
    NSData *fdData;
}

@property(retain) NSData *fdData; // @synthesize fdData;
- (void)eofHandler:(id)arg1;
- (void)waitModal:(int)arg1;
- (void)show:(id)arg1;
- (void)dealloc;

@end

