//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrubberItemView.h"

@class NSButton;

@interface VMFnScrubberItemView : NSScrubberItemView
{
    NSButton *mButton;
}

@property(readonly, retain, nonatomic) NSButton *button; // @synthesize button=mButton;
- (void)configureConstraints;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

