//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextField.h"

@class NSLayoutConstraint;

@interface VMGrowingTextField : NSTextField
{
    NSLayoutConstraint *mWidthConstraint;
    double mWidthOffset;
}

+ (BOOL)requiresConstraintBasedLayout;
+ (Class)cellClass;
@property(nonatomic) double widthOffset; // @synthesize widthOffset=mWidthOffset;
@property(retain, nonatomic) NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=mWidthConstraint;
- (void)textViewFrameDidChange:(id)arg1;
- (void)updateConstraints;
- (void)awakeFromNib;
- (void)dealloc;

@end

