//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface VMIPCMessage : NSObject
{
    NSString *name;
    NSString *object;
    NSDictionary *userInfo;
}

- (void)dealloc;
- (id)description;
- (id)matchesInObserverArray:(id)arg1;
- (id)propertyList;
- (id)userInfo;
- (id)object;
- (id)name;
- (id)initWithName:(id)arg1 object:(id)arg2 userInfo:(id)arg3;
- (id)initWithInfo:(id)arg1;

@end

