//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSThread;

@interface VMIPCMessageSender : NSObject
{
    BOOL syncMessageSent;
    NSThread *messageSenderThread;
}

@property BOOL syncMessageSent; // @synthesize syncMessageSent;
@property(retain) NSThread *messageSenderThread; // @synthesize messageSenderThread;
- (BOOL)sendMessage:(id)arg1 toPort:(id)arg2 synchronous:(BOOL)arg3;
- (void)stopSender;
- (void)workerThreadStopRunning;
- (void)workerThreadSendMessage:(id)arg1;
- (void)workerThreadStartRunning;
- (void)startSenderThread;
- (id)init;

@end

