//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "VMIPCMessageReceiverDelegate.h"

@class NSMutableDictionary, NSString, VMIPCMessageReceiver, VMIPCMessageSender;

@interface VMIPCCommon : NSObject <VMIPCMessageReceiverDelegate>
{
    NSMutableDictionary *observerTable;
    NSMutableDictionary *lastMessageIDs;
    VMIPCMessageReceiver *messageReceiver;
    id terminateDelegate;
    SEL terminateSelector;
    VMIPCMessageSender *messageSender;
}

@property SEL terminateSelector; // @synthesize terminateSelector;
@property(retain) id terminateDelegate; // @synthesize terminateDelegate;
@property(retain) VMIPCMessageSender *messageSender; // @synthesize messageSender;
@property(retain) VMIPCMessageReceiver *messageReceiver; // @synthesize messageReceiver;
@property(retain) NSMutableDictionary *lastMessageIDs; // @synthesize lastMessageIDs;
@property(retain) NSMutableDictionary *observerTable; // @synthesize observerTable;
- (void)dispatchMessageToLocalListeners:(id)arg1;
- (void)onMessageReceiverDidTerminate:(id)arg1;
- (void)onRemoteMessageReceived:(id)arg1;
- (void)onMessageReceiverDidInitialize:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)portName;
- (void)terminateWithDelegate:(id)arg1 selector:(SEL)arg2;
- (BOOL)postMessage:(id)arg1 synchronously:(BOOL)arg2;
- (void)removeEntries:(id)arg1 forObserver:(id)arg2;
- (void)addEntries:(id)arg1 forObserver:(id)arg2;
- (BOOL)allowIncomingMessages;
- (void)setAllowIncomingMessages:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

