//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@protocol VMIPCMessageReceiverDelegate <NSObject>
- (void)onMessageReceiverDidTerminate:(id)arg1;
- (void)onRemoteMessageReceived:(NSMutableDictionary *)arg1;
- (void)onMessageReceiverDidInitialize:(id)arg1;
@end

