//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMIPCCommon.h"

@class NSMutableDictionary;

@interface VMIPCServer : VMIPCCommon
{
    NSMutableDictionary *clientMessageDictionary;
    NSMutableDictionary *clientAppDictionary;
}

@property(retain) NSMutableDictionary *clientAppDictionary; // @synthesize clientAppDictionary;
@property(retain) NSMutableDictionary *clientMessageDictionary; // @synthesize clientMessageDictionary;
- (id)portName;
- (void)onRemoveListener:(id)arg1;
- (void)onAddListener:(id)arg1;
- (id)clientsForMessage:(id)arg1;
- (void)removeClient:(id)arg1;
- (void)onApplicationTerminated:(id)arg1;
- (BOOL)postMessage:(id)arg1 synchronously:(BOOL)arg2;
- (void)dealloc;
- (void)terminateWithDelegate:(id)arg1 selector:(SEL)arg2;
- (void)onMessageReceiverDidInitialize:(id)arg1;
- (void)setAllowIncomingMessages:(BOOL)arg1;
- (id)init;

@end

