//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString, NSTimer, VMToolbarSegmentedControl;

@interface VMLedSegmentItem : NSObject
{
    NSImage *stateStatusImages[10];
    NSImage *disconnectedStatusImage;
    NSString *disconnectedAccessibleDescription;
    NSString *connectedAccessibleDescription;
    int ledState;
    int transitionIndex;
    BOOL hasLabel;
    long long segment;
    VMToolbarSegmentedControl *segmentedControl;
    NSTimer *timer;
    NSString *imageName;
}

@property(retain, nonatomic) NSString *connectedAccessibleDescription; // @synthesize connectedAccessibleDescription;
@property(retain, nonatomic) NSString *disconnectedAccessibleDescription; // @synthesize disconnectedAccessibleDescription;
@property(retain, nonatomic) NSImage *disconnectedStatusImage; // @synthesize disconnectedStatusImage;
@property(nonatomic) VMToolbarSegmentedControl *segmentedControl; // @synthesize segmentedControl;
@property(nonatomic) int ledState; // @synthesize ledState;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName;
- (BOOL)generateImagesForName:(id)arg1;
- (void)drawBitmap:(id)arg1 withAlpha:(float)arg2 intoBitmap:(id)arg3;
- (BOOL)loadImagesForName:(id)arg1;
- (id)imageRepFromTemplate:(id)arg1 forState:(int)arg2 scale:(unsigned long long)arg3;
- (void)timerFired:(id)arg1;
- (void)setTimer:(id)arg1;
- (BOOL)needsTimer;
- (void)releaseImages;
- (void)dealloc;
- (void)setImageNamed:(id)arg1;
- (BOOL)skipTransition;
- (void)setAccessibilityDescription:(id)arg1 forLedState:(int)arg2;
- (id)accessibilityDescription;
- (id)currentImage;
- (id)controlView;
- (id)initForImageNamed:(id)arg1 forSegment:(long long)arg2 inControl:(id)arg3;

@end

