//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VMLicense : NSObject
{
    struct LicenseAttr *licenseAttr;
    int attrStatus;
    int licenseType;
}

+ (id)license;
+ (id)licenseForVersion:(const char *)arg1;
- (id)lastModifiedDate;
- (id)licenseEdition;
- (id)serial;
- (id)stringValueForAttribute:(const char *)arg1;
- (int)licenseType;
- (BOOL)expires;
- (BOOL)expires:(id *)arg1 daysLeft:(unsigned int *)arg2;
- (BOOL)isExpired;
- (int)currentLicenseType;
- (void)dealloc;
- (id)init;
- (id)initForVersion:(const char *)arg1;

@end

