//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSColor, NSImage, NSString;

@interface VMNamedColorButton : NSButton
{
    NSString *colorName;
    NSColor *buttonColor;
    NSImage *baseImage;
}

+ (Class)cellClass;
@property(retain, nonatomic) NSColor *buttonColor; // @synthesize buttonColor;
@property(retain, nonatomic) NSImage *baseImage; // @synthesize baseImage;
@property(retain, nonatomic) NSString *colorName; // @synthesize colorName;
- (void)setImage:(id)arg1;
- (void)dealloc;

@end

