//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@class NSArray, NSMutableArray, VMNavigationSubcell;

@interface VMNavigationCell : NSButtonCell
{
    NSMutableArray *subcells;
    BOOL needsLayout;
    long long firstResponderIndex;
    VMNavigationSubcell *selectedSubcell;
}

@property(readonly) long long firstResponderIndex; // @synthesize firstResponderIndex;
@property(retain) VMNavigationSubcell *selectedSubcell; // @synthesize selectedSubcell;
@property(retain) NSArray *subcells; // @synthesize subcells;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (void)pushItemWithTitle:(id)arg1 representedObject:(id)arg2 toolTip:(id)arg3;
- (void)subcellAction:(id)arg1;
- (long long)clickIndex;
- (void)popLastItem;
- (void)popToFirst;
- (void)popItems;
- (void)popItemsStartingWith:(id)arg1;
- (struct CGSize)cellSize;
- (void)calcDrawInfo:(struct CGRect)arg1;
- (id)subcellAtPoint:(struct CGPoint)arg1 withFrame:(struct CGRect)arg2;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)handleKeyDown:(id)arg1;
- (void)drawFocusRingForBounds:(struct CGRect)arg1;
- (id)activeFocusSubcell;
- (id)bezierPathForCell:(id)arg1 withCellBounds:(struct CGRect)arg2 forFocus:(BOOL)arg3;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initImageCell:(id)arg1;
- (id)initTextCell:(id)arg1;
- (id)init;
- (void)commonInit;
- (void)setAccessibilitySubcellFocus:(id)arg1;
- (id)accessibilityFocusedUIElement;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (BOOL)accessibilityIsIgnored;

@end

