//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@class NSBezierPath, NSString;

@interface VMNavigationSubcell : NSTextFieldCell
{
    struct CGRect cellBounds;
    NSBezierPath *bezierPath;
    NSString *toolTip;
    BOOL drawSelected;
    BOOL isFirstCell;
    BOOL isLastCell;
}

@property(retain) NSString *toolTip; // @synthesize toolTip;
@property(retain) NSBezierPath *bezierPath; // @synthesize bezierPath;
@property struct CGRect cellBounds; // @synthesize cellBounds;
@property BOOL drawSelected; // @synthesize drawSelected;
@property BOOL isLastCell; // @synthesize isLastCell;
@property BOOL isFirstCell; // @synthesize isFirstCell;
- (BOOL)trackMouse:(id)arg1 inRect:(struct CGRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;
- (struct CGRect)drawingRectForBounds:(struct CGRect)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGSize)cellSize;
- (double)lastCellOffset;
- (double)firstCellOffset;
- (void)dealloc;
- (id)initTextCell:(id)arg1;
- (id)accessibilityFocusedUIElement;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;

@end

