//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface VMNetworkInterface : NSObject
{
    BOOL mDisabled;
    BOOL mActive;
    int mIpState;
    NSString *mBSDName;
    unsigned long long mServiceOrderIndex;
    NSString *mLocalizedName;
    NSString *mCustomVMNetKey;
    NSString *mServiceID;
}

+ (id)imageForState:(int)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) NSString *serviceID; // @synthesize serviceID=mServiceID;
@property(retain, nonatomic) NSString *customVMNetKey; // @synthesize customVMNetKey=mCustomVMNetKey;
@property(retain, nonatomic) NSString *localizedName; // @synthesize localizedName=mLocalizedName;
@property(nonatomic) unsigned long long serviceOrderIndex; // @synthesize serviceOrderIndex=mServiceOrderIndex;
@property(retain, nonatomic) NSString *bsdName; // @synthesize bsdName=mBSDName;
@property(nonatomic) int ipState; // @synthesize ipState=mIpState;
@property(nonatomic) BOOL active; // @synthesize active=mActive;
@property(nonatomic) BOOL disabled; // @synthesize disabled=mDisabled;
- (long long)compare:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (int)state;
- (id)stateImage;
- (void)dealloc;
- (id)initWithBsdName:(id)arg1 serviceID:(id)arg2 localizedName:(id)arg3;

@end

