//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArrayController.h"

@interface VMNetworkInterfaceController : NSArrayController
{
    struct __SCDynamicStore *dynamicStore;
    struct __CFRunLoopSource *runLoopSource;
}

+ (BOOL)hasInterfacesWithBSDName:(id)arg1;
- (id)currentServices:(struct __SCPreferences *)arg1;
- (void)onKeysChanged:(id)arg1;
- (BOOL)onInterfaceKeyChanged:(id)arg1;
- (BOOL)onServiceStateKeyChanged:(id)arg1;
- (BOOL)onServiceSetupKeyChanged:(id)arg1;
- (void)addInterfaceWithServiceRef:(struct __SCNetworkService *)arg1;
- (id)addInterfaceWithServiceRef:(struct __SCNetworkService *)arg1 withInterfaceRef:(struct __SCNetworkInterface *)arg2;
- (id)ipV4ValuesForInterface:(id)arg1;
- (id)serviceValuesForInterface:(id)arg1;
- (int)ipStateForServiceRef:(struct __SCNetworkService *)arg1;
- (BOOL)isIPv4LinkLocal:(id)arg1;
- (id)interfacesForBsdName:(id)arg1;
- (struct __SCNetworkService *)serviceRefForServiceID:(id)arg1;
- (id)interfaceForServiceID:(id)arg1;
- (int)mostActiveState;
- (void)refreshInterfaces;
- (void)refreshServiceOrder;
- (void)dealloc;
- (id)init;

@end

