//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VMObjectTracker : NSObject
{
}

+ (id)deallocHelperForObject:(id)arg1;
+ (CDUnknownBlockType)registerZeroingWeakRefLocation:(id *)arg1;
+ (void)notifyDeallocDidStartForObject:(id)arg1;
+ (CDUnknownBlockType)addDeallocDidFinishObserver:(CDUnknownBlockType)arg1 forObject:(id)arg2;
+ (CDUnknownBlockType)addDeallocDidStartObserver:(CDUnknownBlockType)arg1 forObject:(id)arg2;

@end

