//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@class NSArray, NSString, NSView;

@interface VMOpenPanelPopUpButton : NSPopUpButton
{
    NSString *filename;
    NSArray *filetypes;
    NSString *prompt;
    NSString *defaultTitle;
    NSString *message;
    NSString *directoryPreferenceKey;
    BOOL isSavePanel;
    NSString *directoryPath;
    NSString *defaultFilename;
    BOOL canChooseFiles;
    BOOL canChooseDirectories;
    BOOL canCreateDirectories;
    BOOL treatsFilePackagesAsDirectories;
    id delegate;
    NSView *accessoryView;
}

@property(retain) NSString *directoryPreferenceKey; // @synthesize directoryPreferenceKey;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)setItems;
- (void)browseForFile:(id)arg1;
- (void)browseForFileToSave;
- (void)browseForFileToOpen;
- (void)setPanelValues:(id)arg1;
- (void)selectedItemAction:(id)arg1;
- (void)browseForFileDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (id)defaultFilename;
- (BOOL)canChooseDirectories;
- (BOOL)canChooseFiles;
- (id)filetypes;
- (id)filename;
- (void)setDefaultFilename:(id)arg1;
- (void)setDirectoryPath:(id)arg1;
- (void)setPrompt:(id)arg1;
- (void)setTreatsFilePackagesAsDirectories:(BOOL)arg1;
- (void)setCanCreateDirectories:(BOOL)arg1;
- (void)setCanChooseDirectories:(BOOL)arg1;
- (void)setCanChooseFiles:(BOOL)arg1;
- (void)setDefaultTitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setAccessoryView:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setMessage:(id)arg1;
- (void)setIsSavePanel:(BOOL)arg1;
- (void)setFiletypes:(id)arg1;
- (void)setFilename:(id)arg1;

@end

