//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSControl.h"

@class NSMutableArray;

@interface VMPieChart : NSControl
{
    NSMutableArray *segments;
    BOOL needsLayout;
    BOOL isGeneratingContent;
    BOOL showToolTips;
    unsigned long long segmentCount;
    int pieStyle;
    long long backgroundStyle;
}

@property(nonatomic) BOOL showToolTips; // @synthesize showToolTips;
@property(nonatomic) BOOL isGeneratingContent; // @synthesize isGeneratingContent;
@property(nonatomic) unsigned long long segmentCount; // @synthesize segmentCount;
@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle;
@property(nonatomic) int pieStyle; // @synthesize pieStyle;
- (BOOL)setColorName:(id)arg1 forSegment:(long long)arg2;
- (id)colorForSegment:(long long)arg1;
- (void)setColor:(id)arg1 forSegment:(long long)arg2;
- (float)floatValueForSegment:(long long)arg1;
- (void)setFloatValue:(float)arg1 forSegment:(long long)arg2;
- (id)toolTipForSegment:(long long)arg1;
- (void)setToolTip:(id)arg1 forSegment:(long long)arg2;
- (id)formatStringForSegment:(long long)arg1;
- (void)setFormatString:(id)arg1 forSegment:(long long)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawBarPieInRect:(struct CGRect)arg1;
- (void)drawRoundPieInRect:(struct CGRect)arg1;
- (float)totalValue;
- (struct CGRect)chartRectForBounds:(struct CGRect)arg1;
- (id)segmentAtPoint:(struct CGPoint)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (id)stringForToolTip:(long long)arg1 point:(struct CGPoint)arg2 segment:(id)arg3;
- (void)doLayout;
- (void)doLayoutBar;
- (void)doLayoutRound;
- (id)legendImageForSegment:(long long)arg1;
- (void)drawSegmentsInRect:(struct CGRect)arg1;
- (void)generateSegments;
- (id)makeSegment;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;

@end

