//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMGrowingTextField.h"

@interface VMRolloverTextField : VMGrowingTextField
{
    long long trackingRectTag;
    BOOL hasMouseOver;
}

- (void)dealloc;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)removeTrackingRect;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingRect:(id)arg1;
- (struct CGRect)trackingRect;
- (void)setFrame:(struct CGRect)arg1;
- (BOOL)shouldDrawRolloverEffect;

@end

