//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface VMSharedData : NSObject
{
    int dataFD;
    NSData *data;
}

- (void)unmap;
- (BOOL)setSharedMemoryName:(id)arg1 isWritable:(BOOL)arg2 error:(id *)arg3;
- (BOOL)mapWithLength:(unsigned long long)arg1 isWritable:(BOOL)arg2 isPrivate:(BOOL)arg3 error:(id *)arg4;
- (void)closeFD;
- (void)dealloc;
- (id)sharedData;
- (id)initWithSharedMemoryName:(id)arg1 length:(unsigned long long)arg2 isWritable:(BOOL)arg3 isPrivate:(BOOL)arg4 error:(id *)arg5;

@end

