//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXMLParserDelegate.h"

@class NSMutableString, NSString, NSXMLParser;

@interface VMSimpleXMLParser : NSObject <NSXMLParserDelegate>
{
    id delegate;
    SEL selector;
    NSXMLParser *parser;
    NSMutableString *currentStringValue;
    NSString *elementName;
}

@property(retain) NSString *elementName; // @synthesize elementName;
@property(retain) NSMutableString *currentStringValue; // @synthesize currentStringValue;
@property(retain) NSXMLParser *parser; // @synthesize parser;
@property id delegate; // @synthesize delegate;
- (void)dealloc;
- (BOOL)parse;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 foundCharacters:(id)arg2;
- (id)initWithDelegate:(id)arg1 filename:(id)arg2 elementName:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

