//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VMSlider.h"

@class NSValueTransformer;

@interface VMSnapSlider : VMSlider
{
    int mTransformedStep;
    NSValueTransformer *mTransformer;
}

@property(nonatomic) int transformedStep; // @synthesize transformedStep=mTransformedStep;
@property(retain, nonatomic) NSValueTransformer *transformer; // @synthesize transformer=mTransformer;
- (void)mouseDown:(id)arg1;
- (void)moveRight:(id)arg1;
- (void)moveLeft:(id)arg1;
- (void)setBoundValue:(id)arg1;
- (id)boundValue;
- (void)dealloc;

@end

