//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLevelIndicatorCell.h"

@interface VMSpeedometerLevelIndicatorCell : NSLevelIndicatorCell
{
}

- (void)drawArcWithCenter:(struct CGPoint)arg1 startAngle:(double)arg2 endAngle:(double)arg3 arcRadius:(double)arg4 radius:(double)arg5 tickmark:(id)arg6 color:(id)arg7;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)tickMarkPath;
- (id)speedPointerPath;

@end

