//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSLayoutConstraint;

@interface VMStackLayoutView : NSView
{
    BOOL mIsHorizontal;
    NSLayoutConstraint *mEmptyConstraint;
    NSLayoutConstraint *mEndConstraint;
    NSLayoutConstraint *mStartConstraint;
    double mSpacing;
}

+ (BOOL)requiresConstraintBasedLayout;
@property(nonatomic) BOOL isHorizontal; // @synthesize isHorizontal=mIsHorizontal;
@property(nonatomic) double spacing; // @synthesize spacing=mSpacing;
@property(retain, nonatomic) NSLayoutConstraint *startConstraint; // @synthesize startConstraint=mStartConstraint;
@property(retain, nonatomic) NSLayoutConstraint *endConstraint; // @synthesize endConstraint=mEndConstraint;
@property(retain, nonatomic) NSLayoutConstraint *emptyConstraint; // @synthesize emptyConstraint=mEmptyConstraint;
- (id)description;
- (void)willRemoveSubview:(id)arg1;
- (void)addSubview:(id)arg1;
- (void)addSubview:(id)arg1 positioned:(long long)arg2 relativeTo:(id)arg3;
- (void)insertConstrainedSubview:(id)arg1 afterView:(id)arg2;
- (id)constraintWithSecondItem:(id)arg1;
- (id)constraintWithFirstItem:(id)arg1;
@property(readonly, nonatomic) double adjustedSpacing;
- (long long)fixedFarEdge;
- (long long)fixedNearEdge;
- (long long)farEdge;
- (long long)nearEdge;
- (id)initWithFrame:(struct CGRect)arg1;

@end

