//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class VMSubtreeView;

@interface VMSubtreeViewItem : NSViewController
{
    struct CGSize _minimumSize;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(nonatomic) struct CGSize minimumSize; // @synthesize minimumSize=_minimumSize;
- (void)awakeFromNib;
@property(readonly, retain, nonatomic) VMSubtreeView *subtreeView;

@end

