//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSArray, NSImage, VMTOCBulletMatrix;

@interface VMTableOfContentsView : NSView
{
    VMTOCBulletMatrix *tocMatrix;
    NSArray *labelArray;
    long long selectedIndex;
    NSImage *highlightedImage;
    NSImage *normalImage;
}

@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex;
@property(retain, nonatomic) NSImage *normalImage; // @synthesize normalImage;
@property(retain, nonatomic) NSImage *highlightedImage; // @synthesize highlightedImage;
@property(retain, nonatomic) NSArray *labelArray; // @synthesize labelArray;
- (void)updateTableOfContents;
- (void)stepBackward;
- (void)stepForward;
- (double)preferredWidth;
@property(nonatomic) NSArray *labels;
- (void)dealloc;

@end

