//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@interface VMTableView : NSTableView
{
    BOOL isPerformingDoubleAction;
}

- (void)deleteBackward:(id)arg1;
- (void)deleteForward:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (void)deleteSelection;
- (void)delete:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (long long)clickedRow;
- (long long)clickedColumn;
- (void)performDoubleAction;
- (void)keyDown:(id)arg1;

@end

