//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor;

@interface VMTreeContainerView : NSView
{
    NSColor *borderColor;
    double borderWidth;
    double cornerRadius;
    NSColor *fillColor;
    BOOL showingSelected;
}

+ (id)defaultAnimationForKey:(id)arg1;
@property(copy, nonatomic) NSColor *fillColor; // @synthesize fillColor;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(copy, nonatomic) NSColor *borderColor; // @synthesize borderColor;
@property(nonatomic) BOOL showingSelected; // @synthesize showingSelected;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)highlightColor;
- (void)drawRect:(struct CGRect)arg1;
- (void)setLayer:(id)arg1;
- (void)updateLayerAppearanceToMatchContainerView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)commonInit;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;

@end

