//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSBundle, NSColor, NSMapTable, NSMutableSet, NSSet, NSString, VMSubtreeView;

@interface VMTreeView : NSView
{
    id <VMTreeViewModelNode> modelRoot;
    NSString *nodeViewNibName;
    NSBundle *nodeViewNibBundle;
    NSMutableSet *selectedModelNodes;
    struct CGSize minimumFrameSize;
    BOOL animatesLayout;
    BOOL layoutAnimationSuppressed;
    double contentMargin;
    double parentChildSpacing;
    double siblingSpacing;
    BOOL resizesToFillEnclosingScrollView;
    NSColor *backgroundColor;
    NSColor *connectingLineColor;
    double connectingLineWidth;
    long long connectingLineStyle;
    double mScaleFactor;
    double mMinScaleFactor;
    id <VMTreeViewDelegate> mDelegate;
    NSMapTable *mModelNodeToViewItemMapTable;
}

+ (id)defaultAnimationForKey:(id)arg1;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
@property(retain, nonatomic) NSMapTable *modelNodeToViewItemMapTable; // @synthesize modelNodeToViewItemMapTable=mModelNodeToViewItemMapTable;
@property(nonatomic) id <VMTreeViewDelegate> delegate; // @synthesize delegate=mDelegate;
@property(nonatomic) double minScaleFactor; // @synthesize minScaleFactor=mMinScaleFactor;
@property(nonatomic) double scaleFactor; // @synthesize scaleFactor=mScaleFactor;
@property(retain, nonatomic) id <VMTreeViewModelNode> modelRoot; // @synthesize modelRoot;
@property(nonatomic) BOOL resizesToFillEnclosingScrollView; // @synthesize resizesToFillEnclosingScrollView;
@property(retain, nonatomic) NSBundle *nodeViewNibBundle; // @synthesize nodeViewNibBundle;
@property(copy, nonatomic) NSString *nodeViewNibName; // @synthesize nodeViewNibName;
@property(nonatomic) double connectingLineWidth; // @synthesize connectingLineWidth;
@property(copy, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor;
@property(nonatomic) long long connectingLineStyle; // @synthesize connectingLineStyle;
@property(copy, nonatomic) NSColor *connectingLineColor; // @synthesize connectingLineColor;
@property(nonatomic) double siblingSpacing; // @synthesize siblingSpacing;
@property(nonatomic) double parentChildSpacing; // @synthesize parentChildSpacing;
@property(nonatomic) double contentMargin; // @synthesize contentMargin;
@property(nonatomic) struct CGSize minimumFrameSize; // @synthesize minimumFrameSize;
@property(nonatomic) BOOL layoutAnimationSuppressed; // @synthesize layoutAnimationSuppressed;
@property(nonatomic) BOOL animatesLayout; // @synthesize animatesLayout;
- (id)siblingOfModelNode:(id)arg1 atRelativeIndex:(long long)arg2;
- (BOOL)modelNodeIsInAssignedTree:(id)arg1;
- (BOOL)modelNode:(id)arg1 isDescendantOf:(id)arg2;
- (id)subtreeViewForModelNode:(id)arg1;
- (id)viewItemForModelNode:(id)arg1;
- (void)swipeWithEvent:(id)arg1;
- (void)magnifyWithEvent:(id)arg1;
- (void)endGestureWithEvent:(id)arg1;
- (void)beginGestureWithEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstMouse;
- (void)keyDown:(id)arg1;
- (void)moveRight:(id)arg1;
- (void)moveLeft:(id)arg1;
- (void)moveDown:(id)arg1;
- (void)moveUp:(id)arg1;
- (void)moveToNearestChild:(id)arg1;
- (void)moveToParent:(id)arg1;
- (void)moveToSiblingByRelativeIndex:(long long)arg1;
- (BOOL)acceptsFirstResponder;
- (id)modelNodeAtPoint:(struct CGPoint)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isOpaque;
- (void)scrollSelectedModelNodesToVisible;
- (void)scrollModelNodesToVisible:(id)arg1;
- (struct CGRect)boundsOfModelNodes:(id)arg1;
- (void)toggleExpansionOfSelectedModelNodes:(id)arg1;
- (void)expandRoot;
- (void)collapseRoot;
- (void)setNeedsGraphLayout;
- (BOOL)needsGraphLayout;
- (struct CGSize)layoutGraphIfNeeded;
- (void)viewWillDraw;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)parentClipViewDidResize:(id)arg1;
- (void)updateRootSubtreeViewPositionForSize:(struct CGSize)arg1;
- (void)updateFrameSizeForContentAndClipView;
- (void)buildGraph;
- (void)reloadData;
- (id)recursiveRebuildGraphForModelNode:(id)arg1 newMap:(id)arg2;
- (id)newItemForRepresentedObject:(id)arg1;
@property(readonly, nonatomic) struct CGRect selectionBounds;
@property(readonly, nonatomic) id <VMTreeViewModelNode> singleSelectedModelNode;
@property(copy, nonatomic) NSSet *selectedModelNodes;
@property(readonly, nonatomic) VMSubtreeView *rootSubtreeView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)commonInit;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;

@end

