//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface VMW_DelegatingView : NSView
{
    id <VMW_ViewDelegate> delegate;
}

+ (id)delegateNotifications;
@property(nonatomic) id <VMW_ViewDelegate> delegate; // @synthesize delegate;
- (void)dispatchNotificationToDelegate:(id)arg1;
- (void)willRemoveSubview:(id)arg1;
- (void)didAddSubview:(id)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewDidMoveToSuperview;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)viewDidUnhide;
- (void)viewDidHide;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)setNextResponder:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)canBecomeKeyView;
- (BOOL)acceptsFirstResponder;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

